// Real-auth native staging only. This script refuses production URLs and fixtures.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { chromium } from 'playwright';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const envFile = process.env.STANDUP_STAGE_ENV;
if (!envFile) throw new Error('Supply the private native staging environment path');
const env = Object.fromEntries(readFileSync(envFile, 'utf8').split('\n').filter(line => line.includes('=') && !line.startsWith('#')).map(line => { const at = line.indexOf('='); return [line.slice(0, at), line.slice(at + 1).replace(/^['"]|['"]$/g, '')]; }));
const origin = process.env.STANDUP_STAGE_APP ?? 'http://localhost:4359';
if (!['127.0.0.1', 'localhost'].includes(new URL(origin).hostname) || new URL(env.NEXT_PUBLIC_SUPABASE_URL).hostname !== '127.0.0.1' || !env.STANDUP_TEST_ORGANIZATION_ID?.endsWith('999990')) throw new Error('Only isolated synthetic staging is permitted');
const output = process.env.STANDUP_STAGE_EVIDENCE;
if (!output) throw new Error('Supply explicit evidence directory');
mkdirSync(output, { recursive: true, mode: 0o700 });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const failures = [];
page.on('pageerror', error => failures.push(error.message));
page.on('console', message => { if (message.type() === 'error') failures.push(message.text()); });
const checks = {};
try {
  await page.goto(`${origin}/login`, { waitUntil: 'domcontentloaded' });
  await page.getByLabel('Work Email').fill(env.STANDUP_TEST_EMAIL);
  await page.getByLabel('Password', { exact: true }).fill(env.STANDUP_TEST_PASSWORD);
  await page.getByRole('button', { name: /sign in/i }).click();
  await page.waitForURL(url => !url.pathname.startsWith('/login'), { timeout: 60000 });
  checks.realAuth = true;
  await page.goto(`${origin}/admin/stand-up`, { waitUntil: 'domcontentloaded' });
  const facility = page.getByRole('combobox', { name: 'Facility', exact: true });
  await facility.waitFor({ timeout: 60000 });
  await facility.selectOption(env.STANDUP_TEST_FACILITY_ID);
  const fields = ['monthly_rent_roll_cents','current_total_census','sp_female_beds_open','sp_male_beds_open','sp_flexible_beds_open','private_beds_open','admissions_expected','hospital_and_rehab_total','expected_discharges','callouts_last_week','terminations_last_week','current_open_positions','overtime_reported','tours_expected','provider_activities_expected','outreach_engagements'];
  for (const key of fields) await page.locator(`#${key}`).fill(key === 'monthly_rent_roll_cents' ? '1000.25' : key === 'current_total_census' ? '10' : '0');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await page.getByText(/Saved receipt: revision/).waitFor({ timeout: 30000 });
  checks.saveReceipt = true;
  const command = async (action, payload = {}) => {
    const response = await page.request.post(`${origin}/api/stand-up`, { data: { action, payload }, headers: { Origin: origin } });
    const data = await response.json();
    assert.equal(response.status(), 200, `${action}: ${JSON.stringify(data)}`);
    return data;
  };
  const workspace = await command('workspace');
  const scope = { facility_id: env.STANDUP_TEST_FACILITY_ID, week_start: workspace.current_week };
  const exported = await command('export', scope);
  assert.equal(exported.values.monthly_rent_roll_cents, 100025);
  assert.equal(exported.values.callouts_last_week, 0);
  checks.centsAndZero = true;
  const incoming = { ...exported.values, current_total_census: 12 };
  await command('save', { ...scope, expected_version: exported.version, request_id: crypto.randomUUID(), values: { ...exported.values, current_total_census: 11 }, status: 'draft' });
  const preview = await command('preview_recovery', { ...scope, baseline_id: exported.baseline_id, values: incoming });
  assert.ok(preview.conflicts.includes('current_total_census'));
  await page.getByRole('button', { name: 'Refresh saved reports', exact: true }).click();
  await page.getByRole('button', { name: `Review recovery ${preview.preview_id}`, exact: true }).click();
  // Keep the current Haven value explicitly; the file's contrary value is not silently imported.
  const conflict = page.getByRole('textbox', { name: 'Resolve Current census', exact: true });
  await conflict.waitFor({ timeout: 15000 });
  await conflict.fill('11');
  const recoveryResponse = page.waitForResponse(response => response.url() === `${origin}/api/stand-up` && response.request().postDataJSON()?.action === 'commit_recovery');
  await page.getByRole('button', { name: /Apply reviewed recovery/ }).click();
  assert.equal((await recoveryResponse).status(), 200);
  await page.getByRole('button', { name: /Apply reviewed recovery/ }).waitFor({ state: 'hidden', timeout: 30000 });
  const recovered = await command('export', scope);
  assert.equal(recovered.values.current_total_census, 11);
  assert.ok(!(await command('workspace')).pending_recoveries.some(item => item.preview_id === preview.preview_id));
  checks.reviewedRecovery = true;
  await page.evaluate(() => { for (const element of document.querySelectorAll('main, main *')) { if (element.scrollHeight > element.clientHeight) element.scrollTop = 0; } window.scrollTo(0, 0); });
  await page.screenshot({ path: `${output}/stand-up-desktop.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${output}/stand-up-phone.png`, fullPage: true });
  checks.phoneOverflow = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1);
  assert.ok(checks.phoneOverflow, 'Phone viewport overflow');
  const axePath = new URL('../../node_modules/axe-core/axe.min.js', import.meta.url);
  await page.addScriptTag({ path: fileURLToPath(axePath) });
  const axe = await page.evaluate(async () => (await window.axe.run(document.querySelector('main'), { runOnly: { type: 'tag', values: ['wcag2a','wcag2aa','wcag21aa'] } })).violations.map(v => ({ id: v.id, impact: v.impact, count: v.nodes.length })));
  checks.accessibilityViolations = axe;
  assert.equal(axe.length, 0, JSON.stringify(axe));
  checks.pageErrors = failures;
  assert.equal(failures.length, 0, JSON.stringify(failures));
  writeFileSync(`${output}/browser-proof.json`, JSON.stringify({ pass: true, target: origin, synthetic: true, checks }, null, 2), { mode: 0o600 });
  console.log(JSON.stringify({ pass: true, checks }));
} catch (error) {
  await page.screenshot({ path: `${output}/stand-up-failure.png`, fullPage: true }).catch(() => {});
  writeFileSync(`${output}/browser-proof.json`, JSON.stringify({ pass: false, target: origin, synthetic: true, checks, pageErrors: failures, error: String(error) }, null, 2), { mode: 0o600 });
  throw error;
} finally { await browser.close(); }
