/**
 * Executive Report Generator — produces print-ready HTML reports
 * from live KPI data with template-specific sections.
 *
 * POST body: { template: "ops_weekly"|"financial_monthly"|"board_quarterly", facility_id?: string }
 * Auth: JWT via Authorization header (owner/org_admin only).
 */
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import {
  computeKpiForFacilityIds,
  loadFacilitiesForOrganization,
  type ExecKpiPayload,
} from "../_shared/exec-kpi-metrics.ts";
import { getCorsHeaders, jsonResponse } from "../_shared/cors.ts";
import { withTiming } from "../_shared/structured-log.ts";
import { isRateLimited } from "../_shared/rate-limit.ts";

type Template = "ops_weekly" | "financial_monthly" | "board_quarterly" | "custom";
type FacilityKpi = { name: string; id: string; kpi: ExecKpiPayload };

const TEMPLATES: Record<Template, string> = {
  ops_weekly: "Weekly Operations Summary",
  financial_monthly: "Monthly Financial Review",
  board_quarterly: "Quarterly Board Report",
  custom: "Custom Report",
};

// ── HTML Builder Helpers ──

const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");

function kpiCard(label: string, value: string, color = "#0f172a"): string {
  return `<div class="kpi-card"><div class="kpi-label">${esc(label)}</div><div class="kpi-value" style="color:${color}">${esc(value)}</div></div>`;
}

function facilityRow(f: FacilityKpi): string {
  const k = f.kpi;
  const occ = k.census.occupancyPct != null ? `${k.census.occupancyPct}%` : "N/A";
  const ar = `$${(k.financial.totalBalanceDueCents / 100).toLocaleString()}`;
  return `<tr>
    <td><strong>${esc(f.name)}</strong></td>
    <td>${occ}</td>
    <td>${k.clinical.openIncidents}</td>
    <td>${k.clinical.medicationErrorsMtd}</td>
    <td>${ar}</td>
    <td>${k.compliance.openSurveyDeficiencies}</td>
    <td>${k.workforce.certificationsExpiring30d}</td>
    <td>${k.infection.activeOutbreaks}</td>
  </tr>`;
}

function buildHtml(title: string, date: string, sections: string): string {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${esc(title)}</title>
<style>
body{font-family:'Inter',-apple-system,sans-serif;color:#1e293b;max-width:850px;margin:0 auto;padding:40px;font-size:13px;line-height:1.6}
.header{border-bottom:3px solid #6366f1;padding-bottom:16px;margin-bottom:24px}
.header h1{font-size:22px;font-weight:700;color:#0f172a;margin:0}
.header .meta{font-size:11px;color:#64748b;margin-top:4px}
.kpi-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:20px 0}
.kpi-card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px}
.kpi-label{font-size:9px;text-transform:uppercase;letter-spacing:1.2px;color:#64748b;font-weight:700}
.kpi-value{font-size:24px;font-weight:700;margin-top:2px}
h2{font-size:16px;font-weight:700;color:#0f172a;margin:28px 0 12px;border-bottom:1px solid #e2e8f0;padding-bottom:6px}
table{width:100%;border-collapse:collapse;margin:12px 0}
th{text-align:left;font-size:9px;text-transform:uppercase;letter-spacing:1px;color:#64748b;padding:8px;border-bottom:2px solid #e2e8f0}
td{padding:8px;border-bottom:1px solid #f1f5f9;font-size:12px}
.alert-row{padding:10px 12px;border-left:3px solid;margin-bottom:6px;background:#f8fafc;border-radius:0 6px 6px 0;font-size:12px}
.critical{border-color:#ef4444}.warning{border-color:#f59e0b}.info{border-color:#3b82f6}
.footer{margin-top:32px;padding-top:12px;border-top:1px solid #e2e8f0;font-size:10px;color:#94a3b8;text-align:center}
@media print{body{padding:20px}@page{margin:1cm}}
</style></head><body>
<div class="header"><h1>${esc(title)}</h1><div class="meta">Haven Executive Intelligence &middot; Generated ${esc(date)}</div></div>
${sections}
<div class="footer">Haven &mdash; Circle of Life &middot; Confidential &middot; Generated by Executive Intelligence</div>
</body></html>`;
}

// ── Template Renderers ──

function renderOpsWeekly(portfolio: ExecKpiPayload, facilities: FacilityKpi[], alerts: Array<{ severity: string; title: string; body: string | null }>): string {
  const p = portfolio;
  let html = `<div class="kpi-grid">
    ${kpiCard("Occupancy", p.census.occupancyPct != null ? `${p.census.occupancyPct}%` : "N/A", "#10b981")}
    ${kpiCard("Open Incidents", `${p.clinical.openIncidents}`, p.clinical.openIncidents > 0 ? "#ef4444" : "#10b981")}
    ${kpiCard("Med Errors MTD", `${p.clinical.medicationErrorsMtd}`, p.clinical.medicationErrorsMtd > 2 ? "#ef4444" : "#10b981")}
    ${kpiCard("Outbreaks", `${p.infection.activeOutbreaks}`, p.infection.activeOutbreaks > 0 ? "#ef4444" : "#10b981")}
    ${kpiCard("Deficiencies", `${p.compliance.openSurveyDeficiencies}`)}
    ${kpiCard("Certs Expiring", `${p.workforce.certificationsExpiring30d}`)}
  </div>`;
  html += `<h2>Facility Breakdown</h2><table><thead><tr><th>Facility</th><th>Occ %</th><th>Incidents</th><th>Med Errors</th><th>AR</th><th>Deficiencies</th><th>Certs Exp</th><th>Outbreaks</th></tr></thead><tbody>`;
  for (const f of facilities) html += facilityRow(f);
  html += `</tbody></table>`;
  if (alerts.length > 0) {
    html += `<h2>Active Alerts (Top ${alerts.length})</h2>`;
    for (const a of alerts) html += `<div class="alert-row ${a.severity}"><strong>${esc(a.title)}</strong>${a.body ? `<br/>${esc(a.body)}` : ""}</div>`;
  }
  return html;
}

function renderFinancialMonthly(portfolio: ExecKpiPayload, facilities: FacilityKpi[]): string {
  const p = portfolio;
  const ar = `$${(p.financial.totalBalanceDueCents / 100).toLocaleString()}`;
  let html = `<div class="kpi-grid">
    ${kpiCard("Open Invoices", `${p.financial.openInvoicesCount}`, "#6366f1")}
    ${kpiCard("Total AR Outstanding", ar, "#f59e0b")}
    ${kpiCard("Occupancy", p.census.occupancyPct != null ? `${p.census.occupancyPct}%` : "N/A", "#10b981")}
    ${kpiCard("Certs Expiring 30d", `${p.workforce.certificationsExpiring30d}`)}
  </div>`;
  html += `<h2>Facility Financial Summary</h2><table><thead><tr><th>Facility</th><th>Occ %</th><th>Incidents</th><th>Med Errors</th><th>AR</th><th>Deficiencies</th><th>Certs Exp</th><th>Outbreaks</th></tr></thead><tbody>`;
  for (const f of facilities) html += facilityRow(f);
  html += `</tbody></table>`;
  return html;
}

function renderBoardQuarterly(portfolio: ExecKpiPayload, facilities: FacilityKpi[], alerts: Array<{ severity: string; title: string; body: string | null }>): string {
  const p = portfolio;
  const ar = `$${(p.financial.totalBalanceDueCents / 100).toLocaleString()}`;
  let html = `<h2>Executive Summary</h2><div class="kpi-grid">
    ${kpiCard("Portfolio Occupancy", p.census.occupancyPct != null ? `${p.census.occupancyPct}%` : "N/A", "#10b981")}
    ${kpiCard("Licensed Beds", `${p.census.licensedBeds}`)}
    ${kpiCard("Occupied", `${p.census.occupiedResidents}`)}
    ${kpiCard("Total AR", ar, "#f59e0b")}
    ${kpiCard("Open Incidents", `${p.clinical.openIncidents}`, "#ef4444")}
    ${kpiCard("Active Outbreaks", `${p.infection.activeOutbreaks}`, p.infection.activeOutbreaks > 0 ? "#ef4444" : "#10b981")}
    ${kpiCard("Survey Deficiencies", `${p.compliance.openSurveyDeficiencies}`)}
    ${kpiCard("Certs Expiring 30d", `${p.workforce.certificationsExpiring30d}`)}
  </div>`;
  html += `<h2>Facility Scorecard</h2><table><thead><tr><th>Facility</th><th>Occ %</th><th>Incidents</th><th>Med Errors</th><th>AR</th><th>Deficiencies</th><th>Certs Exp</th><th>Outbreaks</th></tr></thead><tbody>`;
  for (const f of facilities) html += facilityRow(f);
  html += `</tbody></table>`;
  if (alerts.length > 0) {
    html += `<h2>Escalation Items</h2>`;
    for (const a of alerts) html += `<div class="alert-row ${a.severity}"><strong>${esc(a.title)}</strong>${a.body ? `<br/>${esc(a.body)}` : ""}</div>`;
  }
  html += `<h2>Strategic Highlights</h2><p style="color:#64748b;font-style:italic">This section is populated by the executive team during board preparation. Use the Haven Scenario Modeling tool for projections.</p>`;
  return html;
}

// ── Main Handler ──

Deno.serve(async (req) => {
  const t = withTiming("exec-report-generator");
  const origin = req.headers.get("origin");

  if (req.method === "OPTIONS") return new Response("ok", { headers: getCorsHeaders(origin) });
  if (req.method !== "POST") return jsonResponse({ error: "Method not allowed" }, 405, origin);

  const url = Deno.env.get("SUPABASE_URL")!;
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const admin = createClient(url, serviceKey);

  // Auth
  const token = (req.headers.get("authorization") ?? "").replace("Bearer ", "");
  const { data: { user }, error: authErr } = await admin.auth.getUser(token);
  if (authErr || !user) return jsonResponse({ error: "Unauthorized" }, 401, origin);
  if (isRateLimited(user.id)) return jsonResponse({ error: "Rate limit exceeded." }, 429, origin);

  const { data: profile } = await admin.from("user_profiles").select("organization_id, app_role").eq("id", user.id).maybeSingle();
  if (!profile?.organization_id) return jsonResponse({ error: "Organization not found" }, 403, origin);
  if (!["owner", "org_admin"].includes(profile.app_role)) return jsonResponse({ error: "Insufficient role" }, 403, origin);

  const orgId = profile.organization_id;

  // Parse body
  let body: { template?: string; facility_id?: string };
  try { body = await req.json(); } catch { return jsonResponse({ error: "Invalid JSON" }, 400, origin); }

  const template = (body.template ?? "ops_weekly") as Template;
  if (!TEMPLATES[template]) return jsonResponse({ error: "Invalid template" }, 400, origin);

  // Load data
  const allFacilities = await loadFacilitiesForOrganization(admin, orgId);
  const portfolioKpi = await computeKpiForFacilityIds(admin, orgId, allFacilities);

  const facilityKpis: FacilityKpi[] = [];
  for (const fac of allFacilities) {
    const kpi = await computeKpiForFacilityIds(admin, orgId, [fac]);
    facilityKpis.push({ name: fac.name ?? fac.id.slice(0, 8), id: fac.id, kpi });
  }

  // Load alerts
  const { data: alertRows } = await admin.from("exec_alerts").select("severity, title, body")
    .eq("organization_id", orgId).is("deleted_at", null).is("resolved_at", null)
    .order("severity", { ascending: false }).limit(10);
  const alerts = (alertRows ?? []) as Array<{ severity: string; title: string; body: string | null }>;

  // Render template
  const date = new Date().toLocaleString("en-US", { dateStyle: "long", timeStyle: "short" });
  let sections: string;

  switch (template) {
    case "ops_weekly": sections = renderOpsWeekly(portfolioKpi, facilityKpis, alerts); break;
    case "financial_monthly": sections = renderFinancialMonthly(portfolioKpi, facilityKpis); break;
    case "board_quarterly": sections = renderBoardQuarterly(portfolioKpi, facilityKpis, alerts); break;
    default: sections = renderOpsWeekly(portfolioKpi, facilityKpis, alerts);
  }

  const html = buildHtml(TEMPLATES[template], date, sections);

  t.log({ event: "complete", outcome: "success", template, facilities: allFacilities.length });

  return new Response(JSON.stringify({ ok: true, html, generated_at: new Date().toISOString() }), {
    status: 200,
    headers: {
      ...getCorsHeaders(origin),
      "Content-Type": "application/json",
      "X-Content-Type-Options": "nosniff",
      "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'",
    },
  });
});
