-- COL-357: synthetic rollback-only payroll packet security/lifecycle probe.
BEGIN;
GRANT USAGE ON SCHEMA auth TO authenticated;
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(auth.jwt()->>'sub','')::uuid $$;
CREATE TEMP TABLE pp_fixture AS SELECT gen_random_uuid() owner_id,gen_random_uuid() admin_id,gen_random_uuid() outsider_id,gen_random_uuid() worker_id,gen_random_uuid() staff_id,gen_random_uuid() other_facility,gen_random_uuid() admin_session,gen_random_uuid() outsider_session,f.id facility_id,f.organization_id,f.entity_id FROM public.facilities f WHERE f.deleted_at IS NULL ORDER BY f.id LIMIT 1;
INSERT INTO auth.users(id,email) SELECT owner_id,owner_id||'@packets.invalid' FROM pp_fixture UNION ALL SELECT admin_id,admin_id||'@packets.invalid' FROM pp_fixture UNION ALL SELECT outsider_id,outsider_id||'@packets.invalid' FROM pp_fixture UNION ALL SELECT worker_id,worker_id||'@packets.invalid' FROM pp_fixture;
INSERT INTO public.user_profiles(id,organization_id,email,full_name,app_role) SELECT owner_id,organization_id,owner_id||'@packets.invalid','Packet Owner','owner'::public.app_role FROM pp_fixture UNION ALL SELECT admin_id,organization_id,admin_id||'@packets.invalid','Packet Admin','facility_admin'::public.app_role FROM pp_fixture UNION ALL SELECT outsider_id,organization_id,outsider_id||'@packets.invalid','Packet Outsider','facility_admin'::public.app_role FROM pp_fixture UNION ALL SELECT worker_id,organization_id,worker_id||'@packets.invalid','Packet Worker','med_tech'::public.app_role FROM pp_fixture;
INSERT INTO auth.sessions(id,user_id) SELECT admin_session,admin_id FROM pp_fixture UNION ALL SELECT outsider_session,outsider_id FROM pp_fixture;
INSERT INTO public.facilities(id,entity_id,organization_id,name,address_line_1,city,zip,total_licensed_beds) SELECT other_facility,entity_id,organization_id,'Packet scope probe','Test','Test','00000',1 FROM pp_fixture;
INSERT INTO public.user_facility_access(user_id,facility_id,organization_id) SELECT admin_id,facility_id,organization_id FROM pp_fixture UNION ALL SELECT outsider_id,other_facility,organization_id FROM pp_fixture;
INSERT INTO public.staff(id,organization_id,facility_id,first_name,last_name,staff_role,hire_date) SELECT staff_id,organization_id,facility_id,'Packet','Worker','resident_aide',date '2026-01-01' FROM pp_fixture;
INSERT INTO public.timeclock_credentials(organization_id,staff_id,employee_number,pin_hash,pin_set_by) SELECT organization_id,staff_id,'PACKET-TEST','synthetic-test-hash',owner_id FROM pp_fixture;
DO $$ DECLARE before_rev text; after_rev text; f record; BEGIN
 SELECT * INTO f FROM pp_fixture;
 before_rev:=public.payroll_packet_revision(f.owner_id,f.facility_id);
 UPDATE public.timeclock_credentials SET failed_attempts=failed_attempts+1 WHERE staff_id=f.staff_id;
 after_rev:=public.payroll_packet_revision(f.owner_id,f.facility_id);
 IF before_rev<>after_rev THEN RAISE EXCEPTION 'credential authentication metadata should not stale payroll'; END IF;
 UPDATE public.timeclock_credentials SET employee_number='PACKET-NEW' WHERE staff_id=f.staff_id;
 IF after_rev=public.payroll_packet_revision(f.owner_id,f.facility_id) THEN RAISE EXCEPTION 'payroll employee number must stale payroll'; END IF;
END $$;
CREATE FUNCTION pg_temp.pp_fail(q text,expected text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN BEGIN EXECUTE q; EXCEPTION WHEN OTHERS THEN IF position(expected IN SQLERRM)>0 THEN RETURN; END IF; RAISE; END; RAISE EXCEPTION 'Expected error %',expected; END $$;
CREATE FUNCTION pg_temp.pp_assert(v boolean,n text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF NOT coalesce(v,false) THEN RAISE EXCEPTION 'Assertion failed: %',n; END IF; END $$;
CREATE FUNCTION pg_temp.pp_auth(actor uuid,session uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN
 PERFORM set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',p.id,'session_id',session,'organization_id',p.organization_id,'app_role',p.app_role,'auth_claim_version',p.auth_claim_version,'iat',extract(epoch FROM clock_timestamp())::bigint)::text,true) FROM public.user_profiles p WHERE p.id=actor;
END $$;
CREATE TEMP TABLE pp_values(k text PRIMARY KEY,v jsonb);
GRANT ALL ON pp_values TO service_role,authenticated,anon;
GRANT SELECT ON pp_fixture TO service_role,authenticated,anon;
DO $$ DECLARE t text;r text;BEGIN
 FOREACH r IN ARRAY ARRAY['anon','authenticated','service_role'] LOOP
  FOREACH t IN ARRAY ARRAY['payroll_packets','payroll_packet_policies','payroll_packet_events'] LOOP
   IF has_table_privilege(r,'public.'||t,'INSERT,UPDATE,DELETE,TRUNCATE') THEN RAISE EXCEPTION 'Direct write grant % %',r,t; END IF;
  END LOOP;
 END LOOP;
 PERFORM pg_temp.pp_assert(NOT has_function_privilege('authenticated','public.payroll_packet_action(uuid,uuid,integer,text,jsonb)','EXECUTE'),'authenticated RPC denied');
 PERFORM pg_temp.pp_assert(NOT has_function_privilege('anon','public.payroll_packet_source_page(uuid,uuid,text,integer,integer)','EXECUTE'),'anonymous source denied');
END $$;
SET LOCAL ROLE anon;
SELECT pg_temp.pp_fail('INSERT INTO public.payroll_packet_events DEFAULT VALUES','permission denied');
RESET ROLE;
SET LOCAL ROLE authenticated;
SELECT pg_temp.pp_fail('DELETE FROM public.payroll_packets','permission denied');
RESET ROLE;
SET LOCAL ROLE service_role;
SELECT pg_temp.pp_fail('UPDATE public.payroll_packet_policies SET revision=9','permission denied');
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_revision(%L,%L)',outsider_id,facility_id),'payroll_access_denied') FROM pp_fixture;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_revision(%L,%L)',worker_id,facility_id),'payroll_access_denied') FROM pp_fixture;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_policy_save(%L,%L,%L,true,0)',admin_id,facility_id,'{}'),'payroll_access_denied') FROM pp_fixture;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_policy_save(%L,%L,%L,true,0)',owner_id,facility_id,'{}'),'payroll_policy_incomplete') FROM pp_fixture;
INSERT INTO pp_values SELECT 'config',jsonb_build_object('employerName','Synthetic Employer','payFrequency','weekly','anchorDate','2026-09-21','workweekDay',1,'workweekTime','00:00','timeZone','America/New_York','overtimeThresholdMinutes',2400,'overtimeFacilityIds',jsonb_build_array(facility_id::text),'calculationMode','reviewed','mealPolicy','punched_unpaid','roundingMinutes',0,'salaryTreatment','unchanged','approvalRole','central','defaultMethod','phone','policyNote','Synthetic explicit review') FROM pp_fixture;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_policy_save(%L,%L,%L,true,0)',owner_id,facility_id,((SELECT v FROM pp_values WHERE k='config')||'{"workweekDay":null}'::jsonb)::text),'payroll_policy_incomplete') FROM pp_fixture;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_policy_save(%L,%L,%L,true,0)',owner_id,facility_id,((SELECT v FROM pp_values WHERE k='config')||jsonb_build_object('overtimeFacilityIds',jsonb_build_array(gen_random_uuid()::text)))::text),'payroll_policy_invalid') FROM pp_fixture;
INSERT INTO pp_values SELECT 'policy',public.payroll_packet_policy_save(owner_id,facility_id,(SELECT v FROM pp_values WHERE k='config'),true,0) FROM pp_fixture;
SELECT pg_temp.pp_assert((SELECT v->>'confirmed_at' FROM pp_values WHERE k='policy') IS NOT NULL,'policy confirmed');
INSERT INTO pp_values SELECT 'input',jsonb_build_object('staffId',staff_id,'payrollId','TEST1','payBasis','hourly','department','operations','regularMinutes',2400,'overtimeMinutes',0,'holidayMinutes',0,'personalMinutes',0,'trainingMinutes',0,'onCallCents',0,'bonusCents',0,'salaryCents',NULL,'note','','reason','reviewed source','reviewed',true) FROM pp_fixture;
INSERT INTO pp_values SELECT 'snapshot',jsonb_build_object('schemaVersion',1,'facilityId',facility_id,'facilityName','Synthetic facility','employerName','Synthetic Employer','periodStart','2026-09-21','periodEnd','2026-09-27','checkDate','2026-09-30','generatedAt',now(),'sourceRevision',public.payroll_packet_revision(owner_id,facility_id),'policy',(SELECT v FROM pp_values WHERE k='config'),'policyConfirmedAt',(SELECT v->'confirmed_at' FROM pp_values WHERE k='policy'),'rows',jsonb_build_array((SELECT v FROM pp_values WHERE k='input')||'{"name":"Packet Worker","role":"resident_aide","workedMinutes":2400,"mealMinutes":0,"paidWorkMinutes":2400,"paidMinutes":2400,"issues":[],"sourcePunchIds":[],"sourceCorrectionIds":[]}'::jsonb),'totals','{"regularMinutes":2400}'::jsonb,'blockers','[]'::jsonb,'warnings','[]'::jsonb) FROM pp_fixture;
INSERT INTO pp_values SELECT 'packet',public.payroll_packet_write(owner_id,facility_id,NULL,0,public.payroll_packet_revision(owner_id,facility_id),1,'2026-09-21','2026-09-27','2026-09-30',jsonb_build_array((SELECT v FROM pp_values WHERE k='input')),(SELECT v FROM pp_values WHERE k='snapshot')) FROM pp_fixture;
RESET ROLE;
SELECT pg_temp.pp_auth(admin_id,admin_session) FROM pp_fixture;
SET LOCAL ROLE authenticated;
SELECT pg_temp.pp_assert((SELECT count(*)=1 FROM public.payroll_packets WHERE id=(SELECT (v->>'id')::uuid FROM pp_values WHERE k='packet')),'assigned facility can read');
RESET ROLE;
SELECT pg_temp.pp_auth(outsider_id,outsider_session) FROM pp_fixture;
SET LOCAL ROLE authenticated;
SELECT pg_temp.pp_assert((SELECT count(*)=0 FROM public.payroll_packets WHERE id=(SELECT (v->>'id')::uuid FROM pp_values WHERE k='packet')),'RLS hides other facility');
RESET ROLE;
SELECT set_config('request.jwt.claims','{}',true);
SET LOCAL ROLE service_role;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_action(%L,%L,99,%L,%L)',owner_id,(SELECT v->>'id' FROM pp_values WHERE k='packet'),'approve','{}'),'payroll_revision_conflict') FROM pp_fixture;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_action(%L,%L,1,%L,%L)',admin_id,(SELECT v->>'id' FROM pp_values WHERE k='packet'),'approve','{}'),'payroll_approval_denied') FROM pp_fixture;
SELECT pg_temp.pp_assert((public.payroll_packet_source_page(owner_id,facility_id,'people',0,500)->>'count')::int>0,'paginated people') FROM pp_fixture;
SELECT pg_temp.pp_assert(NOT (public.payroll_packet_source_page(owner_id,facility_id,'people',0,500)::text ~ 'pin_hash|pinHash|badge_lookup'),'no source credentials') FROM pp_fixture;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_source_page(%L,%L,%L,0,501)',owner_id,facility_id,'people'),'payroll_page_invalid') FROM pp_fixture;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_source_page(%L,%L,%L,0,1)',owner_id,facility_id,'credentials'),'payroll_source_kind_invalid') FROM pp_fixture;
RESET ROLE;
-- A source write stales the saved packet before approval. Source rows remain editable through their existing writers.
UPDATE public.staff SET first_name='Updated Packet' WHERE id=(SELECT staff_id FROM pp_fixture);
SET LOCAL ROLE service_role;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_action(%L,%L,1,%L,%L)',owner_id,(SELECT v->>'id' FROM pp_values WHERE k='packet'),'approve','{}'),'payroll_source_stale') FROM pp_fixture;
UPDATE pp_values SET v=jsonb_set(v,'{sourceRevision}',to_jsonb(public.payroll_packet_revision((SELECT owner_id FROM pp_fixture),(SELECT facility_id FROM pp_fixture)))) WHERE k='snapshot';
UPDATE pp_values SET v=jsonb_set(v,'{checkDate}','"2026-10-01"'::jsonb) WHERE k='snapshot';
UPDATE pp_values SET v=public.payroll_packet_write((SELECT owner_id FROM pp_fixture),(SELECT facility_id FROM pp_fixture),(v->>'id')::uuid,1,public.payroll_packet_revision((SELECT owner_id FROM pp_fixture),(SELECT facility_id FROM pp_fixture)),1,'2026-09-21','2026-09-27','2026-10-01',jsonb_build_array((SELECT v FROM pp_values WHERE k='input')),(SELECT v FROM pp_values WHERE k='snapshot')) WHERE k='packet';
SELECT pg_temp.pp_assert((SELECT v->>'check_date'='2026-10-01' AND v->'snapshot'->>'checkDate'='2026-10-01' FROM pp_values WHERE k='packet'),'draft check date correction persisted');
RESET ROLE;
INSERT INTO pp_values VALUES('document',jsonb_build_object('approvedAt',clock_timestamp(),'approvedByName','Packet Owner','pdfBase64',encode(convert_to('%PDF-1.4 synthetic test document only','UTF8'),'base64'),'html',repeat('Synthetic document ',20),'csv','Name,Hours'||chr(10)||'Synthetic,40','documentHash',encode(extensions.digest(convert_to('%PDF-1.4 synthetic test document only','UTF8'),'sha256'),'hex')));
SET LOCAL ROLE service_role;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_action(%L,%L,2,%L,%L)',owner_id,(SELECT v->>'id' FROM pp_values WHERE k='packet'),'approve',((SELECT v FROM pp_values WHERE k='document')||jsonb_build_object('documentHash',repeat('a',64)))::text),'payroll_document_invalid') FROM pp_fixture;
UPDATE pp_values SET v=public.payroll_packet_action((SELECT owner_id FROM pp_fixture),(v->>'id')::uuid,2,'approve',(SELECT v FROM pp_values WHERE k='document')) WHERE k='packet';
SELECT pg_temp.pp_assert((SELECT v->>'status'='approved' AND NOT(v ? 'approved_pdf_base64') FROM pp_values WHERE k='packet'),'approved metadata only');
RESET ROLE;
SELECT pg_temp.pp_fail(format('UPDATE public.payroll_packets SET snapshot=%L WHERE id=%L','{}',(SELECT v->>'id' FROM pp_values WHERE k='packet')),'payroll_document_immutable');
SELECT pg_temp.pp_fail(format('UPDATE public.payroll_packets SET check_date=%L WHERE id=%L','2026-10-02',(SELECT v->>'id' FROM pp_values WHERE k='packet')),'payroll_document_immutable');
SELECT pg_temp.pp_fail(format('DELETE FROM public.payroll_packets WHERE id=%L',(SELECT v->>'id' FROM pp_values WHERE k='packet')),'payroll_history_immutable');
SELECT pg_temp.pp_fail('UPDATE public.payroll_packet_events SET detail=''{}''','append only');
SET LOCAL ROLE service_role;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_action(%L,%L,3,%L,%L)',owner_id,(SELECT v->>'id' FROM pp_values WHERE k='packet'),'report','{"method":"phone","reference":""}'),'payroll_report_invalid') FROM pp_fixture;
UPDATE pp_values SET v=public.payroll_packet_action((SELECT owner_id FROM pp_fixture),(v->>'id')::uuid,3,'report','{"method":"phone","reference":"Synthetic call reference","reportedByName":"Untrusted name"}') WHERE k='packet';
UPDATE pp_values SET v=public.payroll_packet_action((SELECT owner_id FROM pp_fixture),(v->>'id')::uuid,4,'difference','{"note":"One entry differs"}') WHERE k='packet';
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_action(%L,%L,5,%L,%L)',owner_id,(SELECT v->>'id' FROM pp_values WHERE k='packet'),'reconcile','{"matches":false,"note":"Mismatch"}'),'payroll_reconciliation_mismatch') FROM pp_fixture;
UPDATE pp_values SET v=public.payroll_packet_action((SELECT owner_id FROM pp_fixture),(v->>'id')::uuid,5,'reconcile','{"matches":true,"note":"ADP preview matches packet","reconciledByName":"Untrusted name"}') WHERE k='packet';
INSERT INTO pp_values SELECT 'amendment',public.payroll_packet_write(owner_id,facility_id,NULL,0,public.payroll_packet_revision(owner_id,facility_id),1,'2026-09-21','2026-09-27','2026-10-01',jsonb_build_array((SELECT v FROM pp_values WHERE k='input')),(SELECT v FROM pp_values WHERE k='snapshot'),(SELECT (v->>'id')::uuid FROM pp_values WHERE k='packet'),'Synthetic approved correction') FROM pp_fixture;
SELECT pg_temp.pp_assert((SELECT v->>'version'='2' FROM pp_values WHERE k='amendment'),'amendment version');
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_write(%L,%L,NULL,0,%L,1,%L,%L,%L,%L,%L,%L,%L)',owner_id,facility_id,public.payroll_packet_revision(owner_id,facility_id),'2026-09-21','2026-09-27','2026-10-01',jsonb_build_array((SELECT v FROM pp_values WHERE k='input'))::text,(SELECT v::text FROM pp_values WHERE k='snapshot'),(SELECT v->>'id' FROM pp_values WHERE k='packet'),'Duplicate amendment'),'payroll_amendment_superseded') FROM pp_fixture;
UPDATE pp_values SET v=public.payroll_packet_action((SELECT owner_id FROM pp_fixture),(v->>'id')::uuid,1,'approve',(SELECT v FROM pp_values WHERE k='document')) WHERE k='amendment';
INSERT INTO pp_values SELECT 'third',public.payroll_packet_write(owner_id,facility_id,NULL,0,public.payroll_packet_revision(owner_id,facility_id),1,'2026-09-21','2026-09-27','2026-10-01',jsonb_build_array((SELECT v FROM pp_values WHERE k='input')),(SELECT v FROM pp_values WHERE k='snapshot'),(SELECT (v->>'id')::uuid FROM pp_values WHERE k='amendment'),'Next correction') FROM pp_fixture;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_action(%L,%L,2,%L,%L)',owner_id,(SELECT v->>'id' FROM pp_values WHERE k='amendment'),'report','{"method":"run","reference":"obsolete"}'),'payroll_report_blocked') FROM pp_fixture;
-- Editing policy without explicit reconfirmation clears the confirmation but retains the editor.
RESET ROLE;
UPDATE public.user_profiles SET full_name='Policy Editor' WHERE id=(SELECT owner_id FROM pp_fixture);
SET LOCAL ROLE service_role;
SELECT pg_temp.pp_assert(public.payroll_packet_policy_save(owner_id,facility_id,(SELECT v FROM pp_values WHERE k='config'),false,1)->>'confirmed_at' IS NULL,'policy edit clears confirmation') FROM pp_fixture;
RESET ROLE;
UPDATE public.staff SET facility_id=(SELECT other_facility FROM pp_fixture),deleted_at=now() WHERE id=(SELECT staff_id FROM pp_fixture);
SET LOCAL ROLE service_role;
SELECT pg_temp.pp_assert(EXISTS(SELECT 1 FROM jsonb_array_elements(public.payroll_packet_source_page(owner_id,facility_id,'people',0,500)->'data') p WHERE p->>'id'=staff_id::text),'historical packet employee retained after roster transfer/deletion') FROM pp_fixture;
RESET ROLE;
UPDATE public.user_facility_access SET revoked_at=now() WHERE user_id=(SELECT admin_id FROM pp_fixture);
SET LOCAL ROLE service_role;
SELECT pg_temp.pp_fail(format('SELECT public.payroll_packet_revision(%L,%L)',admin_id,facility_id),'payroll_access_denied') FROM pp_fixture;
RESET ROLE;
SELECT pg_temp.pp_assert((SELECT approved_pdf_base64=(SELECT v->>'pdfBase64' FROM pp_values WHERE k='document') AND approved_csv=(SELECT v->>'csv' FROM pp_values WHERE k='document') AND approved_html=(SELECT v->>'html' FROM pp_values WHERE k='document') AND status='reconciled' FROM public.payroll_packets WHERE id=(SELECT (v->>'id')::uuid FROM pp_values WHERE k='packet')),'original packet unchanged after amendments');
UPDATE public.user_profiles SET full_name='Renamed later' WHERE id=(SELECT owner_id FROM pp_fixture);
SELECT pg_temp.pp_assert((SELECT updated_by=(SELECT owner_id FROM pp_fixture) AND updated_by_name='Policy Editor' AND confirmed_by IS NULL AND confirmed_at IS NULL FROM public.payroll_packet_policies WHERE facility_id=(SELECT facility_id FROM pp_fixture)),'unconfirmed policy retains editor snapshot after rename');
SELECT pg_temp.pp_assert(EXISTS(SELECT 1 FROM public.audit_log WHERE table_name='payroll_packet_policies' AND record_id=(SELECT (v->>'id')::uuid FROM pp_values WHERE k='policy') AND action='UPDATE' AND user_id=(SELECT owner_id FROM pp_fixture) AND old_data->>'updated_by_name'='Packet Owner' AND new_data->>'updated_by_name'='Policy Editor' AND new_data->>'confirmed_at' IS NULL),'policy audit retains editor user id and old/new names');

SELECT pg_temp.pp_assert((SELECT created_by_name='Packet Owner' AND approved_by_name='Packet Owner' AND reported_by_name='Packet Owner' AND reconciled_by_name='Packet Owner' FROM public.payroll_packets WHERE id=(SELECT (v->>'id')::uuid FROM pp_values WHERE k='packet')),'action names are frozen from current actor, not supplied names');
SELECT pg_temp.pp_assert(NOT EXISTS(SELECT 1 FROM public.payroll_packet_events WHERE packet_id=(SELECT (v->>'id')::uuid FROM pp_values WHERE k='packet') AND actor_name<>'Packet Owner'),'event names survive profile rename');
SELECT pg_temp.pp_fail(format('UPDATE public.payroll_packets SET created_by_name=%L WHERE id=%L','Forged',(SELECT v->>'id' FROM pp_values WHERE k='packet')),'payroll_identity_immutable');
ROLLBACK;
