-- Rollback-only synthetic proof. No actual resident data or agency submission.
BEGIN;
CREATE TEMP TABLE bf AS SELECT gen_random_uuid() org,gen_random_uuid() entity,gen_random_uuid() site,gen_random_uuid() other_site,gen_random_uuid() resident,gen_random_uuid() other_resident,gen_random_uuid() request;
CREATE TEMP TABLE ba AS SELECT role,gen_random_uuid() id,gen_random_uuid() session FROM unnest(ARRAY['owner','manager','nurse','caregiver']) role;
CREATE TEMP TABLE br(label text PRIMARY KEY,reply jsonb);
GRANT ALL ON bf,ba,br TO authenticated,service_role;
INSERT INTO public.organizations(id,name) SELECT org,'COL504 synthetic' FROM bf;
INSERT INTO public.entities(id,organization_id,name) SELECT entity,org,'COL504 synthetic' FROM bf;
INSERT INTO public.facilities(id,organization_id,entity_id,name,address_line_1,city,zip,total_licensed_beds,timezone) SELECT site,org,entity,'COL504 synthetic','Test','Test','00000',2,'America/New_York' FROM bf UNION ALL SELECT other_site,org,entity,'COL504 other','Test','Test','00000',2,'America/New_York' FROM bf;
INSERT INTO auth.users(id,email,raw_app_meta_data,raw_user_meta_data) SELECT id,id||'@col504.invalid',jsonb_build_object('organization_id',org,'app_role',role),'{}'::jsonb FROM ba,bf;
INSERT INTO public.user_profiles(id,organization_id,full_name,email,app_role,is_active) SELECT id,org,'COL504 '||role,id||'@col504.invalid',role::public.app_role,true FROM ba,bf ON CONFLICT(id) DO UPDATE SET organization_id=excluded.organization_id,app_role=excluded.app_role,is_active=true;
INSERT INTO auth.sessions(id,user_id) SELECT session,id FROM ba;
INSERT INTO public.user_facility_access(user_id,facility_id,organization_id) SELECT id,site,org FROM ba,bf;
INSERT INTO public.staff(user_id,facility_id,organization_id,first_name,last_name,staff_role,employment_status,hire_date) SELECT id,site,org,'COL504',role,'cna','active',current_date FROM ba,bf WHERE role<>'owner';
INSERT INTO public.residents(id,organization_id,facility_id,first_name,last_name,date_of_birth,gender) SELECT resident,org,site,'COL504','Synthetic',DATE '1940-01-01','female'::public.gender FROM bf UNION ALL SELECT other_resident,org,other_site,'Other','Synthetic',DATE '1940-01-01','female'::public.gender FROM bf;
CREATE FUNCTION pg_temp.blogin(p_role text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$ DECLARE a record; BEGIN SELECT ba.*,p.auth_claim_version INTO a FROM ba JOIN public.user_profiles p USING(id) WHERE ba.role=p_role; PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',a.id,'session_id',a.session,'role','authenticated','auth_claim_version',a.auth_claim_version,'iat',extract(epoch FROM clock_timestamp())::bigint)::text,true); END $$;
CREATE FUNCTION pg_temp.bassert(ok boolean,msg text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF ok IS NOT TRUE THEN RAISE EXCEPTION 'COL504 %',msg; END IF; END $$;
CREATE FUNCTION pg_temp.berror(stmt text,expected text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN BEGIN EXECUTE stmt; EXCEPTION WHEN OTHERS THEN IF SQLSTATE=expected THEN RETURN; END IF; RAISE; END; RAISE EXCEPTION 'Expected denial %: %',expected,stmt; END $$;
CREATE FUNCTION pg_temp.bcommand(action text,payload jsonb) RETURNS jsonb LANGUAGE sql AS $$ SELECT public.benefits_case_command((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,action,payload,(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)#>>'{case,revision}')::integer,gen_random_uuid()); $$;
SELECT pg_temp.bassert(NOT has_table_privilege('authenticated','public.benefits_documents','SELECT,INSERT,UPDATE,DELETE'),'direct document grants');
SELECT pg_temp.bassert(NOT has_function_privilege('anon','public.benefits_case_list(jsonb)','EXECUTE'),'anonymous RPC');
SELECT pg_temp.bassert(NOT has_function_privilege('authenticated','public.benefits_document_attest(uuid,text,bigint,text,uuid,text,text)','EXECUTE'),'staff byte attestation');
SELECT pg_temp.bassert(NOT has_function_privilege('service_role','public.benefits_case_command(uuid,text,jsonb,integer,uuid)','EXECUTE'),'service staff impersonation');
SELECT pg_temp.blogin('caregiver'); SET LOCAL ROLE authenticated;
SELECT pg_temp.berror($q$SELECT public.benefits_case_list()$q$,'42501');
RESET ROLE; SELECT pg_temp.blogin('manager'); SET LOCAL ROLE authenticated;
SELECT pg_temp.berror($q$SELECT public.benefits_case_create(resident,NULL,'smmc_ltc',request) FROM bf$q$,'42501');
RESET ROLE; SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
INSERT INTO br SELECT 'grant',public.benefits_access_set(jsonb_build_object('facility_id',site,'user_id',(SELECT id FROM ba WHERE role='manager'),'can_write',true,'can_review',false,'expires_at',now()+interval '1 day','reason','Synthetic grant')) FROM bf;
INSERT INTO br SELECT 'case',public.benefits_case_create(resident,NULL,'smmc_ltc',request) FROM bf;
SELECT pg_temp.bassert((SELECT public.benefits_case_create(resident,NULL,'smmc_ltc',request)=(SELECT reply FROM br WHERE label='case') FROM bf),'create retry changed result');
SELECT pg_temp.berror($q$SELECT public.benefits_case_create(resident,NULL,'oss',request) FROM bf$q$,'23505');
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_options()->'residents')=2,'owner options');
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_case_list()->'cases')=1,'queue');
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_access_list()->'grants')=1,'access read');
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_options(NULL,(SELECT resident::text FROM bf))->'residents')=1,'exact resident link lookup');
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)->'requirements')=18,'source checklist not seeded');
INSERT INTO br SELECT 'retry_args',jsonb_build_object('request_id',gen_random_uuid(),'revision',1);
INSERT INTO br SELECT 'retry_result',public.benefits_case_command((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,'update_case','{"next_action":"Retry proof"}',1,(SELECT reply->>'request_id' FROM br WHERE label='retry_args')::uuid);
SELECT pg_temp.bassert(public.benefits_case_command((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,'update_case','{"next_action":"Retry proof"}',1,(SELECT reply->>'request_id' FROM br WHERE label='retry_args')::uuid)=(SELECT reply FROM br WHERE label='retry_result'),'payload-bound replay failed');
SELECT pg_temp.berror($q$SELECT public.benefits_case_command((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,'update_case','{"next_action":"Changed"}',1,(SELECT reply->>'request_id' FROM br WHERE label='retry_args')::uuid)$q$,'23505');

SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('update_case','{"status":"closed"}')$q$,'23514');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('update_case','{"screening":{"income_cents":-1}}')$q$,'22023');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('update_case','{"screening":{"married":"maybe"}}')$q$,'22023');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('record_event','{"agency":"dcf","event_type":"eligibility","outcome":"approved","occurred_on":"2026-09-21","formal_decision":true}')$q$,'22023');
SELECT pg_temp.bcommand('update_case','{"screening":{"income_cents":999999999,"income_basis":"unknown","married":"unknown"},"next_action":"Confirm financial facts"}');
SELECT pg_temp.bassert((public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)#>>'{case,status}')='open','screening automatically rejected case');
SELECT pg_temp.berror($q$SELECT public.benefits_case_command((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,'update_case','{}',1,gen_random_uuid())$q$,'P0409');
SELECT pg_temp.bassert((SELECT count(*) FROM jsonb_array_elements(public.benefits_access_list()->'users') u WHERE u->>'id'=(SELECT id::text FROM ba WHERE role='caregiver'))=0,'caregiver offered as a grant subject');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('update_case',jsonb_build_object('assigned_to',(SELECT id FROM ba WHERE role='nurse')))$q$,'22023');
SELECT pg_temp.bcommand('update_case',jsonb_build_object('assigned_to',(SELECT id FROM ba WHERE role='manager')));
SELECT pg_temp.bassert((SELECT count(*) FROM jsonb_array_elements(public.benefits_options()->'assignees') u WHERE u->>'id'=(SELECT id::text FROM ba WHERE role='nurse'))=0,'ungranted nurse offered as assignee');
INSERT INTO br SELECT 'upload',pg_temp.bcommand('prepare_document',jsonb_build_object('filename','evidence.pdf','mime_type','application/pdf','size_bytes',12,'sha256',repeat('a',64),'document_type','bank_statement'));
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('finalize_document',jsonb_build_object('document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')))$q$,'55000');
RESET ROLE;
GRANT USAGE ON SCHEMA storage TO authenticated;
GRANT SELECT,INSERT ON storage.objects TO authenticated;
CREATE POLICY benefits_synthetic_permissive ON storage.objects FOR ALL TO authenticated USING(true) WITH CHECK(true);
INSERT INTO storage.objects(bucket_id,name,version,metadata) SELECT 'benefits-documents',reply#>>'{document,storage_path}','v1',jsonb_build_object('size',12,'mimetype','application/pdf','eTag','etag1') FROM br WHERE label='upload';
CREATE TEMP TABLE bo AS SELECT o.id,o.version,o.metadata->>'eTag' etag FROM storage.objects o WHERE o.name=(SELECT reply#>>'{document,storage_path}' FROM br WHERE label='upload'); GRANT SELECT ON bo TO service_role;
SET LOCAL ROLE service_role;
SELECT pg_temp.berror($q$SELECT public.benefits_document_attest((SELECT reply#>>'{document,id}' FROM br WHERE label='upload')::uuid,repeat('b',64),12,'application/pdf',id,version,etag) FROM bo$q$,'55000');
SELECT public.benefits_document_attest((SELECT reply#>>'{document,id}' FROM br WHERE label='upload')::uuid,repeat('a',64),12,'application/pdf',id,version,etag) FROM bo;
RESET ROLE; SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert((SELECT count(*)=0 FROM storage.objects WHERE bucket_id='benefits-documents'),'blanket storage policy exposed financial evidence');
SELECT pg_temp.berror($q$INSERT INTO storage.objects(bucket_id,name) VALUES('benefits-documents','forged')$q$,'42501');
SELECT pg_temp.bcommand('finalize_document',jsonb_build_object('document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')));
INSERT INTO br SELECT 'requirement',pg_temp.bcommand('upsert_requirement',jsonb_build_object('title','Bank statement','stage','application','status','received','signature_status','not_required','document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')));
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('record_submission',jsonb_build_object('stage','application','destination','Synthetic agency','method','portal','sent_at',now(),'document_ids',jsonb_build_array((SELECT reply#>>'{document,id}' FROM br WHERE label='upload'))))$q$,'22023');
RESET ROLE; SELECT pg_temp.blogin('manager'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_case_list()->'cases')=1,'granted case invisible');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('upsert_requirement',(SELECT jsonb_build_object('id',value->>'id','title',value->>'title','stage',value->>'stage','status','missing','signature_status','not_required') FROM jsonb_array_elements(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)->'requirements') WHERE value->>'signature_status'='pending' LIMIT 1))$q$,'42501');
SELECT pg_temp.berror($q$SELECT public.benefits_case_command((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,'update_case','{"next_action":"Retry proof"}',1,(SELECT reply->>'request_id' FROM br WHERE label='retry_args')::uuid)$q$,'23505');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('upsert_requirement',jsonb_build_object('title','Signature','stage','application','status','received','signature_status','verified','document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')))$q$,'42501');
SELECT pg_temp.berror($q$SELECT public.benefits_case_create(other_resident,NULL,'smmc_ltc',gen_random_uuid()) FROM bf$q$,'42501');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('upsert_requirement',jsonb_build_object('title','Bank statement','stage','application','status','accepted','signature_status','not_required','document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')))$q$,'42501');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('record_event','{"agency":"dcf","event_type":"eligibility","outcome":"approved","occurred_on":"2026-09-21","formal_decision":true,"source_reference":"Synthetic call"}')$q$,'42501');
SELECT pg_temp.berror($q$SELECT * FROM public.benefits_cases$q$,'42501');
RESET ROLE; SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bcommand('upsert_requirement',jsonb_build_object('id',(SELECT reply->>'record_id' FROM br WHERE label='requirement'),'title','Bank statement','stage','application','status','accepted','signature_status','not_required','document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')));
-- Reviewed applicability applies independently to every source checklist item.
DO $$ DECLARE r jsonb; BEGIN
 FOR r IN SELECT value FROM jsonb_array_elements(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)->'requirements') WHERE value->>'stage'='application' AND value->>'status'<>'accepted' LOOP
  PERFORM pg_temp.bcommand('upsert_requirement',jsonb_build_object('id',r->>'id','title',r->>'title','stage',r->>'stage','status','not_applicable','signature_status','not_required','review_reason','Synthetic fixture applicability only'));
 END LOOP;
END $$;
INSERT INTO br SELECT 'submission',pg_temp.bcommand('record_submission',jsonb_build_object('stage','application','destination','Synthetic agency','method','portal','sent_at',now(),'document_ids',jsonb_build_array((SELECT reply#>>'{document,id}' FROM br WHERE label='upload'))));
SELECT pg_temp.bcommand('record_receipt',jsonb_build_object('submission_id',(SELECT reply->>'record_id' FROM br WHERE label='submission'),'received_at',now(),'source_reference','Synthetic portal receipt'));
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)->'receipts')=1,'receipt missing');
INSERT INTO br SELECT 'denial',pg_temp.bcommand('record_event','{"agency":"dcf","event_type":"eligibility","outcome":"denied","occurred_on":"2026-09-21","formal_decision":true,"source_reference":"Synthetic denial letter"}');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('update_case',jsonb_build_object('funding',jsonb_build_object('status','reviewed','plan','Synthetic','reference','Test','coverage_start','2026-09-01','evidence_event_ids',jsonb_build_array((SELECT reply->>'record_id' FROM br WHERE label='denial')))))$q$,'22023');
DO $$ DECLARE x record; ids jsonb:='[]'; event jsonb; BEGIN
 FOR x IN SELECT * FROM (VALUES ('dcf','eligibility','approved'),('cares','assessment','eligible'),('plan','enrollment','enrolled'),('plan','authorization','authorized')) t(agency,event_type,outcome) LOOP
  event:=pg_temp.bcommand('record_event',jsonb_build_object('agency',x.agency,'event_type',x.event_type,'outcome',x.outcome,'occurred_on','2026-09-21','formal_decision',true,'source_reference','Synthetic attributable letter'));
  ids:=ids||jsonb_build_array(event->>'record_id');
 END LOOP;
 PERFORM pg_temp.bcommand('update_case',jsonb_build_object('funding',jsonb_build_object('status','reviewed','plan','Synthetic','reference','Test','coverage_start','2026-09-01','evidence_event_ids',ids)));
END $$;
SELECT pg_temp.bcommand('update_case','{"status":"closed","closure_reason":"Synthetic test complete"}');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('update_case','{"next_action":"Edited while closed"}')$q$,'22023');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('update_case','{"status":"open","due_date":"2026-12-01"}')$q$,'22023');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('update_case','{"funding":{"notes":"Edited while closed"}}')$q$,'22023');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('record_event','{"agency":"other","event_type":"note","outcome":"note","occurred_on":"2026-09-21"}')$q$,'22023');
SELECT pg_temp.bcommand('update_case','{"status":"open"}');
SELECT pg_temp.bcommand('upsert_requirement',(SELECT jsonb_build_object('id',value->>'id','title',value->>'title','stage',value->>'stage','status','received','signature_status','verified','signed_on','2026-09-20','document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload'),'review_reason','Synthetic signature verified') FROM jsonb_array_elements(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)->'requirements') WHERE value->>'signature_status'='pending' LIMIT 1));
SELECT pg_temp.bassert((SELECT count(*) FROM jsonb_array_elements(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)->'requirements') WHERE value->>'signature_status'='verified' AND value->>'reviewed_by' IS NOT NULL)=1,'verified signature not stamped by reviewer');
SELECT public.benefits_access_set(jsonb_build_object('facility_id',site,'user_id',(SELECT id FROM ba WHERE role='manager'),'can_write',true,'can_review',false,'expires_at',now()+interval '1 day','revoked',true,'reason','Synthetic revocation')) FROM bf;
RESET ROLE; SELECT pg_temp.blogin('manager'); SET LOCAL ROLE authenticated;
SELECT pg_temp.berror($q$SELECT public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)$q$,'42501');
RESET ROLE;
UPDATE public.user_profiles SET settings=jsonb_set(settings,'{must_change_password}','true') WHERE id=(SELECT id FROM ba WHERE role='owner');
SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT pg_temp.berror($q$SELECT public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)$q$,'42501');
RESET ROLE; UPDATE public.user_profiles SET settings=jsonb_set(settings,'{must_change_password}','false') WHERE id=(SELECT id FROM ba WHERE role='owner');
UPDATE storage.objects SET version='v2' WHERE id=(SELECT id FROM bo);
SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT pg_temp.berror($q$SELECT public.benefits_document_target((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')::uuid)$q$,'55000');
RESET ROLE;
UPDATE storage.objects SET version='v1' WHERE id=(SELECT id FROM bo);
-- Operating rules: readable by any benefits actor, changed only by owners/org admins, validated, never back-dated.
SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_rules_list()->'rules')=14,'rules list incomplete');
SELECT pg_temp.bassert((SELECT jsonb_array_length(value->'value') FROM jsonb_array_elements(public.benefits_rules_list()->'rules') WHERE value->>'rule_key'='checklist.smmc_ltc')=18,'default checklist not exposed');
SELECT pg_temp.berror($q$SELECT public.benefits_rule_set('{"rule_key":"family_collection.max_days","value":400,"effective_from":"2026-09-22","reason":"too long"}')$q$,'22023');
SELECT pg_temp.berror($q$SELECT public.benefits_rule_set(jsonb_build_object('rule_key','renewal.warning_days','value',30,'effective_from',(current_date-1)::text,'reason','back-dated'))$q$,'22023');
SELECT pg_temp.berror($q$SELECT public.benefits_rule_set(jsonb_build_object('rule_key','checklist.oss','value','[{"title":"x","stage":"nowhere"}]'::jsonb,'effective_from',current_date::text,'reason','bad stage'))$q$,'22023');
SELECT public.benefits_rule_set(jsonb_build_object('rule_key','checklist.oss','value','[{"title":"Signed OSS application","stage":"application","signature_status":"pending"},{"title":"Income verification","stage":"application"}]'::jsonb,'effective_from',current_date::text,'reason','Synthetic OSS checklist'));
INSERT INTO br SELECT 'oss_case',public.benefits_case_create(other_resident,NULL,'oss',gen_random_uuid()) FROM bf;
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='oss_case')::uuid)->'requirements')=2,'rule-driven OSS checklist not applied');
-- Reading financial evidence is itself recorded.
SELECT public.benefits_document_access((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')::uuid,'download');
SELECT pg_temp.bassert((SELECT count(*) FROM jsonb_array_elements(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)->'history') WHERE value->>'action'='document_download')=1,'download not recorded');
RESET ROLE; SELECT pg_temp.blogin('manager'); SET LOCAL ROLE authenticated;
SELECT pg_temp.berror($q$SELECT public.benefits_rule_set('{"rule_key":"renewal.warning_days","value":30,"effective_from":"2099-01-01","reason":"not mine to set"}')$q$,'42501');
RESET ROLE;
-- Review findings (452): reviewed funding cannot be rewritten by a write-only grantee; notices need evidence; expired + signed_on; void; assignee filter.
SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT public.benefits_access_set(jsonb_build_object('facility_id',site,'user_id',(SELECT id FROM ba WHERE role='manager'),'can_write',true,'can_review',false,'expires_at',now()+interval '1 day','reason','Synthetic re-grant for 453')) FROM bf;
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('record_event',jsonb_build_object('agency','other','event_type','notice_review','outcome','45-day notice considered','occurred_on','2026-09-21'))$q$,'22023');
SELECT pg_temp.bcommand('record_event',jsonb_build_object('agency','other','event_type','notice_review','outcome','45-day notice considered','occurred_on','2026-09-21','document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')));
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('upsert_requirement',jsonb_build_object('id',(SELECT reply->>'record_id' FROM br WHERE label='requirement'),'title','Bank statement','stage','application','status','accepted','signature_status','verified','document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')))$q$,'22023');
RESET ROLE; SELECT pg_temp.blogin('manager'); SET LOCAL ROLE authenticated;
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('update_case','{"funding":{"notes":"write-only rewrite of reviewed funding"}}')$q$,'42501');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('record_event',jsonb_build_object('agency','other','event_type','notice_review','outcome','x','occurred_on','2026-09-21','document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')))$q$,'42501');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('upsert_requirement',jsonb_build_object('id',(SELECT reply->>'record_id' FROM br WHERE label='requirement'),'title','Bank statement','stage','application','status','expired','signature_status','not_required'))$q$,'42501');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('void_document',jsonb_build_object('document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload'),'reason','wrong resident'))$q$,'42501');
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_case_list(jsonb_build_object('assigned_to',(SELECT id FROM ba WHERE role='manager')))->'cases')=1,'assignee filter missed the assigned case');
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_case_list(jsonb_build_object('assigned_to',(SELECT id FROM ba WHERE role='nurse')))->'cases')=0,'assignee filter leaked');
RESET ROLE; SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bcommand('upsert_requirement',jsonb_build_object('id',(SELECT reply->>'record_id' FROM br WHERE label='requirement'),'title','Bank statement','stage','application','status','expired','signature_status','not_required','review_reason','Statements older than three months'));
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('record_submission',jsonb_build_object('stage','application','destination','Synthetic agency','method','portal','sent_at',now(),'document_ids',jsonb_build_array((SELECT reply#>>'{document,id}' FROM br WHERE label='upload'))))$q$,'22023');
SELECT pg_temp.bcommand('void_document',jsonb_build_object('document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload'),'reason','Uploaded to the wrong resident'));
SELECT pg_temp.bassert((SELECT count(*) FROM jsonb_array_elements(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)->'documents') WHERE value->>'voided_at' IS NOT NULL AND value->>'void_reason'='Uploaded to the wrong resident')=1,'void not recorded');
SELECT pg_temp.bassert((SELECT value->>'document_id' IS NULL AND value->>'status' IN ('missing','expired') FROM jsonb_array_elements(public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)->'requirements') WHERE value->>'id'=(SELECT reply->>'record_id' FROM br WHERE label='requirement')),'voided evidence still attached to a requirement');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('void_document',jsonb_build_object('document_id',(SELECT reply#>>'{document,id}' FROM br WHERE label='upload'),'reason','twice'))$q$,'22023');
SELECT pg_temp.berror($q$SELECT public.benefits_document_access((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')::uuid,'download')$q$,'42501');
SELECT pg_temp.bassert((SELECT value->>'assignee_active'='true' FROM jsonb_array_elements(public.benefits_case_list()->'cases') WHERE value->>'id'=(SELECT reply->>'case_id' FROM br WHERE label='case')),'assignee authority not reported');
SELECT public.benefits_access_set(jsonb_build_object('facility_id',site,'user_id',(SELECT id FROM ba WHERE role='manager'),'can_write',true,'can_review',false,'expires_at',now()+interval '1 day','revoked',true,'reason','Synthetic revocation for 453')) FROM bf;
SELECT pg_temp.bassert((SELECT value->>'assignee_active'='false' FROM jsonb_array_elements(public.benefits_case_list()->'cases') WHERE value->>'id'=(SELECT reply->>'case_id' FROM br WHERE label='case')),'lost assignee authority not flagged');
RESET ROLE;
-- A moved resident: the case stays readable and flagged, cannot be written, and a reviewed rebind follows the resident.
UPDATE public.residents SET facility_id=(SELECT other_site FROM bf) WHERE id=(SELECT resident FROM bf);
SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert((public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)#>>'{case,needs_rebind}')='true','moved resident not flagged');
SELECT pg_temp.bassert((SELECT count(*) FROM jsonb_array_elements(public.benefits_case_list()->'cases') WHERE value->>'needs_rebind'='true')=1,'moved case vanished from the queue');
SELECT pg_temp.berror($q$SELECT pg_temp.bcommand('update_case','{"next_action":"write while moved"}')$q$,'42501');
INSERT INTO br SELECT 'rebind_args',jsonb_build_object('request_id',gen_random_uuid());
INSERT INTO br SELECT 'rebind',public.benefits_case_rebind((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,(SELECT reply->>'request_id' FROM br WHERE label='rebind_args')::uuid);
SELECT pg_temp.bassert((SELECT reply->>'facility_id' FROM br WHERE label='rebind')=(SELECT other_site::text FROM bf),'rebind did not follow the resident');
SELECT pg_temp.bassert(public.benefits_case_rebind((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,(SELECT reply->>'request_id' FROM br WHERE label='rebind_args')::uuid)=(SELECT reply FROM br WHERE label='rebind'),'rebind replay changed result');
SELECT pg_temp.berror($q$SELECT public.benefits_case_rebind((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid,gen_random_uuid())$q$,'22023');
SELECT pg_temp.bassert((public.benefits_case_detail((SELECT reply->>'case_id' FROM br WHERE label='case')::uuid)#>>'{case,needs_rebind}')='false','rebind flag not cleared');
RESET ROLE;
ROLLBACK;
