-- Rollback-only synthetic authorization and byte-attestation proof, COL-504.
BEGIN;
CREATE TEMP TABLE bf AS SELECT gen_random_uuid() org,gen_random_uuid() entity,gen_random_uuid() site,gen_random_uuid() other_site,gen_random_uuid() resident;
CREATE TEMP TABLE ba AS SELECT label,CASE WHEN label='owner' THEN 'owner' ELSE 'family' END role,gen_random_uuid() id,gen_random_uuid() session FROM unnest(ARRAY['owner','finance','decision','no_finance','stranger']) label;
CREATE TEMP TABLE br(label text PRIMARY KEY,reply jsonb);
GRANT ALL ON bf,ba,br TO authenticated,service_role;
INSERT INTO public.organizations(id,name) SELECT org,'COL504 family synthetic' FROM bf;
INSERT INTO public.entities(id,organization_id,name) SELECT entity,org,'Synthetic' FROM bf;
INSERT INTO public.facilities(id,organization_id,entity_id,name,address_line_1,city,zip,total_licensed_beds,timezone) SELECT site,org,entity,'Synthetic','Test','Test','00000',2,'America/New_York' FROM bf UNION ALL SELECT other_site,org,entity,'Synthetic other','Test','Test','00000',2,'America/New_York' FROM bf;
INSERT INTO auth.users(id,email,raw_app_meta_data,raw_user_meta_data) SELECT id,id||'@col504.invalid',jsonb_build_object('organization_id',org,'app_role',role),'{}'::jsonb FROM ba,bf;
INSERT INTO public.user_profiles(id,organization_id,full_name,email,app_role,is_active) SELECT id,org,'Synthetic '||label,id||'@col504.invalid',role::public.app_role,true FROM ba,bf ON CONFLICT(id) DO UPDATE SET organization_id=excluded.organization_id,app_role=excluded.app_role,is_active=true;
INSERT INTO auth.sessions(id,user_id) SELECT session,id FROM ba;
INSERT INTO public.user_facility_access(user_id,facility_id,organization_id) SELECT id,site,org FROM ba,bf WHERE label='owner';
INSERT INTO public.residents(id,organization_id,facility_id,first_name,last_name,date_of_birth,gender) SELECT resident,org,site,'Family','Synthetic',DATE '1940-01-01','female'::public.gender FROM bf;
INSERT INTO public.family_resident_links(user_id,resident_id,organization_id,relationship,can_view_financial,can_make_decisions) SELECT id,resident,org,'child',label<>'no_finance',label='decision' FROM ba,bf WHERE label IN ('finance','decision','no_finance');
CREATE FUNCTION pg_temp.blogin(p_label text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$ DECLARE a record; BEGIN SELECT ba.*,p.auth_claim_version INTO a FROM ba JOIN public.user_profiles p USING(id) WHERE ba.label=p_label; PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',a.id,'session_id',a.session,'role','authenticated','auth_claim_version',a.auth_claim_version,'iat',extract(epoch FROM clock_timestamp())::bigint)::text,true); END $$;
CREATE FUNCTION pg_temp.bassert(ok boolean,msg text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF ok IS NOT TRUE THEN RAISE EXCEPTION 'COL504 family %',msg; END IF; END $$;
CREATE FUNCTION pg_temp.berror(stmt text,expected text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN BEGIN EXECUTE stmt; EXCEPTION WHEN OTHERS THEN IF SQLSTATE=expected THEN RETURN; END IF; RAISE; END; RAISE EXCEPTION 'Expected denial %: %',expected,stmt; END $$;
CREATE FUNCTION pg_temp.case_id() RETURNS uuid LANGUAGE sql AS $$ SELECT (reply->>'case_id')::uuid FROM br WHERE label='case'; $$;
CREATE FUNCTION pg_temp.bcommand(action text,payload jsonb) RETURNS jsonb LANGUAGE sql AS $$ SELECT public.benefits_case_command(pg_temp.case_id(),action,payload,(public.benefits_case_detail(pg_temp.case_id())#>>'{case,revision}')::integer,gen_random_uuid()); $$;
CREATE FUNCTION pg_temp.assign(req text,person text) RETURNS jsonb LANGUAGE sql AS $$ SELECT public.benefits_collection_command(pg_temp.case_id(),'assign',jsonb_build_object('requirement_id',(SELECT reply->>'record_id' FROM br WHERE label=req),'family_user_id',(SELECT id FROM ba WHERE label=person),'expires_at',now()+interval '1 day'),(public.benefits_case_detail(pg_temp.case_id())#>>'{case,revision}')::integer,gen_random_uuid()); $$;
CREATE FUNCTION pg_temp.family_id(label text) RETURNS uuid LANGUAGE sql AS $$ SELECT (reply->>'collection_id')::uuid FROM br WHERE br.label=$1; $$;
CREATE FUNCTION pg_temp.family_revision(label text) RETURNS integer LANGUAGE sql AS $$ SELECT (item->>'revision')::integer FROM jsonb_array_elements(public.benefits_family_list()->'requests') item WHERE item->>'id'=pg_temp.family_id($1)::text; $$;
CREATE FUNCTION pg_temp.finish(label text) RETURNS jsonb LANGUAGE sql AS $$ SELECT public.benefits_family_command(pg_temp.family_id($1),'finalize',jsonb_build_object('document_id',(SELECT reply#>>'{document,id}' FROM br WHERE br.label='upload')),pg_temp.family_revision($1),gen_random_uuid()); $$;
SELECT pg_temp.bassert(NOT has_table_privilege('authenticated','public.benefits_collection_requests','SELECT,INSERT,UPDATE,DELETE'),'direct grants');
SELECT pg_temp.bassert(NOT has_function_privilege('anon','public.benefits_family_list()','EXECUTE'),'anonymous listing');
SELECT pg_temp.bassert(NOT has_function_privilege('authenticated','haven.benefits_family_eligible(uuid,public.benefits_cases,boolean)','EXECUTE'),'private authority helper exposed');
SELECT pg_temp.bassert(NOT has_function_privilege('service_role','public.benefits_family_command(uuid,text,jsonb,integer,uuid)','EXECUTE'),'service impersonation');
SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
INSERT INTO br SELECT 'case',public.benefits_case_create(resident,NULL,'smmc_ltc',gen_random_uuid()) FROM bf;
INSERT INTO br SELECT 'bank',pg_temp.bcommand('upsert_requirement','{"title":"Bank statement","stage":"application","status":"requested","signature_status":"not_required"}');
INSERT INTO br SELECT 'signature',pg_temp.bcommand('upsert_requirement','{"title":"Signed release","stage":"application","status":"requested","signature_status":"pending"}');
SELECT pg_temp.berror($q$SELECT pg_temp.assign('bank','no_finance')$q$,'42501');
SELECT pg_temp.berror($q$SELECT pg_temp.assign('signature','finance')$q$,'42501');
SELECT pg_temp.berror($q$SELECT pg_temp.assign('bank','stranger')$q$,'42501');
INSERT INTO br SELECT 'bank_request',pg_temp.assign('bank','finance');
INSERT INTO br SELECT 'signature_request',pg_temp.assign('signature','decision');
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_collection_list(pg_temp.case_id())->'requests')=2,'staff request list');
RESET ROLE; SELECT pg_temp.blogin('no_finance'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert(public.benefits_family_list()->'requests'='[]'::jsonb,'no financial permission leaked requests');
RESET ROLE; SELECT pg_temp.blogin('stranger'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert(public.benefits_family_list()->'requests'='[]'::jsonb,'unlinked family leaked requests');
RESET ROLE; SELECT pg_temp.blogin('finance'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert(jsonb_array_length(public.benefits_family_list()->'requests')=1,'explicit scope');
SELECT pg_temp.bassert(NOT (public.benefits_family_list()#>'{requests,0}') ?| ARRAY['case_id','funding','documents','screening','history','storage_path'],'case data leak');
SELECT pg_temp.berror($q$SELECT public.benefits_case_detail(pg_temp.case_id())$q$,'42501');
SELECT pg_temp.berror($q$SELECT public.benefits_collection_list(pg_temp.case_id())$q$,'42501');
SELECT pg_temp.berror($q$SELECT * FROM public.benefits_collection_requests$q$,'42501');
SELECT pg_temp.berror($q$SELECT public.benefits_family_command(pg_temp.family_id('signature_request'),'prepare','{}',1,gen_random_uuid())$q$,'42501');
INSERT INTO br SELECT 'upload_args',jsonb_build_object('request_id',gen_random_uuid(),'revision',pg_temp.family_revision('bank_request'));
INSERT INTO br SELECT 'upload',public.benefits_family_command(pg_temp.family_id('bank_request'),'prepare','{"filename":"statement.pdf","mime_type":"application/pdf","size_bytes":12,"sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}',(SELECT (reply->>'revision')::integer FROM br WHERE label='upload_args'),(SELECT (reply->>'request_id')::uuid FROM br WHERE label='upload_args'));
SELECT pg_temp.bassert(public.benefits_family_command(pg_temp.family_id('bank_request'),'prepare','{"filename":"statement.pdf","mime_type":"application/pdf","size_bytes":12,"sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}',(SELECT (reply->>'revision')::integer FROM br WHERE label='upload_args'),(SELECT (reply->>'request_id')::uuid FROM br WHERE label='upload_args'))=(SELECT reply FROM br WHERE label='upload'),'prepare replay changed');
SELECT pg_temp.berror($q$SELECT public.benefits_family_command(pg_temp.family_id('bank_request'),'prepare','{}',(SELECT (reply->>'revision')::integer FROM br WHERE label='upload_args'),(SELECT (reply->>'request_id')::uuid FROM br WHERE label='upload_args'))$q$,'23505');
SELECT pg_temp.berror($q$SELECT public.benefits_family_command(pg_temp.family_id('bank_request'),'finalize','{}',1,gen_random_uuid())$q$,'40001');
SELECT pg_temp.berror($q$SELECT pg_temp.finish('bank_request')$q$,'55000');
RESET ROLE;
INSERT INTO storage.objects(bucket_id,name,version,metadata) SELECT 'benefits-documents',reply#>>'{document,storage_path}','v1',jsonb_build_object('size',12,'mimetype','application/pdf','eTag','family-etag1') FROM br WHERE label='upload';
CREATE TEMP TABLE bo AS SELECT o.id,o.version,o.metadata->>'eTag' etag FROM storage.objects o WHERE o.name=(SELECT reply#>>'{document,storage_path}' FROM br WHERE label='upload'); GRANT SELECT ON bo TO service_role;
SET LOCAL ROLE service_role;
SELECT pg_temp.berror($q$SELECT public.benefits_document_attest((SELECT reply#>>'{document,id}' FROM br WHERE label='upload')::uuid,repeat('b',64),12,'application/pdf',id,version,etag) FROM bo$q$,'55000');
SELECT public.benefits_document_attest((SELECT reply#>>'{document,id}' FROM br WHERE label='upload')::uuid,repeat('a',64),12,'application/pdf',id,version,etag) FROM bo;
RESET ROLE;
UPDATE storage.objects SET version='v2' WHERE id=(SELECT id FROM bo);
SELECT pg_temp.blogin('finance'); SET LOCAL ROLE authenticated;
SELECT pg_temp.berror($q$SELECT pg_temp.finish('bank_request')$q$,'55000');
RESET ROLE;
UPDATE storage.objects SET version='v1' WHERE id=(SELECT id FROM bo);
UPDATE public.family_resident_links SET revoked_at=now() WHERE user_id=(SELECT id FROM ba WHERE label='finance');
SELECT pg_temp.blogin('finance'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert(public.benefits_family_list()->'requests'='[]'::jsonb,'revoked linkage leaked list');
SELECT pg_temp.berror($q$SELECT pg_temp.finish('bank_request')$q$,'42501');
SELECT pg_temp.berror($q$SELECT public.benefits_family_target(pg_temp.family_id('bank_request'),(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')::uuid)$q$,'42501');
RESET ROLE;
UPDATE public.family_resident_links SET revoked_at=NULL WHERE user_id=(SELECT id FROM ba WHERE label='finance');
SELECT pg_temp.blogin('finance'); SET LOCAL ROLE authenticated;
INSERT INTO br SELECT 'finished',pg_temp.finish('bank_request');
SELECT pg_temp.bassert(public.benefits_family_list()#>>'{requests,0,upload,status}'='received','upload status not received');
RESET ROLE;
SELECT pg_temp.bassert((SELECT status='received' AND reviewed_by IS NULL AND signature_status='not_required' FROM public.benefits_requirements WHERE id=(SELECT (reply->>'record_id')::uuid FROM br WHERE label='bank')),'family promoted evidence review');
UPDATE public.family_resident_links SET can_make_decisions=false WHERE user_id=(SELECT id FROM ba WHERE label='decision');
SELECT pg_temp.blogin('decision'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert(public.benefits_family_list()->'requests'='[]'::jsonb,'removed signing authority leaked request');
RESET ROLE; SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT public.benefits_collection_command(pg_temp.case_id(),'revoke',jsonb_build_object('collection_id',pg_temp.family_id('bank_request')),(public.benefits_case_detail(pg_temp.case_id())#>>'{case,revision}')::integer,gen_random_uuid());
RESET ROLE; SELECT pg_temp.blogin('finance'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert(public.benefits_family_list()->'requests'='[]'::jsonb,'revoked request leaked list');
SELECT pg_temp.berror($q$SELECT public.benefits_family_target(pg_temp.family_id('bank_request'),(SELECT reply#>>'{document,id}' FROM br WHERE label='upload')::uuid)$q$,'42501');
RESET ROLE;
UPDATE public.family_resident_links SET can_make_decisions=true WHERE user_id=(SELECT id FROM ba WHERE label='decision');
SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bcommand('update_case','{"status":"closed","closure_reason":"Synthetic close"}');
RESET ROLE; SELECT pg_temp.blogin('decision'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert(public.benefits_family_list()->'requests'='[]'::jsonb,'closed case leaked request');
RESET ROLE; SELECT pg_temp.blogin('owner'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bcommand('update_case','{"status":"open"}');
RESET ROLE;
UPDATE public.residents SET facility_id=(SELECT other_site FROM bf) WHERE id=(SELECT resident FROM bf);
SELECT pg_temp.blogin('decision'); SET LOCAL ROLE authenticated;
SELECT pg_temp.bassert(public.benefits_family_list()->'requests'='[]'::jsonb,'transfer leaked request');
SELECT pg_temp.berror($q$SELECT public.benefits_family_command(pg_temp.family_id('signature_request'),'prepare','{}',1,gen_random_uuid())$q$,'42501');
RESET ROLE;
ROLLBACK;
