-- Local rollback-only probe: real current-authority checks, private ACLs and durable dedupe.
BEGIN;
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(auth.jwt()->>'sub','')::uuid $$;
CREATE TEMP TABLE email_actor AS SELECT gen_random_uuid() id,gen_random_uuid() session,id org FROM public.organizations LIMIT 1;
INSERT INTO auth.users(id,email,raw_app_meta_data,raw_user_meta_data) SELECT id,id||'@example.invalid',jsonb_build_object('organization_id',org,'app_role','owner'),'{}' FROM email_actor;
INSERT INTO public.user_profiles(id,organization_id,full_name,email,app_role,is_active) SELECT id,org,'Synthetic email administrator',id||'@example.invalid','owner',true FROM email_actor ON CONFLICT(id) DO UPDATE SET organization_id=excluded.organization_id,app_role='owner',is_active=true;
INSERT INTO auth.sessions(id,user_id) SELECT session,id FROM email_actor;
GRANT SELECT ON email_actor TO authenticated;
GRANT USAGE ON SCHEMA auth TO authenticated;
SELECT set_config('request.jwt.claims',jsonb_build_object('sub',a.id,'session_id',a.session,'role','authenticated','app_role','owner','organization_id',a.org,'auth_claim_version',p.auth_claim_version,'iat',extract(epoch FROM clock_timestamp())::bigint)::text,true) FROM email_actor a JOIN public.user_profiles p USING(id);
CREATE FUNCTION pg_temp.email_assert(ok boolean,msg text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF ok IS NOT TRUE THEN RAISE EXCEPTION '%',msg;END IF;END $$;
CREATE FUNCTION pg_temp.email_error(stmt text,code text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN BEGIN EXECUTE stmt;EXCEPTION WHEN OTHERS THEN IF SQLSTATE=code THEN RETURN;END IF;RAISE;END;RAISE EXCEPTION 'Expected SQLSTATE %',code;END $$;
SET LOCAL ROLE authenticated;
SELECT pg_temp.email_assert(public.system_alert_settings_get()->'settings'->>'version'='0','Default version');
SELECT public.system_alert_settings_update(0,true,ARRAY['admin@example.invalid'],ARRAY['job_failure','job_recovery','monitor_failure']);
SELECT pg_temp.email_error($q$SELECT public.system_alert_settings_update(0,true,ARRAY['wrong@example.invalid'],ARRAY['job_failure'])$q$,'40001');
SELECT pg_temp.email_error($q$SELECT public.system_alert_settings_update(1,true,ARRAY[]::text[],ARRAY['job_failure'])$q$,'22023');
SELECT pg_temp.email_error($q$SELECT public.system_alert_settings_update(1,true,ARRAY['a@example.invalid','a@example.invalid'],ARRAY['job_failure'])$q$,'22023');
SELECT pg_temp.email_error('SELECT * FROM job_monitor.email_settings','42501');
SELECT public.system_alert_email_test(1);
SELECT pg_temp.email_error('SELECT public.system_alert_email_test(1)','54000');
RESET ROLE;
SELECT pg_temp.email_assert((SELECT count(*)=1 FROM job_monitor.email_settings_audit),'Atomic audit');
SELECT job_monitor.queue_email_signal('jobs',repeat('a',64),true,'[]');
SELECT pg_temp.email_assert((SELECT count(*)=0 FROM job_monitor.email_deliveries WHERE kind='job_failure'),'Unbound organization cannot subscribe to infrastructure');
SELECT public.system_alert_email_claim(id,false) FROM job_monitor.email_deliveries WHERE kind='test';
UPDATE job_monitor.email_deliveries SET created_at=now()-interval '2 days' WHERE kind='test';
SELECT pg_temp.email_assert(public.system_alert_email_claim(id,true) IS NOT NULL,'Unconfigured time does not consume provider retry window') FROM job_monitor.email_deliveries WHERE kind='test';
SELECT public.system_alert_email_finish(id,claim_token,'provider_accepted','synthetic-test',null) FROM job_monitor.email_deliveries WHERE kind='test';
INSERT INTO job_monitor.email_monitor_scope SELECT org FROM email_actor;
SELECT job_monitor.queue_email_signal('jobs',repeat('a',64),true,'[{"jobid":1,"jobname":"Synthetic job","state":"error"}]');
SELECT job_monitor.queue_email_signal('jobs',repeat('a',64),true,'[]');
SELECT pg_temp.email_assert((SELECT count(*)=1 FROM job_monitor.email_deliveries WHERE kind='job_failure'),'Unchanged failure deduped');
SELECT public.system_alert_email_claim(id) FROM job_monitor.email_deliveries WHERE kind='job_failure';
SELECT pg_temp.email_assert(public.system_alert_email_claim(id) IS NULL,'Concurrent claim suppressed') FROM job_monitor.email_deliveries WHERE kind='job_failure';
CREATE TEMP TABLE old_email_claim AS SELECT id,claim_token FROM job_monitor.email_deliveries WHERE kind='job_failure';
UPDATE job_monitor.email_deliveries SET lease_until=now()-interval '1 second' WHERE kind='job_failure';
SELECT public.system_alert_email_claim(id) FROM job_monitor.email_deliveries WHERE kind='job_failure';
SELECT pg_temp.email_error(format('SELECT public.system_alert_email_finish(%L,%L,%L,null,null)',id,claim_token,'failed'),'40001') FROM old_email_claim;
SELECT public.system_alert_email_finish(id,claim_token,'failed',null,'provider_http_503') FROM job_monitor.email_deliveries WHERE kind='job_failure';
SELECT pg_temp.email_assert(public.system_alert_email_claim(id)->>'id'=id::text,'Failed delivery retries same id') FROM job_monitor.email_deliveries WHERE kind='job_failure';
SELECT public.system_alert_email_finish(id,claim_token,'provider_accepted','synthetic-provider',null) FROM job_monitor.email_deliveries WHERE kind='job_failure';
SELECT pg_temp.email_assert(public.system_alert_email_claim(id) IS NULL,'Accepted delivery not resent') FROM job_monitor.email_deliveries WHERE kind='job_failure';
SELECT job_monitor.queue_email_signal('jobs',repeat('b',64),false,'[]');
SELECT job_monitor.queue_email_signal('jobs',repeat('b',64),false,'[]');
SELECT job_monitor.queue_email_signal('jobs',repeat('a',64),true,'[]');
SELECT pg_temp.email_assert((SELECT count(*)=1 FROM job_monitor.email_deliveries WHERE kind='job_recovery'),'Recovery deduped');
SELECT pg_temp.email_assert((SELECT count(*)=2 FROM job_monitor.email_deliveries WHERE kind='job_failure'),'Recurrence sends new episode');
SELECT pg_temp.email_assert(NOT has_function_privilege('authenticated','public.system_alert_email_claim(uuid,boolean)','EXECUTE'),'Authenticated cannot dispatch');
SELECT pg_temp.email_assert(NOT has_function_privilege('service_role','public.system_alert_settings_update(integer,boolean,text[],text[])','EXECUTE'),'Service cannot edit settings');
UPDATE public.user_profiles SET is_active=false WHERE id=(SELECT id FROM email_actor);
SET LOCAL ROLE authenticated;
SELECT pg_temp.email_error('SELECT public.system_alert_settings_get()','42501');
SELECT pg_temp.email_error($q$SELECT public.system_alert_settings_update(1,false,ARRAY['admin@example.invalid'],ARRAY['job_failure'])$q$,'42501');
RESET ROLE;
ROLLBACK;
