-- Disposable local PostgreSQL proof only. All synthetic rows roll back.
BEGIN;
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(auth.jwt()->>'sub','')::uuid $$;
CREATE TEMP TABLE cd_actor AS SELECT gen_random_uuid() id,gen_random_uuid() session,f.organization_id org FROM public.facilities f WHERE f.deleted_at IS NULL GROUP BY f.organization_id HAVING count(*)>=2 LIMIT 1;
CREATE TEMP TABLE cd_issue_owner AS SELECT gen_random_uuid() id,(SELECT org FROM cd_actor) org;
CREATE TEMP TABLE cd_sites AS SELECT row_number() OVER(ORDER BY f.id)::integer n,f.id facility,f.organization_id org,gen_random_uuid() subject,NULL::uuid task,gen_random_uuid() census,p.start_date,p.start_date+2 end_date FROM public.facilities f JOIN cd_actor a ON a.org=f.organization_id CROSS JOIN LATERAL(SELECT date_trunc('week',current_date-40)::date start_date)p WHERE f.deleted_at IS NULL ORDER BY f.id LIMIT 2;
DO $$ BEGIN IF (SELECT count(*) FROM cd_sites)<>2 THEN RAISE EXCEPTION 'COL160 two seed sites required';END IF;END $$;
INSERT INTO auth.users(id,email,raw_app_meta_data,raw_user_meta_data) SELECT id,id||'@col160.invalid',jsonb_build_object('organization_id',org,'app_role','owner'),'{}' FROM cd_actor;
INSERT INTO auth.users(id,email,raw_app_meta_data,raw_user_meta_data) SELECT id,id||'@col160.invalid',jsonb_build_object('organization_id',org,'app_role','manager'),'{}' FROM cd_issue_owner;
INSERT INTO public.user_profiles(id,organization_id,full_name,email,app_role,is_active) SELECT id,org,'COL160 synthetic owner',id||'@col160.invalid','owner',true FROM cd_actor ON CONFLICT(id) DO UPDATE SET organization_id=excluded.organization_id,app_role='owner',is_active=true;
INSERT INTO public.user_profiles(id,organization_id,full_name,email,app_role,is_active) SELECT id,org,'COL160 separate issue owner',id||'@col160.invalid','manager',true FROM cd_issue_owner;
INSERT INTO auth.sessions(id,user_id) SELECT session,id FROM cd_actor;
INSERT INTO public.user_facility_access(user_id,facility_id,organization_id) SELECT a.id,s.facility,s.org FROM cd_actor a,cd_sites s;
INSERT INTO public.user_facility_access(user_id,facility_id,organization_id) SELECT a.id,s.facility,s.org FROM cd_issue_owner a,cd_sites s;
INSERT INTO public.operation_subject_access(organization_id,facility_id,user_id,scope,granted_by,reason,can_record) SELECT s.org,s.facility,a.id,'financial',a.id,'Synthetic COL160 native source scope',true FROM cd_actor a,cd_sites s;
INSERT INTO public.operation_activity_subjects(id,organization_id,facility_id,subject_kind) SELECT subject,org,facility,'facility' FROM cd_sites;
INSERT INTO public.census_daily_log(id,facility_id,organization_id,log_date,total_licensed_beds,occupied_beds,available_beds,hold_beds,maintenance_beds,occupancy_rate) SELECT census,facility,org,start_date,20,10+n,10-n,0,0,(10+n)::numeric/20 FROM cd_sites;
GRANT USAGE ON SCHEMA auth TO authenticated;GRANT SELECT ON ALL TABLES IN SCHEMA public TO authenticated;GRANT SELECT ON cd_actor,cd_issue_owner TO authenticated;GRANT ALL ON cd_sites TO authenticated;
SELECT set_config('request.jwt.claims',jsonb_build_object('sub',a.id,'session_id',a.session,'role','authenticated','app_role','owner','organization_id',a.org,'auth_claim_version',p.auth_claim_version,'iat',extract(epoch FROM clock_timestamp())::bigint)::text,true) FROM cd_actor a JOIN public.user_profiles p USING(id);
CREATE TEMP TABLE cd_receipts(name text PRIMARY KEY,value jsonb);GRANT ALL ON cd_receipts TO authenticated;
CREATE FUNCTION pg_temp.cd_assert(ok boolean,msg text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF ok IS NOT TRUE THEN RAISE EXCEPTION 'COL160 %',msg;END IF;END $$;
CREATE FUNCTION pg_temp.cd_error(stmt text,fragment text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN BEGIN EXECUTE stmt;EXCEPTION WHEN OTHERS THEN IF position(fragment IN SQLERRM)>0 THEN RETURN;END IF;RAISE EXCEPTION 'Unexpected error % wanted %',SQLERRM,fragment;END;RAISE EXCEPTION 'Expected rejection %',fragment;END $$;
CREATE FUNCTION pg_temp.cd_detail(p_task uuid,p_site uuid,p_start date,p_end date) RETURNS jsonb LANGUAGE sql VOLATILE AS $$ SELECT x->'expectation' FROM jsonb_array_elements(public.corporate_deliverable_snapshot(p_task,p_start,p_end)->'sites')x WHERE (x->>'facility_id')::uuid=p_site $$;
CREATE FUNCTION pg_temp.cd_private_stats(p_site uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT jsonb_build_object('expectations',(SELECT count(*) FROM haven.corporate_submission_expectations),'coverage_sets',(SELECT count(*) FROM haven.corporate_coverage_sets),'site_versions',(SELECT count(*) FROM haven.corporate_submission_versions v JOIN haven.corporate_submission_expectations e ON e.id=v.expectation_id WHERE e.facility_id=p_site),'state_kinds',(SELECT count(DISTINCT kind) FROM haven.corporate_submission_events WHERE kind IN('prepared','sent','received','accepted')),'meeting_hash',(SELECT encode(sha256(convert_to(snapshot::text,'UTF8')),'hex') FROM haven.corporate_meeting_captures ORDER BY captured_at LIMIT 1)) $$;
CREATE FUNCTION pg_temp.cd_missing_meeting_stats() RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT jsonb_build_object('meetings',(SELECT count(*) FROM haven.corporate_meeting_captures),'requests',(SELECT count(*) FROM haven.corporate_deliverable_requests WHERE request_key='col160-missing-001'),'snapshot_bytes',(SELECT encode(convert_to(snapshot::text,'UTF8'),'base64') FROM haven.corporate_meeting_captures ORDER BY captured_at LIMIT 1)) $$;
SET LOCAL ROLE authenticated;
INSERT INTO cd_receipts VALUES('rule',public.save_operation_requirement_draft_review((SELECT id FROM public.operation_activities WHERE organization_id=(SELECT org FROM cd_actor) AND activity_key='hfo-al-m09-01'),'{"title":"Synthetic corporate census packet","wording":"Prepare a native source packet without sending it","allowed_recorder_roles":["owner"],"subject_kind":"facility"}'));
SELECT public.publish_operation_requirement_review((SELECT (value->>'id')::uuid FROM cd_receipts WHERE name='rule'),clock_timestamp()-interval '1 hour');
INSERT INTO cd_receipts SELECT 'site-'||n,public.save_operation_facility_requirement_draft_review((SELECT id FROM public.operation_activities WHERE organization_id=(SELECT org FROM cd_actor) AND activity_key='hfo-al-m09-01'),facility,jsonb_build_object('applicability','applicable','requirement_version_id',(SELECT value->>'id' FROM cd_receipts WHERE name='rule'),'schedule_status','needs_confirmation')) FROM cd_sites;
SELECT public.publish_operation_facility_requirement_review((value->>'id')::uuid,clock_timestamp()-interval '30 minutes') FROM cd_receipts WHERE name LIKE 'site-%';
INSERT INTO cd_receipts SELECT 'task-'||n,public.create_operation_manual_occurrence_review((SELECT id FROM public.operation_activities WHERE organization_id=s.org AND activity_key='hfo-al-m09-01'),s.facility,s.subject,'col160-manual-'||n,'{}') FROM cd_sites s;
UPDATE cd_sites s SET task=(r.value->>'id')::uuid FROM cd_receipts r WHERE r.name='task-'||s.n;

-- Stable identity and explicit expected coverage. The first site must not hide site2.
SELECT public.corporate_deliverable_command(task,'col160-register-001','register',jsonb_build_object('period_start',start_date,'period_end',end_date,'period_provenance','Controller selected synthetic close period','expected_facility_ids',(SELECT jsonb_agg(facility ORDER BY facility) FROM cd_sites))) FROM cd_sites WHERE n=1;
SELECT pg_temp.cd_assert((pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'expectations')::integer=1,'first register duplicated');
SELECT pg_temp.cd_assert((SELECT count(*)=1 FROM cd_sites s,jsonb_array_elements(public.corporate_deliverable_snapshot(s.task,s.start_date,s.end_date)->'sites')x WHERE s.n=1 AND x->>'status'='missing'),'missing expected site silently omitted');
-- A committed missing-site meeting must survive the actual reply schema and exact replay.
SAVEPOINT cd_missing_meeting;
CREATE TEMP TABLE cd_missing_meeting_payload AS SELECT task,jsonb_build_object('period_start',start_date,'period_end',end_date,'coverage_revision',public.corporate_deliverable_snapshot(task,start_date,end_date)#>>'{coverage,revision}','presented_at',NULL,'presented_on',NULL,'presentation_provenance',NULL) payload FROM cd_sites WHERE n=1;
SELECT public.corporate_deliverable_command(task,'col160-missing-001','capture_meeting',payload) FROM cd_missing_meeting_payload;
CREATE TEMP TABLE cd_missing_meeting_read AS SELECT public.corporate_deliverable_snapshot(task,start_date,end_date) snapshot FROM cd_sites WHERE n=1;
SELECT jsonb_build_object('col160_schema_snapshot','capture_missing','snapshot',snapshot) FROM cd_missing_meeting_read;
SELECT pg_temp.cd_assert((SELECT count(*)=1 AND bool_and(x->'expectation'='null'::jsonb) FROM cd_missing_meeting_read,jsonb_array_elements(snapshot#>'{meetings,0,snapshot,sites}')x WHERE x->>'status'='missing'),'missing meeting expectation must remain JSON null');
SELECT pg_temp.cd_assert((SELECT count(*)=1 AND bool_and(jsonb_typeof(x->'expectation')='object' AND x#>>'{expectation,id}' IS NOT NULL) FROM cd_missing_meeting_read,jsonb_array_elements(snapshot#>'{meetings,0,snapshot,sites}')x WHERE x->>'status'='expected'),'registered meeting expectation lost native identity');
CREATE TEMP TABLE cd_missing_meeting_bytes AS SELECT pg_temp.cd_missing_meeting_stats() stats;
SELECT pg_temp.cd_assert((SELECT stats->>'meetings'='1' AND stats->>'requests'='1' FROM cd_missing_meeting_bytes),'first missing meeting must commit exactly one capture and request');
SELECT pg_temp.cd_assert((public.corporate_deliverable_command(task,'col160-missing-001','capture_meeting',payload)->>'replayed')::boolean,'missing meeting retry did not replay') FROM cd_missing_meeting_payload;
SELECT jsonb_build_object('col160_schema_snapshot','read_after_identical_retry','snapshot',public.corporate_deliverable_snapshot(task,start_date,end_date)) FROM cd_sites WHERE n=1;
SELECT pg_temp.cd_assert((SELECT pg_temp.cd_missing_meeting_stats()=stats FROM cd_missing_meeting_bytes),'identical retry changed capture bytes or duplicated meeting/request');
SELECT pg_temp.cd_assert((SELECT public.corporate_deliverable_snapshot(s.task,s.start_date,s.end_date)=r.snapshot FROM cd_sites s,cd_missing_meeting_read r WHERE s.n=1),'identical retry changed the complete meeting reply');
ROLLBACK TO SAVEPOINT cd_missing_meeting;
RELEASE SAVEPOINT cd_missing_meeting;

SELECT public.corporate_deliverable_command(task,'col160-register-002','register',jsonb_build_object('period_start',start_date,'period_end',end_date,'period_provenance','Controller selected synthetic close period','expected_facility_ids',(SELECT jsonb_agg(facility ORDER BY facility) FROM cd_sites))) FROM cd_sites WHERE n=2;
SELECT pg_temp.cd_assert((pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'expectations')::integer=2 AND (pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'coverage_sets')::integer=1,'repeated intake duplicated stable expectation or site set');
INSERT INTO cd_receipts SELECT 'race-issue',public.report_operation_issue_review('col160-race-issue',jsonb_build_object('task_instance_id',task,'kind','problem','summary','Synthetic race follow-up','severity','normal')) FROM cd_sites WHERE n=1;
INSERT INTO cd_receipts SELECT 'race-assigned',public.assign_operation_issue_review((value#>>'{issue,id}')::uuid,'col160-race-assign',(value#>>'{issue,issue_revision}'),jsonb_build_object('owner_user_id',(SELECT id FROM cd_issue_owner),'note','Synthetic race owner')) FROM cd_receipts WHERE name='race-issue';
INSERT INTO cd_receipts SELECT 'race-issue-two',public.report_operation_issue_review('col160-race-issue-two',jsonb_build_object('task_instance_id',task,'kind','problem','summary','Synthetic second race follow-up','severity','normal')) FROM cd_sites WHERE n=1;
INSERT INTO cd_receipts SELECT 'race-assigned-two',public.assign_operation_issue_review((value#>>'{issue,id}')::uuid,'col160-race-assign-two',(value#>>'{issue,issue_revision}'),jsonb_build_object('owner_user_id',(SELECT id FROM cd_issue_owner),'note','Synthetic second race owner')) FROM cd_receipts WHERE name='race-issue-two';
-- CONCURRENCY_SETUP_END
SELECT public.corporate_deliverable_command(task,'col160-register-001','register',jsonb_build_object('period_start',start_date,'period_end',end_date,'period_provenance','Controller selected synthetic close period','expected_facility_ids',(SELECT jsonb_agg(facility ORDER BY facility) FROM cd_sites))) FROM cd_sites WHERE n=1;
SELECT pg_temp.cd_assert((pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'expectations')::integer=2,'exact request replay duplicated');
SELECT public.corporate_deliverable_command(task,'col160-register-nochange','register',jsonb_build_object('period_start',start_date,'period_end',end_date,'period_provenance','Controller selected synthetic close period','expected_facility_ids',(SELECT jsonb_agg(facility ORDER BY facility) FROM cd_sites))) FROM cd_sites WHERE n=1;
SELECT pg_temp.cd_assert((pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'coverage_sets')::integer=1,'unchanged coverage duplicated');
SELECT public.corporate_deliverable_command(task,'col160-register-corrected','register',jsonb_build_object('period_start',start_date,'period_end',end_date,'period_provenance','Corrected controller close roster source','expected_facility_ids',(SELECT jsonb_agg(facility ORDER BY facility) FROM cd_sites))) FROM cd_sites WHERE n=1;
SELECT pg_temp.cd_assert((pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'coverage_sets')::integer=2,'corrected coverage provenance was discarded');
SELECT public.corporate_deliverable_command(task,'col160-coverage-b','register',jsonb_build_object('period_start',start_date,'period_end',end_date,'period_provenance','Temporary one-site reviewed roster','expected_facility_ids',jsonb_build_array(facility))) FROM cd_sites WHERE n=1;
SELECT public.corporate_deliverable_command(task,'col160-coverage-a-return','register',jsonb_build_object('period_start',start_date,'period_end',end_date,'period_provenance','Restored reviewed two-site roster','expected_facility_ids',(SELECT jsonb_agg(facility ORDER BY facility) FROM cd_sites))) FROM cd_sites WHERE n=1;
SELECT pg_temp.cd_assert((pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'coverage_sets')::integer=4,'coverage A to B to A history collapsed');

-- Direct authenticated RPC must enforce due evidence independently of the HTTP schema.
-- Roll back this focused check so existing lifecycle and pagination fixture counts stay exact.
SAVEPOINT cd_due_provenance;
DO $$ DECLARE s cd_sites;before_detail jsonb;after_detail jsonb;bad jsonb;payload jsonb;refused boolean;trim_chars CONSTANT text:=U&'\0009\000A\000B\000C\000D\0020\00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000\FEFF';
BEGIN
 SELECT * INTO s FROM cd_sites WHERE n=1;before_detail:=pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date);
 payload:=jsonb_build_object('expectation_id',before_detail->>'id','expected_revision',before_detail->>'revision','recipient_label',NULL,'backup_label',NULL,'due_on',current_date-1,'configuration_provenance','Synthetic due evidence validation');
 PERFORM pg_temp.cd_assert(length(trim_chars)=25,'ECMAScript trim set must contain all 25 whitespace codepoints');
 FOR bad IN SELECT to_jsonb(substring(trim_chars FROM i FOR 1)) FROM generate_series(1,length(trim_chars))i UNION ALL SELECT to_jsonb(unnest(ARRAY['',trim_chars,reverse(trim_chars),repeat('x',1001),trim_chars||repeat('x',1001)||trim_chars])) UNION ALL SELECT value FROM jsonb_array_elements('[null,42,true,false,{},[],["evidence"],{"source":"evidence"}]'::jsonb) LOOP
  refused:=false;
  BEGIN PERFORM public.corporate_deliverable_command(s.task,'col160-invalid-due-evidence','configure',payload||jsonb_build_object('due_provenance',bad));
  EXCEPTION WHEN SQLSTATE '22023' THEN refused:=true;END;
  PERFORM pg_temp.cd_assert(refused,'blank or oversized due provenance accepted by direct RPC');
  after_detail:=pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date);
  PERFORM pg_temp.cd_assert(after_detail=before_detail,'refused due evidence mutated configuration or history');
 END LOOP;
 refused:=false;
 BEGIN PERFORM public.corporate_deliverable_command(s.task,'col160-unpaired-due-evidence','configure',payload||jsonb_build_object('due_on',NULL,'due_provenance','Evidence without a due date'));
 EXCEPTION WHEN SQLSTATE '22023' THEN refused:=true;END;
 PERFORM pg_temp.cd_assert(refused AND pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)=before_detail,'unpaired due evidence accepted or mutated state');
 PERFORM public.corporate_deliverable_command(s.task,'col160-valid-due-evidence','configure',payload||jsonb_build_object('due_provenance',trim_chars||'Approved synthetic café close calendar'||reverse(trim_chars)));
 after_detail:=pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date);
 PERFORM pg_temp.cd_assert(after_detail->>'due_state'='documented' AND (after_detail->>'due_on')::date=current_date-1 AND after_detail#>>'{events,0,details,due_provenance}'='Approved synthetic café close calendar','valid attributable due evidence lost');
 PERFORM public.corporate_deliverable_command(s.task,'col160-max-valid-due-evidence','configure',payload||jsonb_build_object('expected_revision',after_detail->>'revision','due_provenance',trim_chars||repeat('x',1000)||reverse(trim_chars)));
 after_detail:=pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date);
 PERFORM pg_temp.cd_assert(after_detail#>>'{events,1,details,due_provenance}'=repeat('x',1000),'normalized 1000-character due evidence must remain valid');
END $$;
ROLLBACK TO SAVEPOINT cd_due_provenance;
RELEASE SAVEPOINT cd_due_provenance;

-- Unknown recipient/backup/due remain unknown. Preparation is one immutable state.
SELECT public.corporate_deliverable_command(s.task,'col160-configure-001','configure',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','recipient_label',NULL,'backup_label',NULL,'due_on',NULL,'configuration_provenance','No approved recipient, backup or schedule in source','due_provenance',NULL)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT pg_temp.cd_assert((SELECT pg_temp.cd_detail(task,facility,start_date,end_date)#>>'{due_state}'='unknown' FROM cd_sites WHERE n=1),'unknown due became active');
-- COL-326 regression: a gated action's byte-identical retry must replay, never
-- raise a revision conflict. configure appends a 'configured' event and
-- corporate_expectation_revision() returns the newest event id, so the retry's
-- expected_revision is always stale by the time it is sent; retry identity is
-- enforced by request_hash, so it cannot carry a fresher one. Migration 376
-- refused this 40001 because its fast pre-read ran before the request-key
-- replay return, reporting a committed change as rejected. Only capture_meeting
-- and register had replay coverage, which is why that shipped green.
SAVEPOINT cd_gated_replay;
CREATE TEMP TABLE cd_gated_replay_payload AS SELECT s.task task,jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','recipient_label',NULL,'backup_label',NULL,'due_on',NULL,'configuration_provenance','Replay regression probe','due_provenance',NULL) payload FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date) d WHERE s.n=1;
SELECT pg_temp.cd_assert(NOT coalesce((public.corporate_deliverable_command(task,'col160-gated-replay-001','configure',payload)->>'replayed')::boolean,true),'first gated configure must not report a replay') FROM cd_gated_replay_payload;
SELECT pg_temp.cd_assert(coalesce((public.corporate_deliverable_command(task,'col160-gated-replay-001','configure',payload)->>'replayed')::boolean,false),'byte-identical gated retry must replay instead of raising a revision conflict') FROM cd_gated_replay_payload;
DROP TABLE cd_gated_replay_payload;
ROLLBACK TO SAVEPOINT cd_gated_replay;
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(s.task,'col160-missing-standup','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','stand_up','stand_up_week_start',s.start_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1$q$,'missing report remains missing');
SELECT public.stand_up_command('save',jsonb_build_object('facility_id',s.facility,'week_start',s.start_date,'expected_version',0,'request_id',gen_random_uuid(),'values',(SELECT jsonb_object_agg(k,1) FROM jsonb_object_keys(public.stand_up_command('export',jsonb_build_object('facility_id',s.facility,'week_start',s.start_date))->'values')k),'status','ready','as_of',s.end_date::text||'T12:00:00-04:00','reason','Synthetic immutable COL160 Stand Up source')) FROM cd_sites s WHERE n=1;
SELECT public.corporate_deliverable_command(s.task,'col160-standup-actual','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','stand_up','stand_up_week_start',s.start_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT public.corporate_deliverable_command(s.task,'col160-prepare-001','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','census')) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT public.corporate_deliverable_command(s.task,'col160-prepare-site2','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','census')) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=2;
SELECT pg_temp.cd_assert((SELECT pg_temp.cd_detail(task,facility,start_date,end_date)#>>'{current_state}'='prepared' FROM cd_sites WHERE n=1),'preparation changed external state');
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(s.task,'col160-sent-without-recipient','sent',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','channel','mail','source_evidence','operator ledger','sent_on',current_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1$q$,'Current recipient');

-- Capture before corrections. The stored meeting view stays byte-identical.
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(task,'col160-meeting-future','capture_meeting',jsonb_build_object('period_start',start_date,'period_end',end_date,'coverage_revision',(public.corporate_deliverable_snapshot(task,start_date,end_date)#>>'{coverage,revision}')::uuid,'presented_at',NULL,'presented_on',current_date+1,'presentation_provenance','Impossible future presentation')) FROM cd_sites WHERE n=1$q$,'Recorded date cannot be future');
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(task,'col160-meeting-no-offset','capture_meeting',jsonb_build_object('period_start',start_date,'period_end',end_date,'coverage_revision',(public.corporate_deliverable_snapshot(task,start_date,end_date)#>>'{coverage,revision}')::uuid,'presented_at','2026-08-05T12:00:00','presented_on',NULL,'presentation_provenance','Timestamp missing offset')) FROM cd_sites WHERE n=1$q$,'requires recorded offset');
CREATE TEMP TABLE cd_meeting_before AS SELECT public.corporate_deliverable_command(task,'col160-meeting-001','capture_meeting',jsonb_build_object('period_start',start_date,'period_end',end_date,'coverage_revision',(public.corporate_deliverable_snapshot(task,start_date,end_date)#>>'{coverage,revision}')::uuid,'presented_at',NULL,'presented_on',NULL,'presentation_provenance',NULL)) reply FROM cd_sites WHERE n=1;
CREATE TEMP TABLE cd_meeting_hash AS SELECT pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'meeting_hash' hash;
RESET ROLE;UPDATE public.census_daily_log SET occupied_beds=19,available_beds=1 WHERE id=(SELECT census FROM cd_sites WHERE n=1);SET LOCAL ROLE authenticated;
SELECT public.corporate_deliverable_command(s.task,'col160-prepare-002','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','census')) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
RESET ROLE;UPDATE public.census_daily_log SET occupied_beds=11,available_beds=9 WHERE id=(SELECT census FROM cd_sites WHERE n=1);SET LOCAL ROLE authenticated;
SELECT public.corporate_deliverable_command(s.task,'col160-prepare-003','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','census')) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT pg_temp.cd_assert((pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'site_versions')::integer=4,'Stand Up plus A to B to A correction chain collapsed');
SELECT pg_temp.cd_assert(pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'meeting_hash'=(SELECT hash FROM cd_meeting_hash),'old meeting view changed after correction');

-- Distinct operator-recorded lifecycle facts bind the exact latest version.
SELECT public.corporate_deliverable_command(s.task,'col160-configure-002','configure',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','recipient_label','Confirmed synthetic recipient','backup_label',NULL,'due_on',NULL,'configuration_provenance','Attributable synthetic controller decision','due_provenance',NULL)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT public.corporate_deliverable_command(s.task,'col160-sent-001','sent',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','channel','Operator-recorded postal mail','source_evidence','Synthetic mail register','sent_on',current_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(s.task,'col160-received-before-sent','received',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','channel','Bad sequence','source_evidence','Earlier date','received_on',current_date-1)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1$q$,'cannot precede sent');
SELECT public.corporate_deliverable_command(s.task,'col160-received-001','received',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','channel','Operator-recorded reply','source_evidence','Synthetic receipt register','received_on',current_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(s.task,'col160-accepted-before-received','accepted',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','approver_label','Bad order','source_evidence','Earlier approval','accepted_on',current_date-1)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1$q$,'cannot precede receipt');
SELECT public.corporate_deliverable_command(s.task,'col160-accepted-001','accepted',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','approver_label','Synthetic controller','source_evidence','Synthetic acceptance register','accepted_on',current_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT pg_temp.cd_assert((pg_temp.cd_private_stats((SELECT facility FROM cd_sites WHERE n=1))->>'state_kinds')::integer=4,'lifecycle states collapsed');
SELECT pg_temp.cd_assert((SELECT pg_temp.cd_detail(task,facility,start_date,end_date)#>>'{current_state}'='accepted' FROM cd_sites WHERE n=1),'accepted current state missing');
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(s.task,'col160-sent-regression','sent',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','channel','late entry','source_evidence','late register entry','sent_on',current_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1$q$,'cannot regress to sent');

-- A corrected version may be rejected only with an existing current-owned issue.
INSERT INTO cd_receipts SELECT 'issue',public.report_operation_issue_review('col160-issue-001',jsonb_build_object('task_instance_id',task,'kind','problem','summary','Correct rejected corporate packet','severity','normal')) FROM cd_sites WHERE n=1;
INSERT INTO cd_receipts SELECT 'assigned',public.assign_operation_issue_review((value#>>'{issue,id}')::uuid,'col160-issue-assign',(value#>>'{issue,issue_revision}'),jsonb_build_object('owner_user_id',(SELECT id FROM cd_actor),'note','Controller owns packet correction')) FROM cd_receipts WHERE name='issue';
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(s.task,'col160-reject-after-accept','rejected',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','reason','late rejection','issue_id',(SELECT value#>>'{issue,id}' FROM cd_receipts WHERE name='assigned'),'channel','late register','source_evidence','late rejection evidence','rejected_on',current_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1$q$,'terminal decision');
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(s.task,'col160-late-unknown-due','link_follow_up',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','problem_state','late','issue_id',(SELECT value#>>'{issue,id}' FROM cd_receipts WHERE name='assigned'))) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1$q$,'passed documented due date');
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(s.task,'col160-rejected-wrong-state','link_follow_up',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','problem_state','rejected','issue_id',(SELECT value#>>'{issue,id}' FROM cd_receipts WHERE name='assigned'))) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1$q$,'latest packet version to be rejected');
RESET ROLE;UPDATE public.census_daily_log SET occupied_beds=18,available_beds=2 WHERE id=(SELECT census FROM cd_sites WHERE n=1);SET LOCAL ROLE authenticated;
SELECT public.corporate_deliverable_command(s.task,'col160-prepare-rejected','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','census')) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT public.corporate_deliverable_command(s.task,'col160-sent-rejected','sent',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','channel','Operator-recorded portal handoff','source_evidence','Synthetic outbound register','sent_on',current_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT public.corporate_deliverable_command(s.task,'col160-received-rejected','received',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','channel','Operator-recorded reviewer return','source_evidence','Synthetic return register','received_on',current_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(s.task,'col160-rejected-before-received','rejected',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','reason','Bad order','issue_id',(SELECT value#>>'{issue,id}' FROM cd_receipts WHERE name='assigned'),'channel','Reviewer return','source_evidence','Earlier rejection','rejected_on',current_date-1)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1$q$,'cannot precede receipt');
SELECT public.corporate_deliverable_command(s.task,'col160-rejected-001','rejected',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','version_id',d->>'current_version_id','reason','Corporate reviewer found a source mismatch','issue_id',(SELECT value#>>'{issue,id}' FROM cd_receipts WHERE name='assigned'),'channel','Operator-recorded reviewer return','source_evidence','Synthetic rejection register','rejected_on',current_date)) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
SELECT pg_temp.cd_assert((SELECT pg_temp.cd_detail(task,facility,start_date,end_date)#>>'{current_state}'='rejected' AND pg_temp.cd_detail(task,facility,start_date,end_date)#>>'{follow_up,owner_current}'='true' AND pg_temp.cd_detail(task,facility,start_date,end_date)#>>'{follow_up,next_action}' IS NOT NULL FROM cd_sites WHERE n=1),'rejected version lost current owner or next action');
SELECT public.corporate_deliverable_command(s.task,'col160-rejected-link','link_follow_up',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','problem_state','rejected','issue_id',(SELECT value#>>'{issue,id}' FROM cd_receipts WHERE name='assigned'))) FROM cd_sites s,LATERAL pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date)d WHERE s.n=1;
INSERT INTO cd_receipts SELECT 'resolved',public.resolve_operation_issue_review((value#>>'{issue,id}')::uuid,'col160-issue-resolve',(value#>>'{issue,issue_revision}'),jsonb_build_object('resolution_summary','Synthetic packet corrected separately')) FROM cd_receipts WHERE name='assigned';
SELECT pg_temp.cd_assert((SELECT pg_temp.cd_detail(task,facility,start_date,end_date)#>>'{follow_up,status}'='resolved' AND EXISTS(SELECT 1 FROM jsonb_array_elements(pg_temp.cd_detail(task,facility,start_date,end_date)->'events')x WHERE x->>'kind'='rejected' AND x#>>'{details,owner_user_id}'=(SELECT id::text FROM cd_actor)) FROM cd_sites WHERE n=1),'post-resolution current issue state or immutable rejection ownership history missing');

-- Same-period resident deliverables have distinct coverage and meeting history.
RESET ROLE;
CREATE TEMP TABLE cd_residents AS SELECT n,gen_random_uuid() resident,gen_random_uuid() subject,NULL::uuid task FROM generate_series(1,2)n;GRANT ALL ON cd_residents TO authenticated;
CREATE TEMP TABLE cd_resident_trust AS SELECT gen_random_uuid() account,gen_random_uuid() movement;GRANT SELECT ON cd_resident_trust TO authenticated;
INSERT INTO public.residents(id,organization_id,facility_id,first_name,last_name,date_of_birth,gender) SELECT resident,(SELECT org FROM cd_actor),(SELECT facility FROM cd_sites WHERE n=1),'COL160','Resident '||n,'1940-01-01','female' FROM cd_residents;
INSERT INTO public.resident_trust_accounts(id,organization_id,facility_id,resident_id,balance_cents) SELECT t.account,(SELECT org FROM cd_actor),(SELECT facility FROM cd_sites WHERE n=1),(SELECT resident FROM cd_residents WHERE n=1),0 FROM cd_resident_trust t;
INSERT INTO public.resident_trust_transactions(id,organization_id,facility_id,resident_id,account_id,direction,amount_cents,balance_after_cents,description,occurred_at,created_by) SELECT t.movement,(SELECT org FROM cd_actor),(SELECT facility FROM cd_sites WHERE n=1),(SELECT resident FROM cd_residents WHERE n=1),t.account,'deposit',500,500,'Synthetic resident trust',((SELECT start_date FROM cd_sites WHERE n=1)::timestamp AT TIME ZONE 'America/New_York'),(SELECT id FROM cd_actor) FROM cd_resident_trust t;
INSERT INTO public.operation_activity_subjects(id,organization_id,facility_id,subject_kind,resident_id) SELECT subject,(SELECT org FROM cd_actor),(SELECT facility FROM cd_sites WHERE n=1),'resident',resident FROM cd_residents;
INSERT INTO public.operation_subject_access(organization_id,facility_id,user_id,scope,granted_by,reason,can_record) SELECT (SELECT org FROM cd_actor),(SELECT facility FROM cd_sites WHERE n=1),(SELECT id FROM cd_actor),'resident',(SELECT id FROM cd_actor),'Synthetic resident corporate scope',true;
SET LOCAL ROLE authenticated;
INSERT INTO cd_receipts VALUES('resident-rule',public.save_operation_requirement_draft_review((SELECT id FROM public.operation_activities WHERE organization_id=(SELECT org FROM cd_actor) AND activity_key='hfo-al-q01-01'),'{"title":"Synthetic trust statement","wording":"Prepare only after recipient confirmation","allowed_recorder_roles":["owner"],"subject_kind":"resident"}'));
SELECT public.publish_operation_requirement_review((SELECT (value->>'id')::uuid FROM cd_receipts WHERE name='resident-rule'),clock_timestamp()-interval '1 hour');
INSERT INTO cd_receipts VALUES('resident-site',public.save_operation_facility_requirement_draft_review((SELECT id FROM public.operation_activities WHERE organization_id=(SELECT org FROM cd_actor) AND activity_key='hfo-al-q01-01'),(SELECT facility FROM cd_sites WHERE n=1),jsonb_build_object('applicability','applicable','requirement_version_id',(SELECT value->>'id' FROM cd_receipts WHERE name='resident-rule'),'schedule_status','needs_confirmation')));
SELECT public.publish_operation_facility_requirement_review((SELECT (value->>'id')::uuid FROM cd_receipts WHERE name='resident-site'),clock_timestamp()-interval '30 minutes');
INSERT INTO cd_receipts SELECT 'resident-task-'||r.n,public.create_operation_manual_occurrence_review((SELECT id FROM public.operation_activities WHERE organization_id=(SELECT org FROM cd_actor) AND activity_key='hfo-al-q01-01'),(SELECT facility FROM cd_sites WHERE n=1),r.subject,'col160-resident-'||r.n,'{}') FROM cd_residents r;
UPDATE cd_residents r SET task=(x.value->>'id')::uuid FROM cd_receipts x WHERE x.name='resident-task-'||r.n;
SELECT public.corporate_deliverable_command(r.task,'col160-resident-register-'||r.n,'register',jsonb_build_object('period_start',s.start_date,'period_end',s.end_date,'period_provenance','Resident-specific trust statement '||r.n,'expected_facility_ids',jsonb_build_array(s.facility))) FROM cd_residents r,cd_sites s WHERE s.n=1;
SELECT pg_temp.cd_assert((SELECT count(DISTINCT public.corporate_deliverable_snapshot(r.task,s.start_date,s.end_date)#>>'{coverage,id}')=2 FROM cd_residents r,cd_sites s WHERE s.n=1),'cross-resident coverage identity collapsed');
SELECT public.corporate_deliverable_command(r.task,'col160-resident-meeting-'||r.n,'capture_meeting',jsonb_build_object('period_start',s.start_date,'period_end',s.end_date,'coverage_revision',public.corporate_deliverable_snapshot(r.task,s.start_date,s.end_date)#>>'{coverage,revision}','presented_at',NULL,'presented_on',NULL,'presentation_provenance',NULL)) FROM cd_residents r,cd_sites s WHERE s.n=1;
SELECT pg_temp.cd_assert((SELECT bool_and(jsonb_array_length(public.corporate_deliverable_snapshot(r.task,s.start_date,s.end_date)->'meetings')=1) FROM cd_residents r,cd_sites s WHERE s.n=1),'cross-resident meeting history leaked or disappeared');
SELECT public.corporate_deliverable_command(r.task,'col160-resident-configure','configure',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','recipient_label','Confirmed resident-one recipient','backup_label',NULL,'due_on',NULL,'configuration_provenance','Synthetic attributable recipient source','due_provenance',NULL)) FROM cd_residents r,cd_sites s,LATERAL pg_temp.cd_detail(r.task,s.facility,s.start_date,s.end_date)d WHERE r.n=1 AND s.n=1;
SELECT public.corporate_deliverable_command(r.task,'col160-resident-trust','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','trust')) FROM cd_residents r,cd_sites s,LATERAL pg_temp.cd_detail(r.task,s.facility,s.start_date,s.end_date)d WHERE r.n=1 AND s.n=1;
RESET ROLE;UPDATE public.operation_subject_access SET revoked_at=clock_timestamp() WHERE user_id=(SELECT id FROM cd_actor) AND facility_id=(SELECT facility FROM cd_sites WHERE n=1) AND scope='financial';SET LOCAL ROLE authenticated;
SELECT pg_temp.cd_assert((SELECT public.corporate_deliverable_snapshot(r.task,s.start_date,s.end_date)->>'availability'='unavailable' FROM cd_residents r,cd_sites s WHERE r.n=1 AND s.n=1),'revoked financial scope leaked historical trust payload');
RESET ROLE;UPDATE public.operation_subject_access SET revoked_at=NULL WHERE user_id=(SELECT id FROM cd_actor) AND facility_id=(SELECT facility FROM cd_sites WHERE n=1) AND scope='financial';SET LOCAL ROLE authenticated;

-- Remaining exact component mappings: M09-03 trust is usable; FPC and C08
-- remain scoped unavailable rather than accepting an invented subject/type.
RESET ROLE;CREATE TEMP TABLE cd_components(key text PRIMARY KEY,subject uuid,subject_kind text,task uuid);GRANT ALL ON cd_components TO authenticated;
INSERT INTO cd_components VALUES('hfo-al-m09-03',(SELECT subject FROM cd_sites WHERE n=1),'facility',NULL),('hfo-al-c08-01',(SELECT subject FROM cd_residents WHERE n=1),'resident',NULL);
SET LOCAL ROLE authenticated;
INSERT INTO cd_receipts SELECT 'component-rule-'||key,public.save_operation_requirement_draft_review((SELECT id FROM public.operation_activities WHERE organization_id=(SELECT org FROM cd_actor) AND activity_key=c.key),jsonb_build_object('title','Synthetic '||c.key,'wording','Exact COL160 mapping proof','allowed_recorder_roles',jsonb_build_array('owner'),'subject_kind',c.subject_kind)) FROM cd_components c;
SELECT public.publish_operation_requirement_review((value->>'id')::uuid,clock_timestamp()-interval '1 hour') FROM cd_receipts WHERE name LIKE 'component-rule-%';
INSERT INTO cd_receipts SELECT 'component-site-'||key,public.save_operation_facility_requirement_draft_review((SELECT id FROM public.operation_activities WHERE organization_id=(SELECT org FROM cd_actor) AND activity_key=c.key),(SELECT facility FROM cd_sites WHERE n=1),jsonb_build_object('applicability','applicable','requirement_version_id',(SELECT value->>'id' FROM cd_receipts WHERE name='component-rule-'||c.key),'schedule_status','needs_confirmation')) FROM cd_components c;
SELECT public.publish_operation_facility_requirement_review((value->>'id')::uuid,clock_timestamp()-interval '30 minutes') FROM cd_receipts WHERE name LIKE 'component-site-%';
INSERT INTO cd_receipts SELECT 'component-task-'||key,public.create_operation_manual_occurrence_review((SELECT id FROM public.operation_activities WHERE organization_id=(SELECT org FROM cd_actor) AND activity_key=c.key),(SELECT facility FROM cd_sites WHERE n=1),c.subject,'col160-component-'||right(c.key,6),'{}') FROM cd_components c;
UPDATE cd_components c SET task=(r.value->>'id')::uuid FROM cd_receipts r WHERE r.name='component-task-'||c.key;
SELECT public.corporate_deliverable_command(c.task,'col160-map-'||right(c.key,6),'register',jsonb_build_object('period_start',s.start_date,'period_end',s.end_date,'period_provenance','Exact component mapping source','expected_facility_ids',jsonb_build_array(s.facility))) FROM cd_components c,cd_sites s WHERE s.n=1;
SELECT pg_temp.cd_assert((SELECT bool_and((key='hfo-al-m09-03')=(pg_temp.cd_detail(task,(SELECT facility FROM cd_sites WHERE n=1),(SELECT start_date FROM cd_sites WHERE n=1),(SELECT end_date FROM cd_sites WHERE n=1))#>>'{mapping_state}'='mapped')) FROM cd_components) AND (SELECT subject_kind IS NULL FROM public.operation_activities WHERE organization_id=(SELECT org FROM cd_actor) AND activity_key='hfo-al-m09-02'),'FPC activation, C08 classification or M09-03 mapped state changed');
SELECT public.corporate_deliverable_command(c.task,'col160-m09-03-trust','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','trust')) FROM cd_components c,cd_sites s,LATERAL pg_temp.cd_detail(c.task,s.facility,s.start_date,s.end_date)d WHERE c.key='hfo-al-m09-03' AND s.n=1;
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(c.task,'col160-m09-03-wrong','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','census')) FROM cd_components c,cd_sites s,LATERAL pg_temp.cd_detail(c.task,s.facility,s.start_date,s.end_date)d WHERE c.key='hfo-al-m09-03' AND s.n=1$q$,'does not match');
SELECT pg_temp.cd_error($q$SELECT public.corporate_deliverable_command(c.task,'col160-c08-unconfirmed','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','resident_document','native_version_id',gen_random_uuid())) FROM cd_components c,cd_sites s,LATERAL pg_temp.cd_detail(c.task,s.facility,s.start_date,s.end_date)d WHERE c.key='hfo-al-c08-01' AND s.n=1$q$,'Unconfirmed component');

-- Command-only immutable history and current native authority.
SELECT pg_temp.cd_error($q$INSERT INTO haven.corporate_submission_events(expectation_id,task_id,kind,details,sequence,actor_id,recorded_at) SELECT id,origin_task_id,'accepted','{}',999,(SELECT id FROM cd_actor),clock_timestamp() FROM haven.corporate_submission_expectations LIMIT 1$q$,'permission denied');
RESET ROLE;REVOKE SELECT ON public.census_daily_log FROM authenticated;SET LOCAL ROLE authenticated;
SELECT pg_temp.cd_assert((SELECT public.corporate_deliverable_snapshot(task,start_date,end_date)->>'availability'='unavailable' AND public.corporate_deliverable_snapshot(task,start_date,end_date)->>'coverage_complete'='false' FROM cd_sites WHERE n=1),'native revocation returned stale detailed coverage');
RESET ROLE;GRANT SELECT ON public.census_daily_log TO authenticated;SET LOCAL ROLE authenticated;
INSERT INTO cd_receipts SELECT 'new-source-task',public.create_operation_manual_occurrence_review((SELECT id FROM public.operation_activities WHERE organization_id=s.org AND activity_key='hfo-al-m09-01'),s.facility,s.subject,'col160-new-source-task','{}') FROM cd_sites s WHERE s.n=1;
RESET ROLE;UPDATE public.census_daily_log SET occupied_beds=16,available_beds=4 WHERE id=(SELECT census FROM cd_sites WHERE n=1);SET LOCAL ROLE authenticated;
SELECT public.corporate_deliverable_command((SELECT (value->>'id')::uuid FROM cd_receipts WHERE name='new-source-task'),'col160-new-source-version','prepare',jsonb_build_object('expectation_id',d->>'id','expected_revision',d->>'revision','source_family','census')) FROM cd_sites s,LATERAL pg_temp.cd_detail((SELECT (value->>'id')::uuid FROM cd_receipts WHERE name='new-source-task'),s.facility,s.start_date,s.end_date)d WHERE s.n=1;

-- Independent stream cursors retrieve every older payload exactly once.
RESET ROLE;SELECT set_config('haven.corporate_deliverable_command',haven.corporate_deliverable_token(),true);
INSERT INTO haven.corporate_submission_versions(expectation_id,task_id,version,source_family,source_version,captured,prepared_by,prepared_at)
 SELECT e.id,s.task,g.num,'census',encode(sha256(convert_to(g.num::text,'UTF8')),'hex'),jsonb_build_object('fixture_version',g.num),(SELECT id FROM cd_actor),clock_timestamp() FROM cd_sites s JOIN haven.corporate_submission_expectations e ON e.facility_id=s.facility AND e.component_key='hfo-al-m09-01' CROSS JOIN generate_series(2,21)g(num) WHERE s.n=2;
INSERT INTO haven.corporate_submission_events(expectation_id,task_id,kind,version_id,details,sequence,actor_id,recorded_at)
 SELECT e.id,s.task,'configured',NULL,jsonb_build_object('fixture_event',g.num),g.num,(SELECT id FROM cd_actor),clock_timestamp() FROM cd_sites s JOIN haven.corporate_submission_expectations e ON e.facility_id=s.facility AND e.component_key='hfo-al-m09-01' CROSS JOIN generate_series(2,55)g(num) WHERE s.n=2;
SELECT set_config('haven.corporate_deliverable_command','',true);
CREATE TEMP TABLE cd_paged_versions(id uuid PRIMARY KEY);CREATE TEMP TABLE cd_paged_events(id uuid PRIMARY KEY);GRANT ALL ON cd_paged_versions,cd_paged_events TO authenticated;SET LOCAL ROLE authenticated;
DO $$ DECLARE s cd_sites;d jsonb;page jsonb;version_cursor integer;event_cursor bigint;BEGIN SELECT * INTO s FROM cd_sites WHERE n=2;d:=pg_temp.cd_detail(s.task,s.facility,s.start_date,s.end_date);PERFORM pg_temp.cd_assert(jsonb_array_length(d->'versions')=1 AND d#>>'{versions,0,version}'='21' AND d#>>'{history_cursor,before_version}'='21','live current-version page lost exact cursor');version_cursor:=(d#>>'{history_cursor,before_version}')::integer;event_cursor:=(d#>>'{history_cursor,before_sequence}')::bigint;
 WHILE version_cursor<>0 OR event_cursor<>0 LOOP page:=public.corporate_deliverable_history(s.task,(d->>'id')::uuid,version_cursor,event_cursor);INSERT INTO cd_paged_versions SELECT (x->>'id')::uuid FROM jsonb_array_elements(page->'versions')x ON CONFLICT DO NOTHING;INSERT INTO cd_paged_events SELECT (x->>'id')::uuid FROM jsonb_array_elements(page->'events')x ON CONFLICT DO NOTHING;version_cursor:=(page->>'next_before_version')::integer;event_cursor:=(page->>'next_before_sequence')::bigint;END LOOP;
 PERFORM pg_temp.cd_assert((SELECT count(*)=20 FROM cd_paged_versions) AND (SELECT count(*)=5 FROM cd_paged_events),'unequal version/event pages restarted, skipped or duplicated an exhausted stream');END $$;

SELECT public.resolve_operation_issue_review((value#>>'{issue,id}')::uuid,'col160-retire-race-issue-'||name,(value#>>'{issue,issue_revision}'),jsonb_build_object('resolution_summary','Retire synthetic old-task fixture')) FROM cd_receipts WHERE name IN('race-assigned','race-assigned-two');
SELECT public.cancel_operation_occurrence_review((SELECT task FROM cd_sites WHERE n=1),'Retire old synthetic source task','col160-retire-old-task',true);
SELECT pg_temp.cd_assert((SELECT public.corporate_deliverable_snapshot((SELECT (value->>'id')::uuid FROM cd_receipts WHERE name='new-source-task'),start_date,end_date)->>'availability'='unavailable' FROM cd_sites WHERE n=1),'unreadable old source task leaked historical versions');

SELECT 'COL160 corporate deliverables primary PASS' result;
ROLLBACK;
