import React from "react";
import { createRoot } from "react-dom/client";
import "../../src/app/globals.css";
import { WorkforceContext } from "../../src/components/workforce/WorkforceContext";
import { WorkforcePage } from "../../src/components/workforce/WorkforcePage";
import { useFacilityStore } from "../../src/hooks/useFacilityStore";
const id = "11111111-1111-4111-8111-111111111111";
useFacilityStore.setState({ selectedFacilityId: id, availableFacilities: [{ id, name: "Synthetic test building" }] });
const query = new URLSearchParams(window.location.search).get("view");
const view = query === "people" || query === "timecards" ? query : "today";
createRoot(document.getElementById("root")!).render(<div className="min-h-screen bg-background text-foreground"><header className="flex flex-wrap items-center gap-6 border-b px-6 py-4"><strong>Haven</strong><span>Synthetic test building</span><strong>Workforce</strong><span className="ml-auto text-xs text-muted-foreground">Synthetic data · component verification</span></header><div className="flex"><aside className="hidden min-h-screen w-60 shrink-0 bg-[#26282c] p-4 text-white lg:block">{["today", "schedule", "timecards", "payroll", "people"].map((item) => <a key={item} className={`mb-2 block rounded-xl px-3 py-3 text-sm capitalize ${item === view ? "bg-white/15" : "text-white/70"}`} href={`/?view=${item}`}>{item}</a>)}</aside><main className="min-w-0 flex-1 p-5 lg:p-7"><WorkforceContext><WorkforcePage view={view}/></WorkforceContext></main></div></div>);
