import { beforeEach, expect, it, vi } from "vitest";
import { NextRequest, NextResponse } from "next/server";
vi.mock('@/lib/operations/auth',()=>({requireOperationsActor:vi.fn(),revalidateOperationsActor:vi.fn(),actorCanAccessFacility:vi.fn()}));
vi.mock('@/lib/operations/facility-profile-server',()=>({readFacilityProfile:vi.fn()}));
import {requireOperationsActor,revalidateOperationsActor,actorCanAccessFacility} from '@/lib/operations/auth';
import {readFacilityProfile} from '@/lib/operations/facility-profile-server';
import {GET,POST} from './route';
import {POST as prepare} from './drafts/route';
import {activityCatalog} from '@/lib/operations/activity-catalog';
const id='00000000-0000-0000-0002-000000000003';const rpc=vi.fn();const actor={id:'actor',organizationId:'org',appRole:'owner',currentActor:{client:{rpc}}};
const reply={facility:{id},coverage:{source_count:91,component_count:110,mapping_unknown_count:11},entries:[],complete:true};
const get=()=>GET(new NextRequest('https://local.test/api/admin/operations/facility-profile?facility_id='+id));
const request=(body:unknown)=>new Request('https://local.test',{method:'POST',body:JSON.stringify(body)});
beforeEach(()=>{vi.resetAllMocks();vi.mocked(requireOperationsActor).mockResolvedValue({actor} as never);vi.mocked(revalidateOperationsActor).mockResolvedValue({actor} as never);vi.mocked(actorCanAccessFacility).mockResolvedValue(true);vi.mocked(readFacilityProfile).mockResolvedValue(reply as never)});
it('returns authenticated complete profile with no-store',async()=>{const r=await get();expect(r.status).toBe(200);expect(await r.json()).toEqual(reply);expect(r.headers.get('cache-control')).toBe('no-store')});
it('rejects site revocation during read without returning any profile',async()=>{vi.mocked(actorCanAccessFacility).mockResolvedValueOnce(true).mockResolvedValueOnce(false);const r=await get();expect(r.status).toBe(404);expect(await r.json()).not.toHaveProperty('entries')});
it('rejects source changes or later-read failure instead of silent partial coverage',async()=>{vi.mocked(readFacilityProfile).mockResolvedValueOnce(reply as never).mockRejectedValueOnce(Error('late page'));expect((await get()).status).toBe(503);vi.mocked(readFacilityProfile).mockResolvedValueOnce(reply as never).mockResolvedValueOnce({...reply,complete:false} as never);expect((await get()).status).toBe(503)});
it('does not let a client claim an approval through validation',async()=>{const r=await POST(request({facility_id:id,activity_id:activityCatalog.entries[0].components[0].id,provenance:{source:'Claim',answer_id:'Q14',approver_id:id,effective_from:'2026-09-14T00:00:00Z'},payload:{schedule_status:'needs_confirmation'}}));expect(await r.json()).toMatchObject({valid:false,activated:false,imported:false});expect(rpc).not.toHaveBeenCalled()});
it('prepares all components only through the authenticated preserving RPC',async()=>{const results=activityCatalog.entries.flatMap(e=>e.components.map(c=>({activity_id:c.id,central:'prepared',facility:'prepared'})));rpc.mockResolvedValue({data:{prepared:110,preserved:0,unresolved:0,results},error:null});const r=await prepare(request({facility_id:id}));expect(r.status).toBe(200);expect(rpc).toHaveBeenCalledWith('prepare_operation_profile_drafts',{p_facility:id})});
it('refuses malformed inputs, denied actors and incomplete preparation success',async()=>{expect((await prepare(request({facility_id:id,payload:{approve:true}}))).status).toBe(400);expect(rpc).not.toHaveBeenCalled();rpc.mockResolvedValue({data:{prepared:1,preserved:0,unresolved:0,results:[{activity_id:id}]},error:null});expect((await prepare(request({facility_id:id}))).status).toBe(503);vi.mocked(requireOperationsActor).mockResolvedValue({response:NextResponse.json({}, {status:403})});expect((await prepare(request({facility_id:id}))).status).toBe(403)});
