import type { OnboardingQuestion } from "@/lib/onboarding/types";

/**
 * Second-wave discovery: moved from former "core" list plus net-new extended prompts.
 * Sort order 1–12 = migrated; 13–58 = new discovery areas.
 */
export const EXTENDED_DISCOVERY_QUESTIONS: OnboardingQuestion[] = [
  {
    id: "extended.ops.housekeeping",
    tier: "extended",
    sortOrder: 1,
    prompt: "Describe housekeeping and maintenance request flows (submit → assign → verify complete).",
    helpText:
      "Environmental issues affect falls, infection control, and satisfaction—mapping reduces blind spots.",
    assignedTo: "Maintenance",
    department: "Maintenance / Facilities",
    category: "operations",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.hr.turnover",
    tier: "extended",
    sortOrder: 2,
    prompt: "What is typical staff turnover and float patterns that could affect super-user availability?",
    helpText:
      "Churn changes who holds institutional knowledge—plan champions accordingly.",
    assignedTo: "HR",
    department: "HR / Workforce",
    category: "training",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.expansion.multi-site",
    tier: "extended",
    sortOrder: 3,
    prompt: "What is the roadmap for adding facilities/entities after pilot (standards, governance, timelines)?",
    helpText:
      "Multi-site patterns affect configuration, roles, and reporting design early.",
    assignedTo: "President",
    department: "Executive / Ownership",
    category: "governance",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.sales.marketing",
    tier: "extended",
    sortOrder: 4,
    prompt: "What CRM or lead tracking is used for inquiries and move-ins, and who owns the pipeline metrics?",
    helpText:
      "Admissions workflows connect to census and revenue—avoid duplicate entry and dropped leads.",
    assignedTo: "Sales / Admissions",
    department: "Sales / Admissions",
    category: "operations",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.broker.relations",
    tier: "extended",
    sortOrder: 5,
    prompt: "Are broker or referral relationships material to census—and what data must stay out of general staff view?",
    helpText:
      "Sensitive commercial relationships need role separation and clean permissions.",
    assignedTo: "CEO",
    department: "Executive / Ownership",
    category: "governance",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.integrations.lab",
    tier: "extended",
    sortOrder: 6,
    prompt: "What lab, imaging, or external clinical integrations exist (or are planned) and who owns them?",
    helpText:
      "Integration ownership prevents orphaned interfaces and unsafe manual workarounds.",
    assignedTo: "IT",
    department: "IT / Devices",
    category: "infrastructure",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.policies.source",
    tier: "extended",
    sortOrder: 7,
    prompt: "Where is the authoritative policy manual stored today, and how often is it updated?",
    helpText:
      "Policy sources anchor training content and in-app guardrails.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "compliance",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.contracts.key",
    tier: "extended",
    sortOrder: 8,
    prompt: "What key managed care or payer contracts constrain billing workflows or authorizations?",
    helpText:
      "Payer rules change prior auth and billing steps—surface constraints early.",
    assignedTo: "CFO",
    department: "Finance",
    category: "reporting",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.ops.transportation",
    tier: "extended",
    sortOrder: 9,
    prompt: "How are transportation and appointments scheduled, tracked, and billed (if applicable)?",
    helpText:
      "Transport touches liability, resident experience, and staffing—don’t treat it as an afterthought.",
    assignedTo: "COO",
    department: "Operations",
    category: "operations",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.ops.facility-assets",
    tier: "extended",
    sortOrder: 10,
    prompt: "What facility maintenance and capital projects are planned during the pilot window?",
    helpText:
      "Construction and network changes can invalidate training and connectivity assumptions.",
    assignedTo: "Maintenance",
    department: "Maintenance / Facilities",
    category: "operations",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.pilot.success-story",
    tier: "extended",
    sortOrder: 11,
    prompt: "What does “success” look like for staff on the floor 90 days after go-live (one paragraph)?",
    helpText:
      "A concrete staff-level success picture keeps UX and training grounded in reality.",
    assignedTo: "COO",
    department: "Operations",
    category: "pilot",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.governance.open-questions",
    tier: "extended",
    sortOrder: 12,
    prompt: "What unanswered questions or risks should the implementation team track as explicit follow-ups?",
    helpText:
      "Capture unknowns so they become tasks instead of hidden assumptions.",
    assignedTo: "All leadership",
    department: "Executive / Ownership",
    category: "governance",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.software.resident-records",
    tier: "extended",
    sortOrder: 13,
    prompt: "What system is the source of truth for resident clinical and demographic records today (vendor, version, hosting)?",
    helpText:
      "Resident data lineage drives migration scope and integration design.",
    assignedTo: "IT",
    department: "IT / Devices",
    category: "systems",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.software.emar",
    tier: "extended",
    sortOrder: 14,
    prompt: "Describe the eMAR / medication administration system in use (or paper process) and who administers it.",
    helpText:
      "Med tech choices affect safety checks, pharmacy interfaces, and training.",
    assignedTo: "Director of Nursing",
    department: "Clinical / Resident Care",
    category: "systems",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.software.billing-ar",
    tier: "extended",
    sortOrder: 15,
    prompt: "What billing and accounts receivable system(s) are used (per entity or shared), and who owns each?",
    helpText:
      "AR stack drives integrations, statements, and trust accounting.",
    assignedTo: "CFO",
    department: "Finance",
    category: "systems",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.software.incident-reporting",
    tier: "extended",
    sortOrder: 16,
    prompt: "What tool or process is used for internal incident reporting and RCA today (outside of regulatory portals)?",
    helpText:
      "Incident tooling affects timelines, notifications, and analytics.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "systems",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.software.scheduling-staffing",
    tier: "extended",
    sortOrder: 17,
    prompt: "What scheduling and staffing systems are in use (nursing, dietary, maintenance) and how do they integrate with payroll?",
    helpText:
      "Scheduling integrations affect ratios, overtime, and time clocks.",
    assignedTo: "HR",
    department: "HR / Workforce",
    category: "systems",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.software.family-comms",
    tier: "extended",
    sortOrder: 18,
    prompt: "What tools are used for family communication (calls, email, texting apps, portal) and who sends from each?",
    helpText:
      "Channel sprawl affects consent, documentation, and satisfaction.",
    assignedTo: "Executive Director",
    department: "Family / Communications",
    category: "systems",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.software.admissions-census",
    tier: "extended",
    sortOrder: 19,
    prompt: "How are admissions pipeline and census tracked today (CRM, spreadsheet, EHR module)?",
    helpText:
      "Census truth drives revenue recognition and capacity planning.",
    assignedTo: "Sales / Admissions",
    department: "Sales / Admissions",
    category: "systems",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.software.accounting-gl",
    tier: "extended",
    sortOrder: 20,
    prompt: "What general ledger / accounting system is used at the entity level, and is it consolidated across facilities?",
    helpText:
      "GL boundaries affect intercompany, allocations, and reporting.",
    assignedTo: "CFO",
    department: "Finance",
    category: "systems",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.software.payroll-timekeeping",
    tier: "extended",
    sortOrder: 21,
    prompt: "List payroll and timekeeping vendors per entity (or enterprise), including mobile clock rules.",
    helpText:
      "Payroll integrations are high-risk during cutover.",
    assignedTo: "CFO",
    department: "Finance",
    category: "systems",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.vendor.pharmacy-detail",
    tier: "extended",
    sortOrder: 22,
    prompt: "Who is the primary pharmacy vendor per facility, and how are orders, deliveries, and errors escalated?",
    helpText:
      "Pharmacy interfaces are clinical-critical and heavily regulated.",
    assignedTo: "Director of Nursing",
    department: "Clinical / Resident Care",
    category: "vendors",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.vendor.lab-imaging-telehealth",
    tier: "extended",
    sortOrder: 23,
    prompt: "Which lab, imaging, and telehealth vendors are under contract, and how are orders and results routed?",
    helpText:
      "External clinical data paths affect orders, results, and billing.",
    assignedTo: "IT",
    department: "IT / Devices",
    category: "vendors",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.vendor.nurse-call-alerts",
    tier: "extended",
    sortOrder: 24,
    prompt: "What nurse call, pendant, or wander alert systems are installed, and who responds after hours?",
    helpText:
      "Alert infrastructure ties to life safety and liability.",
    assignedTo: "Maintenance",
    department: "Maintenance / Facilities",
    category: "vendors",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.vendor.outside-billing-rcm",
    tier: "extended",
    sortOrder: 25,
    prompt: "Is any billing or revenue cycle management outsourced? Describe scope and SLAs.",
    helpText:
      "RCM handoffs affect claims, denials, and family statements.",
    assignedTo: "CFO",
    department: "Finance",
    category: "vendors",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.vendor.it-msp-detail",
    tier: "extended",
    sortOrder: 26,
    prompt: "Who is the IT managed service provider (if any), what do they manage, and how are after-hours escalations handled?",
    helpText:
      "MSP boundaries affect access, patching, and incident response.",
    assignedTo: "IT",
    department: "IT / Devices",
    category: "vendors",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.vendor.outsourced-services",
    tier: "extended",
    sortOrder: 27,
    prompt: "Which services are fully outsourced (laundry, dietary prep, housekeeping, transportation) and how are they supervised?",
    helpText:
      "Outsourced lanes still need accountability in the platform.",
    assignedTo: "COO",
    department: "Operations",
    category: "vendors",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.facility.staffing-model-diffs",
    tier: "extended",
    sortOrder: 28,
    prompt: "How does staffing model differ by facility (ratios, agency use, PD shifts)?",
    helpText:
      "Per-site staffing reality affects scheduling rules and alerts.",
    assignedTo: "COO",
    department: "Operations",
    category: "facilities",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.facility.connectivity-hardware-diffs",
    tier: "extended",
    sortOrder: 29,
    prompt: "Where do connectivity, devices, or hardware differ materially by facility?",
    helpText:
      "Uneven tech stacks break one-size-fits-all rollouts.",
    assignedTo: "IT",
    department: "IT / Devices",
    category: "facilities",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.facility.licensure-care-mix",
    tier: "extended",
    sortOrder: 30,
    prompt: "How does licensure, memory care mix, or specialty populations differ by facility?",
    helpText:
      "Care mix changes workflows, assessments, and compliance surfaces.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "facilities",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.facility.administrator-workflows",
    tier: "extended",
    sortOrder: 31,
    prompt: "How do administrator daily workflows differ by facility (approvals, rounds, family contact)?",
    helpText:
      "Local admin habits drive adoption and permissions.",
    assignedTo: "COO",
    department: "Operations",
    category: "facilities",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.facility.pilot-site",
    tier: "extended",
    sortOrder: 32,
    prompt: "Which facility is the best pilot site and why (readiness, leadership, tech, census stability)?",
    helpText:
      "Pilot site selection de-risks the first go-live.",
    assignedTo: "President",
    department: "Executive / Ownership",
    category: "pilot",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.lifecycle.admissions-steps",
    tier: "extended",
    sortOrder: 33,
    prompt: "List the concrete admissions steps from inquiry to move-in, including approvals and paperwork owners.",
    helpText:
      "Admissions sequencing drives CRM, assessments, and bed management.",
    assignedTo: "Sales / Admissions",
    department: "Sales / Admissions",
    category: "lifecycle",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.lifecycle.move-in-paperwork",
    tier: "extended",
    sortOrder: 34,
    prompt: "What move-in paperwork packets are required and where do signed copies live?",
    helpText:
      "Document control affects compliance and family disputes.",
    assignedTo: "Sales / Admissions",
    department: "Sales / Admissions",
    category: "lifecycle",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.lifecycle.discharge-transfer",
    tier: "extended",
    sortOrder: 35,
    prompt: "Describe discharge and transfer workflows (hospital return, hospice, another community).",
    helpText:
      "Transitions are high-risk for medication and billing errors.",
    assignedTo: "Director of Nursing",
    department: "Clinical / Resident Care",
    category: "lifecycle",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.lifecycle.census-management",
    tier: "extended",
    sortOrder: 36,
    prompt: "Who owns census changes (bed holds, LOA, hospital holds) and how often is census reconciled to billing?",
    helpText:
      "Census drift breaks AR and staffing plans.",
    assignedTo: "CFO",
    department: "Finance",
    category: "lifecycle",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.lifecycle.room-bed-logic",
    tier: "extended",
    sortOrder: 37,
    prompt: "How are rooms, beds, and level-of-care locations assigned and updated?",
    helpText:
      "Bed logic ties to acuity billing and fire safety.",
    assignedTo: "COO",
    department: "Operations",
    category: "lifecycle",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.lifecycle.pricing-model",
    tier: "extended",
    sortOrder: 38,
    prompt: "How is resident pricing structured (base rate, care levels, ancillary bundles)?",
    helpText:
      "Pricing models drive rate tables and statements.",
    assignedTo: "CFO",
    department: "Finance",
    category: "revenue",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.lifecycle.loc-pricing",
    tier: "extended",
    sortOrder: 39,
    prompt: "How does level-of-care or acuity pricing work in practice (assessment triggers, rate changes)?",
    helpText:
      "LOC pricing connects clinical assessments to finance.",
    assignedTo: "CFO",
    department: "Finance",
    category: "revenue",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.lifecycle.ancillary-charges",
    tier: "extended",
    sortOrder: 40,
    prompt: "What ancillary charges exist (salon, transport, supplies) and how are they authorized and posted?",
    helpText:
      "Ancillary leakage affects satisfaction and AR.",
    assignedTo: "CFO",
    department: "Finance",
    category: "revenue",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.lifecycle.collections",
    tier: "extended",
    sortOrder: 41,
    prompt: "Describe collections workflow for private pay and third-party payers (roles, scripts, write-offs).",
    helpText:
      "Collections touch regulated communications and trust rules.",
    assignedTo: "CFO",
    department: "Finance",
    category: "revenue",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.lifecycle.payer-mix",
    tier: "extended",
    sortOrder: 42,
    prompt: "Summarize payer mix, Medicaid waiver usage, hospice transitions, and long-term care insurance handling.",
    helpText:
      "Payer complexity drives claims workflows and reporting.",
    assignedTo: "CFO",
    department: "Finance",
    category: "revenue",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.family.top-complaints",
    tier: "extended",
    sortOrder: 43,
    prompt: "What are the top recurring family complaints today, and how are they tracked?",
    helpText:
      "Complaint themes inform portal design and service recovery.",
    assignedTo: "Executive Director",
    department: "Family / Communications",
    category: "family",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.family.who-communicates",
    tier: "extended",
    sortOrder: 44,
    prompt: "Who is allowed to communicate clinical vs financial information to families, and how is that enforced?",
    helpText:
      "Role clarity reduces HIPAA issues and family confusion.",
    assignedTo: "Compliance",
    department: "Family / Communications",
    category: "family",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.family.portal-exposure",
    tier: "extended",
    sortOrder: 45,
    prompt: "What information should never be exposed in a family portal or automated message?",
    helpText:
      "Hard boundaries prevent harmful disclosures.",
    assignedTo: "Compliance",
    department: "Family / Communications",
    category: "family",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.family.portal-adoption",
    tier: "extended",
    sortOrder: 46,
    prompt: "What is leadership’s appetite for family portal adoption (targets, support model, languages)?",
    helpText:
      "Adoption assumptions drive training and support staffing.",
    assignedTo: "COO",
    department: "Family / Communications",
    category: "family",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.family.care-conference-escalation",
    tier: "extended",
    sortOrder: 47,
    prompt: "How are care conferences and formal complaints or legal escalations handled today?",
    helpText:
      "Escalation paths affect documentation and notifications.",
    assignedTo: "Executive Director",
    department: "Family / Communications",
    category: "family",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.legal.baa-status",
    tier: "extended",
    sortOrder: 48,
    prompt: "What is the status of Business Associate Agreements with key vendors and cloud services?",
    helpText:
      "BAA gaps block compliant data sharing.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "legal",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.legal.phi-handling",
    tier: "extended",
    sortOrder: 49,
    prompt: "What are explicit PHI handling expectations for email, texting, fax, and shared drives?",
    helpText:
      "Channel policy must match how staff actually work.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "legal",
    importance: "high",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.legal.covered-entity",
    tier: "extended",
    sortOrder: 50,
    prompt: "How is covered entity vs business associate responsibility allocated across entities and vendors?",
    helpText:
      "Structure affects contracts and breach response.",
    assignedTo: "CEO",
    department: "Executive / Ownership",
    category: "legal",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.legal.data-ownership",
    tier: "extended",
    sortOrder: 51,
    prompt: "Who owns operational and clinical data at exit (operator vs vendor vs owner), and what export rights exist?",
    helpText:
      "Data ownership affects contract terms and migration.",
    assignedTo: "CEO",
    department: "Executive / Ownership",
    category: "legal",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.legal.export-ip",
    tier: "extended",
    sortOrder: 52,
    prompt: "What are expectations for data export, reporting IP, and customization ownership at contract end?",
    helpText:
      "Export/IP clauses affect build-vs-buy and customization.",
    assignedTo: "CEO",
    department: "Executive / Ownership",
    category: "legal",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.legal.retention-hold",
    tier: "extended",
    sortOrder: 53,
    prompt: "Beyond baseline retention, what legal hold or litigation workflows exist that affect records?",
    helpText:
      "Holds change what can be deleted or archived.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "legal",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.product.command-center-metrics",
    tier: "extended",
    sortOrder: 54,
    prompt: "What command-center metrics does leadership want on day one vs within 12 months post go-live?",
    helpText:
      "Metric phasing prevents dashboard overload at launch.",
    assignedTo: "COO",
    department: "Executive / Ownership",
    category: "product",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.product.cross-facility",
    tier: "extended",
    sortOrder: 55,
    prompt: "What cross-facility comparisons are required (benchmarks, rankings, variance thresholds)?",
    helpText:
      "Comparisons affect permissions and data model.",
    assignedTo: "President",
    department: "Executive / Ownership",
    category: "product",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.product.multi-entity-expansion",
    tier: "extended",
    sortOrder: 56,
    prompt: "What are expectations for adding entities, brands, or management contracts after pilot?",
    helpText:
      "Expansion assumptions shape tenancy and reporting.",
    assignedTo: "CEO",
    department: "Executive / Ownership",
    category: "product",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.product.insurance-risk",
    tier: "extended",
    sortOrder: 57,
    prompt: "What insurance and enterprise risk workflows should be prioritized after pilot (claims, OSHA, certificates)?",
    helpText:
      "Risk workflows often follow clinical and HR stabilization.",
    assignedTo: "CFO",
    department: "Finance",
    category: "product",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
  {
    id: "extended.product.module-priorities",
    tier: "extended",
    sortOrder: 58,
    prompt: "Rank advanced module priorities after pilot (e.g. referrals, reputation, advanced analytics).",
    helpText:
      "Roadmap sequencing protects delivery focus.",
    assignedTo: "President",
    department: "Executive / Ownership",
    category: "product",
    importance: "normal",
    answerType: "long_text",
    required: false,
  },
];
