import type { OnboardingQuestion } from "@/lib/onboarding/types";

/** First-wave questions that shape the pilot build (lean set). */
export const CORE_ONBOARDING_QUESTIONS: OnboardingQuestion[] = [
  {
    id: "core.governance.decision-rights",
    tier: "core",
    sortOrder: 1,
    prompt: "Who holds final authority for product/build decisions, pilot scope approval, and resolving disagreements?",
    helpText:
      "We need a single accountable owner so scope changes, tradeoffs, and sign-off don’t stall the pilot or create rework from conflicting directions.",
    assignedTo: "CEO",
    department: "Executive / Ownership",
    category: "governance",
    importance: "critical",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.governance.escalation",
    tier: "core",
    sortOrder: 2,
    prompt: "What is the escalation path when clinical, operations, and finance disagree on a go-live decision?",
    helpText:
      "Clear escalation prevents unsafe shortcuts, budget surprises, or silent overrides that break auditability later.",
    assignedTo: "COO",
    department: "Executive / Ownership",
    category: "governance",
    importance: "critical",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.pilot.scope",
    tier: "core",
    sortOrder: 3,
    prompt: "What is explicitly in scope for the pilot, and what is explicitly out of scope?",
    helpText:
      "Boundaries keep delivery predictable and protect residents/staff from half-built workflows during rollout.",
    assignedTo: "President",
    department: "Executive / Ownership",
    category: "pilot",
    importance: "critical",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.pilot.success",
    tier: "core",
    sortOrder: 4,
    prompt: "How will we measure pilot success (metrics, timelines, and who owns each metric)?",
    helpText:
      "Success criteria align build priorities with operational reality and give a fair stop/continue decision.",
    assignedTo: "COO",
    department: "Executive / Ownership",
    category: "pilot",
    importance: "critical",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.pilot.cutover",
    tier: "core",
    sortOrder: 5,
    prompt: "What is the planned cutover strategy: big-bang, phased by facility, or parallel run—and for how long?",
    helpText:
      "Cutover choices drive staffing, training intensity, and risk during the highest-stress window.",
    assignedTo: "COO",
    department: "Executive / Ownership",
    category: "pilot",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.risk.cannot-fail",
    tier: "core",
    sortOrder: 6,
    prompt: "Which workflows must not break on day one, and what paper or offline fallback exists for each?",
    helpText:
      "Identifying cannot-fail workflows focuses testing, support, and rollback planning where harm is highest.",
    assignedTo: "Director of Nursing",
    department: "Clinical / Resident Care",
    category: "workflows",
    importance: "critical",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.clinical.meds",
    tier: "core",
    sortOrder: 7,
    prompt: "Summarize medication pass, reorder, and pharmacy communication workflows today (who touches what, when).",
    helpText:
      "Med workflows are high-risk; mapping real steps prevents dangerous gaps during digital transition.",
    assignedTo: "Director of Nursing",
    department: "Clinical / Resident Care",
    category: "workflows",
    importance: "critical",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.clinical.assessments",
    tier: "core",
    sortOrder: 8,
    prompt: "How are assessments and care plan updates completed, reviewed, and communicated across shifts?",
    helpText:
      "Continuity across shifts is where systems fail silently—this clarifies handoffs and accountability.",
    assignedTo: "Director of Nursing",
    department: "Clinical / Resident Care",
    category: "workflows",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.clinical.incidents",
    tier: "core",
    sortOrder: 9,
    prompt: "What is the current incident / elopement reporting path, including regulatory notification expectations?",
    helpText:
      "Compliance timing and documentation rules must be reflected in workflows—not discovered after go-live.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "compliance",
    importance: "critical",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.ops.shadow-systems",
    tier: "core",
    sortOrder: 10,
    prompt: "What spreadsheets, binders, side systems, or informal workflows actually run the operation today?",
    helpText:
      "Shadow systems hide real process; surfacing them prevents building a tool nobody actually uses.",
    assignedTo: "COO",
    department: "Operations",
    category: "systems",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.ops.exceptions",
    tier: "core",
    sortOrder: 11,
    prompt: "How are exceptions handled (e.g., vendor delays, staffing shortfalls) and who approves workarounds?",
    helpText:
      "Exception paths become the real process—without them, staff improvise outside the system.",
    assignedTo: "COO",
    department: "Operations",
    category: "operations",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.ops.dietary",
    tier: "core",
    sortOrder: 12,
    prompt: "How are diets, allergies, and meal service exceptions communicated between dietary and care staff?",
    helpText:
      "Meal errors are preventable harm; clarity here protects residents and survey outcomes.",
    assignedTo: "Dietary Manager",
    department: "Dietary",
    category: "operations",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.finance.reporting",
    tier: "core",
    sortOrder: 13,
    prompt: "What does leadership need to see weekly vs daily vs monthly across entities and facilities?",
    helpText:
      "Reporting cadence drives dashboards, exports, and who must keep data clean.",
    assignedTo: "CFO",
    department: "Finance",
    category: "reporting",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.finance.ar",
    tier: "core",
    sortOrder: 14,
    prompt: "Summarize billing, collections, and trust-account practices that must remain accurate during rollout.",
    helpText:
      "Financial controls are regulated; mistakes here create legal exposure and family conflict.",
    assignedTo: "CFO",
    department: "Finance",
    category: "reporting",
    importance: "critical",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.finance.payroll",
    tier: "core",
    sortOrder: 15,
    prompt: "What are the payroll and timekeeping integrations (or manual steps) that must not break?",
    helpText:
      "Pay impacts morale and compliance; parallel-run plans should cover pay periods explicitly.",
    assignedTo: "CFO",
    department: "Finance",
    category: "operations",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.it.devices",
    tier: "core",
    sortOrder: 16,
    prompt: "Summarize device, WiFi, and connectivity constraints by facility (or enterprise-wide if uniform).",
    helpText:
      "Hardware and connectivity constraints decide what can run on the floor in real conditions.",
    assignedTo: "IT",
    department: "IT / Devices",
    category: "infrastructure",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.it.security",
    tier: "core",
    sortOrder: 17,
    prompt: "What security policies apply to PHI on workstations, mobile devices, and personal phones?",
    helpText:
      "BYOD and shared logins are common failure modes—policies should match how staff actually work.",
    assignedTo: "IT",
    department: "IT / Devices",
    category: "infrastructure",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.compliance.flags",
    tier: "core",
    sortOrder: 18,
    prompt: "What licensure, regulatory, or survey flags should implementation know about (past citations, plans of correction)?",
    helpText:
      "Known risk areas change testing priorities and documentation requirements.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "compliance",
    importance: "critical",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.compliance.retention",
    tier: "core",
    sortOrder: 19,
    prompt: "What record retention and legal hold requirements apply to clinical and financial records?",
    helpText:
      "Retention drives archive strategy and what must be auditable in-platform.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "compliance",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.hr.training",
    tier: "core",
    sortOrder: 20,
    prompt: "What training approach will be used (role-based, by facility, bilingual needs) and who certifies completion?",
    helpText:
      "Training plans determine rollout pacing and support staffing.",
    assignedTo: "HR",
    department: "HR / Workforce",
    category: "training",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.data.migration",
    tier: "core",
    sortOrder: 21,
    prompt: "What resident/staff data must migrate from legacy systems, and what is the source of truth?",
    helpText:
      "Migration scope affects timelines, validation, and cutover risk.",
    assignedTo: "IT",
    department: "IT / Devices",
    category: "data",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.data.quality",
    tier: "core",
    sortOrder: 22,
    prompt: "Where is data quality weakest today (duplicates, stale contacts, inconsistent diagnoses) and how is it cleaned?",
    helpText:
      "Bad data in means bad workflows out—cleansing rules should be explicit.",
    assignedTo: "COO",
    department: "Operations",
    category: "data",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.ai.boundaries",
    tier: "core",
    sortOrder: 23,
    prompt: "Where must AI or automation NEVER replace human judgment (clinical, consent, billing disputes)?",
    helpText:
      "Clear boundaries protect residents and keep the operator defensible under licensure and liability.",
    assignedTo: "CEO",
    department: "Executive / Ownership",
    category: "governance",
    importance: "critical",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.ai.audit",
    tier: "core",
    sortOrder: 24,
    prompt: "What audit artifacts are required when AI suggests actions (who reviewed, when, overrides)?",
    helpText:
      "Auditability is a regulatory and liability requirement—not optional polish.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "compliance",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.family.engagement",
    tier: "core",
    sortOrder: 25,
    prompt: "How should families receive updates and who approves messaging that could be clinical or financial?",
    helpText:
      "Family communication touches satisfaction and privacy—roles must be explicit.",
    assignedTo: "Executive Director",
    department: "Executive / Ownership",
    category: "operations",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.vendor.critical",
    tier: "core",
    sortOrder: 26,
    prompt: "Which vendor or outsourced services are critical path for daily operations (pharmacy, laundry, IT MSP)?",
    helpText:
      "Vendor dependencies affect integrations, SLAs, and incident response.",
    assignedTo: "COO",
    department: "Operations",
    category: "operations",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.emergency.preparedness",
    tier: "core",
    sortOrder: 27,
    prompt: "Summarize emergency preparedness communications (weather, power, clinical surge) used today.",
    helpText:
      "Emergency comms must remain reliable if systems change—identify single points of failure.",
    assignedTo: "COO",
    department: "Operations",
    category: "operations",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.quality.qapi",
    tier: "core",
    sortOrder: 28,
    prompt: "How is QAPI or quality review conducted today (cadence, metrics, accountable roles)?",
    helpText:
      "Quality cycles should map to reporting so leadership sees the same truth operations uses.",
    assignedTo: "Director of Nursing",
    department: "Clinical / Resident Care",
    category: "reporting",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.reporting.board",
    tier: "core",
    sortOrder: 29,
    prompt: "What board or owner reporting pack is required monthly (finance + clinical + compliance highlights)?",
    helpText:
      "Executive reporting sets the minimum credible narrative for governance oversight.",
    assignedTo: "CFO",
    department: "Finance",
    category: "reporting",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.staffing.ratios",
    tier: "core",
    sortOrder: 30,
    prompt: "What staffing ratio or acuity rules must be reflected in scheduling and census planning?",
    helpText:
      "Regulatory staffing expectations affect scheduling modules and alerts.",
    assignedTo: "Director of Nursing",
    department: "Clinical / Resident Care",
    category: "workflows",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.behavior.care",
    tier: "core",
    sortOrder: 31,
    prompt: "How are behavioral care plans and interventions coordinated with activities and care staff?",
    helpText:
      "Behavior support spans departments—clear ownership reduces inconsistent responses.",
    assignedTo: "Director of Nursing",
    department: "Clinical / Resident Care",
    category: "workflows",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.infection.control",
    tier: "core",
    sortOrder: 32,
    prompt: "What infection control surveillance and reporting is performed today (outbreaks, tracking tools)?",
    helpText:
      "Infection processes often have external reporting obligations—capture them explicitly.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "compliance",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.telephony",
    tier: "core",
    sortOrder: 33,
    prompt: "What phone system and on-call escalation tree is used after hours for clinical and maintenance issues?",
    helpText:
      "After-hours paths are high-risk; they must remain coherent during system changes.",
    assignedTo: "COO",
    department: "Operations",
    category: "operations",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.privacy.requests",
    tier: "core",
    sortOrder: 34,
    prompt: "Who handles privacy requests, record releases, and resident/family data corrections?",
    helpText:
      "Privacy workflows must be assignable and auditable—especially across entities.",
    assignedTo: "Compliance",
    department: "Compliance",
    category: "compliance",
    importance: "high",
    answerType: "long_text",
    required: true,
  },
  {
    id: "core.single-select.pilot-length",
    tier: "core",
    sortOrder: 35,
    prompt: "Preferred pilot length (select one)",
    helpText:
      "Pilot duration affects resourcing, parallel-run cost, and how much feedback we can incorporate.",
    assignedTo: "President",
    department: "Executive / Ownership",
    category: "pilot",
    importance: "high",
    answerType: "single_select",
    required: true,
    options: ["30 days", "60 days", "90 days", "120+ days"],
  },
  {
    id: "core.yes-no.parallel-run",
    tier: "core",
    sortOrder: 36,
    prompt: "Will you require a mandatory parallel run with legacy systems before decommissioning?",
    helpText:
      "Parallel run reduces risk but increases workload—leadership should confirm expectations explicitly.",
    assignedTo: "CFO",
    department: "Finance",
    category: "pilot",
    importance: "high",
    answerType: "yes_no",
    required: true,
  },
];
