import { createHash, createHmac } from "node:crypto";
import {
  QBO_WEBHOOK_LIMITS,
  type QboWebhookError,
  type QboWebhookResult,
  validateQboWebhook,
} from "./qbo-webhook.ts";
const key = "synthetic-verifier-canary-DO-NOT-LOG";
const encoder = new TextEncoder();
const event = (change: Record<string, unknown> = {}) => ({
  specversion: "1.0",
  id: "provider-event-1",
  source: "intuit.opaque/source=",
  type: "qbo.invoice.updated.v1",
  intuitaccountid: "9341455327810551",
  intuitentityid: "123",
  time: "2026-09-09T04:12:31.179851517Z",
  datacontenttype: "application/json",
  data: {},
  ...change,
});
function assert(value: unknown, message: string): asserts value {
  if (!value) throw new Error(message);
}
function equal(actual: unknown, expected: unknown, message: string) {
  assert(JSON.stringify(actual) === JSON.stringify(expected), message);
}
function signature(body: Uint8Array, secret = key) {
  return createHmac("sha256", secret).update(body).digest("base64");
}
function digest(body: Uint8Array) {
  return createHash("sha256").update(body).digest("hex");
}
function input(
  body: Uint8Array,
  secret = key,
  contentType = "application/json",
) {
  return {
    body,
    verifierToken: secret,
    headers: [["Content-Type", contentType], [
      "intuit-signature",
      signature(body, secret),
    ]] as [string, string][],
  };
}
function json(value: unknown) {
  return encoder.encode(JSON.stringify(value));
}
async function validate(value: unknown) {
  return await validateQboWebhook(input(json(value)));
}
function success(result: QboWebhookResult) {
  assert(result.ok, "Expected valid signature and schema");
  return result;
}
function rejected(
  result: QboWebhookResult,
  code: QboWebhookError,
  authenticated: boolean,
) {
  assert(
    !result.ok && result.code === code &&
      result.authenticated === authenticated,
    `Expected fixed rejection ${code}/${authenticated}`,
  );
  return result;
}

Deno.test("HFA-024: RFC4231 known HMAC vector authenticates before JSON rejection", async () => {
  // RFC4231 §4.3 independently published test case2, not generated by the validator.
  const body = encoder.encode("what do ya want for nothing?");
  const expectedHex =
    "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843";
  const expected = btoa(
    String.fromCharCode(
      ...expectedHex.match(/../g)!.map((value) => parseInt(value, 16)),
    ),
  );
  assert(
    signature(body, "Jefe") === expected,
    "Independent Node oracle must match published vector",
  );
  const result = await validateQboWebhook({
    body,
    verifierToken: "Jefe",
    headers: [["content-type", "application/json"], [
      "intuit-signature",
      expected,
    ]],
  });
  const failure = rejected(result, "invalid_json", true);
  assert(
    failure.authenticated && failure.evidence.body_sha256 === digest(body),
    "Authenticated malformed content must retain exact evidence",
  );
});
Deno.test("HFA-024: exact whitespace and nonASCII bytes use independent HMAC and digest oracles", async () => {
  const raw = ` \n[\n ${
    JSON.stringify(event({ data: { name: "患者 café 🧾", amount: 17 } }))
  }\n]\r\n`;
  const body = encoder.encode(raw);
  const result = success(await validateQboWebhook(input(body)));
  assert(
    result.evidence.body_sha256 === digest(body),
    "Whole-body bytes must match independent digest",
  );
  const range = result.privateMetadata.eventByteRanges[0];
  assert(
    result.privateMetadata.events[0].event_bytes_sha256 ===
      digest(body.slice(range.start, range.end)),
    "Event exact-byte hash must match independent digest",
  );
  equal(
    Array.from(result.evidence.copyAuthenticatedBody()),
    Array.from(body),
    "Original authenticated bytes retained",
  );
  const altered = encoder.encode(raw.replace("café", "cafe"));
  rejected(
    await validateQboWebhook({ ...input(body), body: altered }),
    "signature_invalid",
    false,
  );
});
Deno.test("HFA-024: documented content types and header casing authenticate", async () => {
  for (
    const contentType of [
      "application/json",
      "application/cloudevents+json",
      'Application/CloudEvents+Json; charset="utf-8"',
    ]
  ) {
    const request = input(json([event()]), key, contentType);
    request.headers[1][0] = "Intuit-Signature";
    success(await validateQboWebhook(request));
  }
  success(await validate([{ ...event(), datacontenttype: undefined }]));
});
Deno.test("HFA-024: invalid or absent verifier configuration never exposes secrets", async () => {
  const body = json([event()]);
  for (
    const verifierToken of [
      "",
      " ",
      "secret\ncanary",
      "x".repeat(4097),
      "\ud800",
    ]
  ) {
    const result = rejected(
      await validateQboWebhook({ ...input(body), verifierToken }),
      "invalid_config",
      false,
    );
    assert(
      !JSON.stringify(result).includes("canary"),
      "Configuration error must be sanitized",
    );
  }
});
Deno.test("HFA-024: missing malformed and noncanonical signatures fail closed", async () => {
  const body = json([event()]);
  for (
    const bad of [
      "",
      "Bearer " + signature(body),
      signature(body).replace(/=$/, ""),
      " " + signature(body),
      signature(body) + ", " + signature(body),
      "x".repeat(43) + "=",
      "A".repeat(42) + "B=",
    ]
  ) {
    rejected(
      await validateQboWebhook({
        ...input(body),
        headers: [["content-type", "application/json"], [
          "intuit-signature",
          bad,
        ]],
      }),
      "signature_invalid",
      false,
    );
  }
  rejected(
    await validateQboWebhook({
      ...input(body),
      headers: [["content-type", "application/json"]],
    }),
    "signature_invalid",
    false,
  );
});
Deno.test("HFA-024: duplicate security headers and injection characters rejected", async () => {
  const request = input(json([event()]));
  for (
    const duplicate of [["INTUIT-SIGNATURE", request.headers[1][1]], [
      "CONTENT-TYPE",
      "application/json",
    ]] as [string, string][]
  ) {
    rejected(
      await validateQboWebhook({
        ...request,
        headers: [...request.headers, duplicate],
      }),
      "invalid_headers",
      false,
    );
  }
  for (
    const bad of [["x-test", "value\r\nsecret-canary"], [
      "content-type ",
      "application/json",
    ]] as [string, string][]
  ) {
    rejected(
      await validateQboWebhook({
        ...request,
        headers: [...request.headers, bad],
      }),
      "invalid_headers",
      false,
    );
  }
});
Deno.test("HFA-024: unsupported missing and merged content types are not authenticated", async () => {
  const body = json([event()]);
  for (
    const value of [
      "text/plain",
      "application/json; charset=latin1",
      "application/json, application/json",
      "application/cloudevents-batch+json",
      "application/json; boundary=extra",
    ]
  ) {
    rejected(
      await validateQboWebhook(input(body, key, value)),
      "unsupported_content_type",
      false,
    );
  }
  rejected(
    await validateQboWebhook({
      ...input(body),
      headers: [["intuit-signature", signature(body)]],
    }),
    "unsupported_content_type",
    false,
  );
});
Deno.test("HFA-024: oversized bodies fail before authentication and parsing", async () => {
  const result = await validateQboWebhook({
    body: new Uint8Array(QBO_WEBHOOK_LIMITS.bytes + 1),
    verifierToken: key,
    headers: [],
  });
  rejected(result, "body_too_large", false);
  assert(
    !("evidence" in result),
    "Unauthenticated body must not be retained in result",
  );
});
Deno.test("HFA-024: authentication precedes corrupt UTF8 and JSON parsing", async () => {
  const corrupt = new Uint8Array([91, 0xc0, 0xaf, 93]);
  const request = input(corrupt);
  request.headers[1][1] = signature(encoder.encode("different"));
  rejected(await validateQboWebhook(request), "signature_invalid", false);
  const failure = rejected(
    await validateQboWebhook(input(corrupt)),
    "invalid_utf8",
    true,
  );
  assert(
    failure.authenticated,
    "Verified invalidUTF8 must retain authenticated status",
  );
  equal(
    Array.from(failure.evidence.copyAuthenticatedBody()),
    Array.from(corrupt),
    "InvalidUTF8 evidence must be byte-identical",
  );
});
Deno.test("HFA-024: malformed JSON duplicate decoded keys and trailing bytes are rejected", async () => {
  for (
    const raw of [
      "{broken",
      "[",
      "[1,]",
      '[{"x":01}]',
      '[{"x":1e}]',
      '[{"x":"\\q"}]',
      '[{"id":"a","\\u0069d":"b"}]',
      `[${JSON.stringify(event())}] trailing`,
      "\ufeff[]",
      `[${
        JSON.stringify(event({ data: { a: 1 } })).replace(
          '"data":{"a":1}',
          '"data":{"a":1,"a":2}',
        )
      } ]`,
    ]
  ) {
    const body = encoder.encode(raw);
    const result = rejected(
      await validateQboWebhook(input(body)),
      "invalid_json",
      true,
    );
    assert(
      result.authenticated && result.evidence.body_sha256 === digest(body),
      "Malformed authenticated evidence must remain available",
    );
  }
});
Deno.test("HFA-024: current array shape required without fabricated legacy IDs", async () => {
  for (
    const value of [event(), { eventNotifications: [] }, [], [null], [42], [
      "event",
    ], [[]]]
  ) rejected(await validate(value), "invalid_schema", true);
});
Deno.test("HFA-024: all required fields must exist and unsupported extensions fail closed", async () => {
  for (
    const name of [
      "specversion",
      "id",
      "source",
      "type",
      "time",
      "intuitentityid",
      "intuitaccountid",
      "data",
    ]
  ) {
    const value: Record<string, unknown> = event();
    delete value[name];
    rejected(await validate([value]), "invalid_schema", true);
  }
  for (
    const extension of [
      "memo",
      "subject",
      "dataschema",
      "traceparent",
      "data_base64",
    ]
  ) {
    rejected(
      await validate([event({ [extension]: null })]),
      "invalid_schema",
      true,
    );
  }
});
Deno.test("HFA-024: wrong metadata types and malformed current event fields rejected", async () => {
  for (
    const change of [
      { id: 5 },
      { source: null },
      { type: "unknown" },
      { time: false },
      { specversion: "2.0" },
      { intuitentityid: 123 },
      { intuitaccountid: 123 },
      { data: [] },
      { data: null },
      { datacontenttype: null },
      { datacontenttype: "text/plain" },
      { id: "contains space" },
      { id: "\ud800" },
    ]
  ) rejected(await validate([event(change)]), "invalid_schema", true);
});
Deno.test("HFA-024: nanosecond provider time retained without freshness or checkpoints", async () => {
  for (
    const time of [
      "2026-09-09T04:12:31.179851517Z",
      "1900-01-01T00:00:00Z",
      "2099-12-31T23:59:59.1-05:00",
      "2024-02-29T00:00:00+00:00",
    ]
  ) {
    const result = success(await validate([event({ time })]));
    assert(
      result.privateMetadata.events[0].time === time,
      "Time must remain exact regardless of age",
    );
    assert(
      !("checkpoint" in result) && !("fresh" in result),
      "No temporal authority may be inferred",
    );
  }
  for (
    const time of [
      "2026-02-29T00:00:00Z",
      "2026-04-31T00:00:00Z",
      "2026-09-09T24:00:00Z",
      "2026-09-09T00:00:00.1234567890Z",
      "2026-09-09T00:00:60Z",
      "2026-09-09",
    ]
  ) rejected(await validate([event({ time })]), "invalid_schema", true);
});
Deno.test("HFA-024: mixed companies and opaque private identifiers are not tenant bindings", async () => {
  const source = "https://never-fetch.invalid/private-source";
  const result = success(
    await validate([
      event({ source, id: "first" }),
      event({
        source,
        id: "second",
        intuitaccountid: "private-realm-canary",
        intuitentityid: "private-record-canary",
        data: { name: "private-data-canary" },
      }),
    ]),
  );
  assert(
    result.privateMetadata.events[1].intuitaccountid === "private-realm-canary",
    "Opaque provider value must be retained privately",
  );
  const logs = JSON.stringify(result.logSummary);
  for (
    const canary of [
      key,
      source,
      "private-realm-canary",
      "private-record-canary",
      "private-data-canary",
      "first",
    ]
  ) {
    assert(
      !logs.includes(canary),
      "Log summary must exclude private provider metadata",
    );
  }
  assert(
    result.logSummary.event_count === 2 &&
      !JSON.stringify(result.privateMetadata).includes("private-data-canary"),
    "Data remains raw evidence, not parsed metadata",
  );
  assert(
    !("tenant" in result) && !("processed" in result) &&
      !("accepted" in result),
    "No tenant or durable acceptance claim",
  );
});
Deno.test("HFA-024: same provider identity with changed exact bytes is a conflict", async () => {
  rejected(
    await validate([event(), event({ data: { amount: 1 } })]),
    "event_id_conflict",
    true,
  );
  rejected(
    await validate([event(), event({ intuitaccountid: "another-company" })]),
    "event_id_conflict",
    true,
  );
  const raw = JSON.stringify(event());
  rejected(
    await validateQboWebhook(
      input(
        encoder.encode(`[${raw},${raw.replace('"data":{}', '"data": {}')}]`),
      ),
    ),
    "event_id_conflict",
    true,
  );
});
Deno.test("HFA-024: byte-identical repeated events remain hints for future durable dedup", async () => {
  const result = success(await validate([event(), event()]));
  const [a, b] = result.privateMetadata.events;
  assert(
    result.logSummary.event_count === 2 &&
      a.identity_sha256 === b.identity_sha256 &&
      a.event_bytes_sha256 === b.event_bytes_sha256,
    "Do not pretend durable dedup already occurred",
  );
  const other = success(
    await validate([event(), event({ source: "another-source" })]),
  );
  assert(
    other.privateMetadata.events[0].identity_sha256 !==
      other.privateMetadata.events[1].identity_sha256,
    "Identity includes provider source",
  );
});
Deno.test("HFA-024: large JSON numbers and lexical representations cannot collide via float rounding", async () => {
  const raw = JSON.stringify(event()).replace(
    '"data":{}',
    '"data":{"amount":9007199254740992}',
  );
  const changed = raw.replace("9007199254740992", "9007199254740993");
  rejected(
    await validateQboWebhook(input(encoder.encode(`[${raw},${changed}]`))),
    "event_id_conflict",
    true,
  );
  const one = success(
    await validateQboWebhook(input(encoder.encode(`[${raw}]`))),
  );
  const two = success(
    await validateQboWebhook(input(encoder.encode(`[${changed}]`))),
  );
  assert(
    one.privateMetadata.events[0].event_bytes_sha256 !==
      two.privateMetadata.events[0].event_bytes_sha256,
    "Rounded-equivalent numbers require different exact fingerprints",
  );
  for (const numeral of ["1e400", "-0", "1.00", "1e0"]) {
    success(
      await validateQboWebhook(
        input(encoder.encode(`[${raw.replace("9007199254740992", numeral)}]`)),
      ),
    );
  }
});
Deno.test("HFA-024: caller mutation cannot swap authenticated bytes after await", async () => {
  const body = json([event()]);
  const original = body.slice();
  const promise = validateQboWebhook(input(body));
  body.fill(0);
  const result = success(await promise);
  equal(
    Array.from(result.evidence.copyAuthenticatedBody()),
    Array.from(original),
    "Input bytes must be privately owned before async work",
  );
  const first = result.evidence.copyAuthenticatedBody();
  first.fill(0);
  equal(
    Array.from(result.evidence.copyAuthenticatedBody()),
    Array.from(original),
    "Evidence access must return independent copies",
  );
  assert(
    Object.isFrozen(result.privateMetadata.events) &&
      Object.isFrozen(result.privateMetadata.events[0]) &&
      Object.isFrozen(result.logSummary),
    "Derived metadata is immutable",
  );
});
Deno.test("HFA-024: bounded event count depth and JSON nodes fail without dropping authenticated evidence", async () => {
  rejected(
    await validate(
      Array.from(
        { length: QBO_WEBHOOK_LIMITS.events + 1 },
        (_, i) => event({ id: `event-${i}` }),
      ),
    ),
    "limits_exceeded",
    true,
  );
  const deep = JSON.stringify(event()).replace(
    '"data":{}',
    '"data":{"nested":' + "[".repeat(40) + "0" + "]".repeat(40) + "}",
  );
  rejected(
    await validateQboWebhook(input(encoder.encode(`[${deep}]`))),
    "limits_exceeded",
    true,
  );
  rejected(
    await validate([
      event({
        data: {
          many: Array.from({ length: QBO_WEBHOOK_LIMITS.nodes }, () => 0),
        },
      }),
    ]),
    "limits_exceeded",
    true,
  );
});
Deno.test("HFA-024: all error diagnostics exclude body signature and verifier canaries", async () => {
  for (
    const body of [
      encoder.encode("malformed-private-body-canary"),
      json([event({ memo: "private-body-canary" })]),
    ]
  ) {
    const request = input(body);
    const result = await validateQboWebhook(request);
    assert(!result.ok, "Must reject malformed input");
    const serialized = JSON.stringify(result);
    for (const secret of [key, request.headers[1][1], "private-body-canary"]) {
      assert(
        !serialized.includes(secret),
        "Only fixed codes and authorized digest metadata may serialize",
      );
    }
    assert(
      result.authenticated &&
        result.evidence.copyAuthenticatedBody().length === body.length,
      "Private quarantine evidence remains separately available",
    );
  }
});

Deno.test("HFA-024: validly formatted wrong verifier has no authenticated evidence", async () => {
  const request = input(json([event()]));
  const result = rejected(
    await validateQboWebhook({
      ...request,
      verifierToken: "other-valid-verifier-canary",
    }),
    "signature_invalid",
    false,
  );
  assert(
    !("evidence" in result),
    "Wrong verifier must not establish authenticated evidence",
  );
});
Deno.test("HFA-024: all events at the local batch bound are returned without truncation", async () => {
  const result = success(
    await validate(
      Array.from(
        { length: QBO_WEBHOOK_LIMITS.events },
        (_, index) => event({ id: `bound-${index}` }),
      ),
    ),
  );
  assert(
    result.privateMetadata.events.length === QBO_WEBHOOK_LIMITS.events &&
      result.logSummary.event_count === QBO_WEBHOOK_LIMITS.events,
    "Accepted metadata may not truncate the input batch",
  );
  assert(
    result.privateMetadata.events.at(-1)?.id ===
      `bound-${QBO_WEBHOOK_LIMITS.events - 1}`,
    "Last provider event must be retained",
  );
});
Deno.test("HFA-024: envelope whitespace does not change exact event slice identity", async () => {
  const raw = JSON.stringify(event());
  const first = success(
    await validateQboWebhook(input(encoder.encode(`[${raw}]`))),
  );
  const second = success(
    await validateQboWebhook(input(encoder.encode(` \n[ \r\n${raw} \n] `))),
  );
  assert(
    first.evidence.body_sha256 !== second.evidence.body_sha256,
    "Body evidence includes surrounding whitespace",
  );
  assert(
    first.privateMetadata.events[0].event_bytes_sha256 ===
      second.privateMetadata.events[0].event_bytes_sha256,
    "Event fingerprint covers exactly its object bytes",
  );
});
