"use client";

import {
  AlertTriangle,
  BarChart3,
  BookOpen,
  ClipboardCheck,
  Heart,
  Home,
  MessageCircle,
  Phone,
  Pill,
  Shield,
  Users,
  FileText,
} from "lucide-react";
import type { GraceTemplate } from "./types";

export const GRACE_TEMPLATES: GraceTemplate[] = [
  {
    id: "check_resident",
    icon: Heart,
    title: "Check on a resident",
    subtitle: "View care plan, medications, recent notes, and alerts",
    roles: ["caregiver", "nurse", "admin_assistant", "coordinator", "manager", "facility_admin", "org_admin", "owner"],
    type: "knowledge",
    phrase: "Check on resident ",
    knowledge_only: true,
  },
  {
    id: "log_daily_note",
    icon: FileText,
    title: "Log a daily note",
    subtitle: "Record observations, behaviors, or care activities",
    roles: ["caregiver", "nurse", "admin_assistant", "coordinator", "manager", "facility_admin", "org_admin", "owner"],
    type: "flow",
    phrase: "Log a daily note for ",
    flow_slug: "log_daily_note",
  },
  {
    id: "medication_check",
    icon: Pill,
    title: "Check medications",
    subtitle: "View a resident's current meds, schedule, and interactions",
    roles: ["nurse", "manager", "facility_admin", "org_admin", "owner"],
    type: "knowledge",
    phrase: "Check medications for ",
    knowledge_only: true,
  },
  {
    id: "report_incident",
    icon: AlertTriangle,
    title: "Report an incident",
    subtitle: "Log a fall, behavior event, medication error, or safety concern",
    roles: ["caregiver", "nurse", "admin_assistant", "coordinator", "manager", "facility_admin", "org_admin", "owner"],
    type: "flow",
    phrase: "Report an incident for ",
    flow_slug: "report_incident",
  },
  {
    id: "check_room",
    icon: Home,
    title: "Check room status",
    subtitle: "View room occupancy, assignments, and availability",
    roles: ["manager", "facility_admin", "org_admin", "owner"],
    type: "knowledge",
    phrase: "Check room status for ",
    knowledge_only: true,
  },
  {
    id: "find_protocol",
    icon: BookOpen,
    title: "Find a protocol",
    subtitle: "Search SOPs, care protocols, and compliance docs",
    roles: ["caregiver", "nurse", "admin_assistant", "coordinator", "manager", "facility_admin", "org_admin", "owner"],
    type: "knowledge",
    phrase: "Find protocol for ",
    knowledge_only: true,
  },
  {
    id: "staff_on_shift",
    icon: Users,
    title: "Who's on shift",
    subtitle: "View current staff, roles, and assignments",
    roles: ["nurse", "manager", "facility_admin", "org_admin", "owner"],
    type: "knowledge",
    phrase: "Who is on shift ",
    knowledge_only: true,
  },
  {
    id: "schedule_assessment",
    icon: ClipboardCheck,
    title: "Schedule an assessment",
    subtitle: "Set up a care plan review, wellness check, or evaluation",
    roles: ["nurse", "manager", "facility_admin", "org_admin", "owner"],
    type: "flow",
    phrase: "Schedule an assessment for ",
    flow_slug: "schedule_assessment",
  },
  {
    id: "ask_grace",
    icon: MessageCircle,
    title: "Ask Grace anything",
    subtitle: "Get answers from protocols, care data, and the web",
    roles: ["caregiver", "nurse", "admin_assistant", "coordinator", "manager", "facility_admin", "org_admin", "owner"],
    type: "knowledge",
    phrase: "",
    knowledge_only: true,
  },
  {
    id: "daily_census",
    icon: BarChart3,
    title: "Daily census",
    subtitle: "Current resident count, admissions, discharges, room availability",
    roles: ["manager", "facility_admin", "org_admin", "owner"],
    type: "knowledge",
    phrase: "Show me today's census",
    knowledge_only: true,
  },
  {
    id: "open_incidents",
    icon: Shield,
    title: "Open incidents",
    subtitle: "View unresolved incidents and follow-up actions",
    roles: ["nurse", "manager", "facility_admin", "org_admin", "owner"],
    type: "knowledge",
    phrase: "Show open incidents",
    knowledge_only: true,
  },
  {
    id: "family_contact",
    icon: Phone,
    title: "Family contact lookup",
    subtitle: "Find family members and emergency contacts",
    roles: ["caregiver", "nurse", "admin_assistant", "coordinator", "manager", "facility_admin", "org_admin", "owner"],
    type: "knowledge",
    phrase: "Find family contact for ",
    knowledge_only: true,
  },
];

export function filterGraceTemplates(role: string | null | undefined): GraceTemplate[] {
  const safeRole = role ?? "caregiver";
  return GRACE_TEMPLATES.filter((template) => template.roles.includes(safeRole));
}
