import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { chromium } from "playwright";
import AxeBuilder from "@axe-core/playwright";
const origin = "http://127.0.0.1:8950", output = process.env.SHIFT_PROOF_DIR;
if (!output?.includes("/.hermes/tmp/agent-runs/")) throw new Error("Owned proof directory required");
await fs.mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const checks = [], errors = [], external = [], axe = [];
let page;
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: "reduce" });
  await context.route("**/*", (route) => { const url = new URL(route.request().url()); if (url.origin === origin || ["data:", "blob:"].includes(url.protocol)) return route.continue(); external.push(url.origin); return route.abort(); });
  page = await context.newPage(); page.on("pageerror", (error) => errors.push(error.message));
  await page.clock.install({ time: new Date("2026-09-28T14:12:00Z") });
  const state = () => page.request.get(`${origin}/__fixture/proof`).then((r) => r.json());
  const shot = async (name) => { await page.screenshot({ path: path.join(output, name), fullPage: true }); axe.push(...(await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations.map((v) => ({ id: v.id, impact: v.impact, nodes: v.nodes.length }))); };
  const weekUrl = `${origin}/admin/schedules/33333333-3333-4333-8333-333333333333`;
  await page.goto(weekUrl);
  const care = page.getByRole("button", { name: /^Casey Care, Mon, Sep 28:/ });
  await care.waitFor();
  await care.click(); await care.click(); await care.click();
  await page.getByRole("dialog", { name: "Custom shift", exact: true }).waitFor();
  assert.equal(await page.getByLabel("Start time", { exact: true }).inputValue(), "");
  assert(await page.getByRole("button", { name: "Apply times", exact: true }).isDisabled());
  await page.getByRole("button", { name: "Set off", exact: true }).click();
  assert((await care.getAttribute("aria-label")).includes(": Off."));
  assert.equal((await state()).writes, 0);
  await care.click();
  await page.getByRole("button", { name: /^Riley Cook, Mon, Sep 28:/ }).click();
  await page.getByRole("button", { name: /^Alex Admin, Mon, Sep 28:/ }).click();
  assert((await page.getByRole("button", { name: /^Riley Cook, Mon, Sep 28:/ }).getAttribute("aria-label")).includes("Cook split 6:00a–1:00p, Cook split 4:00p–6:00p"));
  assert.equal(await page.getByText("9.0 h", { exact: true }).count(), 1);
  await page.getByRole("button", { name: "Save 3 changes", exact: true }).click();
  await page.getByText("Draft saved.", { exact: true }).waitFor();
  const saved = await state(); assert.equal(saved.assignments.length, 4);
  const cook = saved.assignments.filter((a) => a.staff_id.endsWith("2222"));
  assert.equal(cook.length, 2); assert.equal(cook.reduce((sum, a) => sum + Date.parse(a.schedule_ends_at) - Date.parse(a.schedule_starts_at), 0), 9 * 3600000);
  assert(cook.every((a) => a.schedule_rounding_coverage === false));
  checks.push("Day/Night/Custom/Off requires no custom times for Off; job roles see appropriate choices; cook splits save as two blocks/nine hours and no automatic clinical coverage.");
  await shot("schedule-desktop.png");
  await page.setViewportSize({ width: 390, height: 844 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth));
  await page.getByRole("region", { name: "Seven-day employee schedule", exact: true }).waitFor();
  await shot("schedule-phone.png");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("button", { name: "Publish week", exact: true }).click();
  await page.getByText("Published. Assigned staff can now see this week in My schedule.", { exact: true }).waitFor();
  assert(await care.isDisabled());
  await page.emulateMedia({ media: "print" });
  assert(await page.getByRole("table").isVisible());
  await page.pdf({ path: path.join(output, "schedule.pdf"), printBackground: true, preferCSSPageSize: true });
  await page.emulateMedia({ media: "screen" });
  checks.push("Desktop/mobile grid fits and scrolls accessibly; publication locks cells; landscape print preserves saved blocks and colors.");
  await page.goto(`${origin}/admin/schedules/options`);
  await page.getByRole("button", { name: "New shift option", exact: true }).click();
  assert.equal(await page.getByLabel("Label", { exact: true }).inputValue(), "");
  assert(!(await page.getByRole("checkbox", { name: /Use for resident check coverage/ }).isChecked()));
  await shot("options-desktop.png");
  await page.getByLabel("Label", { exact: true }).fill("Evening care");
  await page.getByLabel("Display order", { exact: true }).fill("2");
  await page.getByLabel("Block 1 start", { exact: true }).fill("14:00");
  await page.getByLabel("Block 1 finish", { exact: true }).fill("22:00");
  await page.getByRole("checkbox", { name: "Medication Tech", exact: true }).check();
  await page.getByRole("checkbox", { name: /Use for resident check coverage/ }).check();
  await page.getByRole("button", { name: "Save shift option", exact: true }).click();
  await page.getByText(/Evening care saved/).waitFor();
  const third = (await state()).presets.find((p) => p.label === "Evening care"); assert(third); assert.equal(third.allowed_staff_roles.join(","), "medication_tech"); assert.equal(third.rounding_coverage, true);
  await page.getByRole("button", { name: "Edit Cook split", exact: true }).click();
  await page.getByLabel("Label", { exact: true }).fill("Kitchen revised");
  await page.getByRole("checkbox", { name: /^Active — available/ }).uncheck();
  await page.getByRole("button", { name: "Save shift option", exact: true }).click();
  await page.getByText(/Kitchen revised saved as inactive/).waitFor();
  await page.goto(weekUrl);
  await page.getByRole("button", { name: /^Riley Cook, Mon, Sep 28: Cook split/ }).waitFor();
  assert.equal(await page.getByText("Kitchen revised", { exact: true }).count(), 0);
  checks.push("Options begin with explicit empty hours/roles, support an added third care choice, and later rename/deactivation does not rewrite published snapshots.");
  await page.goto(`${origin}/caregiver/schedules`);
  await page.locator('[data-slot="card-title"]').filter({ hasText: /^My schedule$/ }).waitFor();
  await page.getByText(/^Cook split ·/i).first().waitFor();
  await shot("my-schedule.png");
  await page.goto(`${origin}/attendance`);
  await page.getByText(/2 published work blocks · 9.00 planned hours/).waitFor();
  assert(await page.getByRole("button", { name: "Clock in", exact: true }).isEnabled());
  await shot("attendance-context.png");
  const identified = await page.request.get(`${origin}/__fixture/attendance`).then((r) => r.json());
  assert.equal(identified.today_worked_minutes, 252); assert.deepEqual(identified.next_actions, ["in"]);
  checks.push("My Schedule and kiosk/timecard/payroll comparison render the same saved split blocks; actual worked minutes and clock actions remain independent.");
  await page.goto(`${origin}/swaps`);
  await page.getByText("Requested work · 9.0 scheduled hours", { exact: true }).waitFor();
  assert.equal(await page.getByRole("listitem").count(), 2);
  await shot("swap-group-context.png");
  checks.push("Swap review displays both saved cook blocks and their nine-hour total as one complete group.");
  await fs.writeFile(path.join(output, "browser-proof.json"), JSON.stringify({ checked_at: new Date().toISOString(), scope: "Actual UI/interval helpers with synthetic local persistence and mocked authentication; not hosted or staff/provider acceptance", checks, page_errors: errors, external_requests: external, axe_violations: axe, production_mutations: false }, null, 2));
  assert.equal(errors.length, 0, errors.join("\n")); assert.equal(external.length, 0, external.join("\n")); assert.equal(axe.length, 0, JSON.stringify(axe));
  console.log(`PASS ${checks.length} shift workflow groups, desktop/phone/print and downstream planned context.`);
} catch (error) { if (page) { await page.screenshot({ path: path.join(output, "failure.png"), fullPage: true }); await fs.writeFile(path.join(output, "failure.txt"), JSON.stringify({error: String(error), page_errors: errors, body: await page.locator("body").innerText()}, null, 2)); } throw error; } finally { await browser.close(); }
