"use client";
import Link from "next/link";
import { useState } from "react";
import { RefreshCw, Users, Clock, CalendarDays, FileCheck } from "lucide-react";
import { FacilityGateNotice } from "@/components/common/FacilityGate";
import { Button, buttonVariants } from "@/components/ui/button";
import { KPITile } from "@/design-system/components/KPITile";
import { metricFromCount, metricNotConfigured } from "@/lib/metrics/metric-state";
import { Input } from "@/components/ui/input";
import { HorizontalScroll } from "@/components/ui/horizontal-scroll";
import { useFacilityStore } from "@/hooks/useFacilityStore";
import { formatMinutesCompact } from "@/lib/timeclock/display-copy";
import { formatInTimeZone } from "date-fns-tz";
import { completedWeekTimesheetHref, type WorkforcePerson } from "@/lib/workforce/model";
import { useWorkforce } from "./WorkforceContext";

type View = "today" | "timecards" | "people";
const titles = { today: "Today", timecards: "Timecards", people: "People" };
function clockLabel(person: WorkforcePerson, enabled: boolean) {
  if (!enabled) return "Kiosk not enabled";
  if (person.status === "out") return person.since ? "Clocked out" : "No punch recorded";
  return `${person.status === "meal" ? "On meal" : "In"}${person.since ? ` since ${formatInTimeZone(new Date(person.since), "America/New_York", "h:mma")}` : ""}`;
}

export function WorkforcePage({ view }: { view: View }) {
  const { data, loading, error, refresh } = useWorkforce();
  const facilityId = useFacilityStore((s) => s.selectedFacilityId);
  const [search, setSearch] = useState("");
  const people = data?.people.filter((p) => `${p.name} ${p.role}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  const present = data?.people.filter((p) => p.status === "in" || p.status === "meal");
  const missing = data?.people.filter((p) => p.attendance === "missing");
  const extra = data?.people.filter((p) => p.attendance === "extra");
  const scheduleTimesMissing = data?.people.some((p) => p.attendance === "unknown") ?? false;
  const exceptions = data?.people.filter((p) => p.exceptions > 0);
  const exceptionCount = metricFromCount({ count: exceptions?.length, loading, error });
  const due = data?.people.flatMap((p) => p.due.map((item) => ({ ...item, person: p }))).sort((a, b) => a.date.localeCompare(b.date));
  return <section className="space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">{titles[view]}</h1><p className="mt-1 text-sm text-muted-foreground">{view === "today" ? "Published shifts alongside recorded kiosk attendance." : view === "timecards" ? "Review the completed week and correct missing punches before payroll." : data?.allFacilities ? "Employees and their current facility assignments." : "Staff, upcoming shifts, and the employee-file requirements on record."}</p>{data ? <p className="mt-1 text-xs text-muted-foreground">{data.facilityName} · Updated {formatInTimeZone(new Date(data.generatedAt), "America/New_York", "h:mma 'ET'")}</p> : null}</div><Button variant="outline" size="sm" onClick={refresh} disabled={loading}><RefreshCw className="mr-2 size-4" />Refresh</Button></header>
    {!facilityId && view !== "people" ? <FacilityGateNotice reason="Select the building whose Workforce you want to review." /> : error ? <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-5"><p>{error}</p><Button variant="outline" onClick={refresh} className="mt-3">Retry</Button></div> : loading || !data ? <div role="status" className="rounded-[16px] border bg-card p-8 text-muted-foreground">Loading Workforce records…</div> : <>
      {view === "today" ? <>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KPITile label="On the clock now" state={data.timeclockEnabled ? metricFromCount({ count: present?.length, loading, error }) : metricNotConfigured("Kiosk off")} info="People whose latest recorded kiosk state is in or on meal." /><KPITile label="Scheduled, no current punch" state={!data.timeclockEnabled ? metricNotConfigured("Not available") : scheduleTimesMissing ? metricNotConfigured("Shift times missing") : metricFromCount({ count: missing?.length, loading, error })} info="People expected from published shifts who are not currently clocked in." /><KPITile label="Here, not scheduled" state={!data.timeclockEnabled ? metricNotConfigured("Not available") : scheduleTimesMissing ? metricNotConfigured("Shift times missing") : metricFromCount({ count: extra?.length, loading, error })} info="People currently clocked in without a matching published shift." /><KPITile label="Staffing standards" state={metricNotConfigured("Not assessed")} info="Verified staffing requirements and evidence are needed to assess coverage." /></div>
        {!data.timeclockEnabled ? <p className="rounded-xl border bg-muted/40 p-4 text-sm">The kiosk is not enabled for this building. Published shifts are shown; attendance cannot yet be compared.</p> : null}
        <div className="grid min-w-0 grid-cols-1 items-start gap-4 xl:grid-cols-[minmax(0,2.5fr)_minmax(240px,1fr)]"><div className="min-w-0 rounded-[16px] border bg-card"><div className="flex flex-wrap items-center justify-between gap-2 border-b p-4"><h2 className="font-semibold">Who’s here and who’s expected</h2><Link className="text-sm font-medium text-primary" href="/admin/staffing/alerts">Coverage and call-outs</Link></div><HorizontalScroll label="Current attendance"><table className="w-full min-w-[640px] text-left text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="p-4">Person</th><th className="p-4">Published shift</th><th className="p-4">Kiosk</th><th className="p-4">Review</th></tr></thead><tbody>{people.filter((p) => p.currentShift || p.attendance === "extra").map((p) => <tr key={p.id} className="border-t"><td className="p-4"><Person person={p}/></td><td className="p-4">{p.currentShift ?? "Not scheduled"}</td><td className="p-4">{clockLabel(p, data.timeclockEnabled)}</td><td className="p-4">{p.attendance === "unknown" ? <Link className="text-primary underline" href="/admin/schedules">Review shift times</Link> : data.timeclockEnabled && p.attendance === "missing" ? <Link className="text-primary underline" href="/admin/staffing/alerts">Review absence</Link> : p.attendance === "called_out" ? "Called out / no-show" : data.timeclockEnabled && p.attendance === "extra" ? <Link className="text-primary underline" href="/admin/schedules">Review schedule</Link> : "—"}</td></tr>)}</tbody></table></HorizontalScroll>{!people.some((p) => p.currentShift || p.attendance === "extra") ? <p className="p-6 text-sm text-muted-foreground">No current published shifts or kiosk attendance recorded.</p> : null}</div>
        <div className="space-y-4"><div className="rounded-[16px] border bg-card p-5"><h2 className="mb-3 flex items-center gap-2 font-semibold"><CalendarDays className="size-4" />Coming up</h2>{people.filter((p) => p.nextShift).slice(0, 8).map((p) => <div key={p.id} className="flex flex-wrap justify-between gap-2 border-t py-3 text-sm"><Person person={p}/><span>{p.nextShift}</span></div>)}{!people.some((p) => p.nextShift) ? <p className="text-sm text-muted-foreground">No upcoming published shifts.</p> : null}<Link href="/admin/schedules" className="mt-3 inline-block text-sm font-medium text-primary">Open schedule →</Link></div><div className="rounded-[16px] border bg-card p-5"><h2 className="mb-3 font-semibold">Before the next payroll</h2><p className="text-sm text-muted-foreground">{exceptionCount.status === "value" ? `${exceptionCount.value} ${exceptionCount.value === 1 ? "person has" : "people have"} recorded punch exceptions in the last completed week.` : "Punch exception totals are unavailable."}</p><Link href="/admin/timecards" className="mt-4 inline-block text-sm font-medium text-primary">Review timecards →</Link><p className="mt-5 border-t pt-4 text-sm text-muted-foreground">Staffing minimums, CPR coverage, and Florida staffing compliance require verified requirements and evidence. This screen does not certify compliance.</p></div></div></div>
      </> : view === "timecards" ? <>
        <div className="flex flex-wrap items-center justify-between gap-3 rounded-[16px] border bg-card p-4"><p className="font-medium">{data.weekStart} – {data.weekEnd}</p><Link href="/admin/timeclock" className={buttonVariants({ variant: "outline", size: "sm" })}>Other periods and uPunch comparison</Link></div>
        <div className="rounded-[16px] border bg-muted/40 p-4 text-sm">Hours here are kiosk review figures for the completed Monday workweek, with punched meals and no rounding. Payroll packets use their own confirmed payroll rules; review and approve the packet in Payroll.</div>
        {exceptions?.length ? <div className="rounded-[16px] border border-amber-600/30 bg-card p-4"><h2 className="font-semibold">Fix these first</h2>{exceptions.map((p) => <Link key={p.id} href={completedWeekTimesheetHref(p.id, data)} className="flex justify-between gap-3 border-t py-3 text-sm text-primary"><span>{p.name}</span><span>{p.exceptions} {p.exceptions === 1 ? "exception" : "exceptions"} · Review →</span></Link>)}</div> : null}
        <HorizontalScroll label="Workforce records" className="rounded-[16px] border bg-card"><table className="w-full min-w-[640px] text-left text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="p-4">Person</th><th className="p-4">Scheduled hours</th><th className="p-4">Worked hours</th><th className="p-4">Review</th></tr></thead><tbody>{people.map((p) => <tr key={p.id} className="border-t"><td className="p-4"><Person person={p}/></td><td className="p-4 tabular-nums">{p.scheduleMissing ? "No published schedule" : p.scheduledMinutes === null ? "Shift times not recorded" : formatMinutesCompact(p.scheduledMinutes)}</td><td className="p-4 tabular-nums">{p.timeIncomplete ? "Needs correction" : p.workedMinutes === null ? "No kiosk time" : formatMinutesCompact(p.workedMinutes)}</td><td className="p-4"><Link className="text-primary underline" href={completedWeekTimesheetHref(p.id, data)}>{p.exceptions ? `${p.exceptions} to fix` : "Review punches"}</Link></td></tr>)}</tbody></table></HorizontalScroll>
      </> : <>
        <div className="flex flex-wrap gap-2"><Link href="/admin/staff/new" className={buttonVariants({ size: "sm" })}>Add person</Link></div>
        {!data.allFacilities ? <div className="rounded-[16px] border bg-card p-5"><h2 className="mb-3 flex items-center gap-2 font-semibold"><FileCheck className="size-4" />Due or expiring within 60 days</h2>{due?.length ? due.slice(0, 12).map((d) => <Link key={`${d.person.id}-${d.title}`} className="flex flex-wrap justify-between gap-2 border-t py-3 text-sm text-primary" href={`/admin/staff/${d.person.id}/employee-file`}><span>{d.person.name} · {d.title}</span><span>{d.date} →</span></Link>) : <p className="text-sm text-muted-foreground">No dated requirements due in the records loaded. Missing or unconfigured requirements still need review below.</p>}</div> : null}
        <Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Find a person or role" aria-label="Find a person or role" className="max-w-md" />
        <HorizontalScroll label="Workforce records" className="rounded-[16px] border bg-card"><table className="w-full min-w-[640px] text-left text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="p-4">Person</th>{data.allFacilities ? <th className="p-4">Facilities</th> : <><th className="p-4">Next shift</th><th className="p-4">Last week</th><th className="p-4">Employee file</th></>}<th className="p-4">Access</th></tr></thead><tbody>{people.map((p) => <tr key={p.id} className="border-t"><td className="p-4"><Person person={p}/></td>{data.allFacilities ? <td className="p-4">{p.facilityNames?.join(", ") || "No current facility assignment"}</td> : <><td className="p-4">{p.nextShift ?? "No published shift"}</td><td className="p-4">{p.timeIncomplete ? "Needs correction" : p.workedMinutes === null ? "No kiosk time" : formatMinutesCompact(p.workedMinutes)}</td><td className="p-4"><Link href={`/admin/staff/${p.id}/employee-file`} className="text-primary underline">{p.fileStatus}</Link></td></>}<td className="p-4"><Link href={`/admin/staff/${p.id}`} className="text-primary underline">Profile / PIN</Link></td></tr>)}</tbody></table></HorizontalScroll>
      </>}
      {people.length === 0 ? <p className="rounded-xl border bg-card p-6 text-sm text-muted-foreground"><Users className="mb-2 size-5" />{search ? "No people match this search." : data?.allFacilities ? "No staff records found across the facilities you can access." : "No staff records found for this facility."}</p> : null}
      <footer className="flex flex-wrap gap-4 border-t pt-4 text-xs text-muted-foreground"><Link href="/admin/time-records">Legacy time records</Link><Link href="/admin/timeclock">Kiosk ledger and settings</Link><Link href="/admin/shift-swaps">Shift requests</Link><span className="inline-flex items-center gap-1"><Clock className="size-3" />Times shown in Eastern time</span></footer>
    </>}
  </section>;
}
function Person({ person }: { person: WorkforcePerson }) { return <div><Link className="font-semibold hover:text-primary hover:underline" href={`/admin/staff/${person.id}`}>{person.name}</Link><p className="mt-0.5 text-xs capitalize text-muted-foreground">{person.role}</p></div>; }
