import re, subprocess, sys
PSQL = ["/tmp/loc-psql.sh", "-d", "haven"]
def q(sql):
    out = subprocess.run(PSQL + ["-F", "\x1f", "-R", "\x1e", "-c", sql], capture_output=True, text=True, check=True).stdout
    return [[f.strip("\n") for f in r.split("\x1f")] for r in out.split("\x1e") if r.strip()]

LIST_BEFORE = re.compile(r"[\[(,]\s*$")
LIST_AFTER = re.compile(r"^\s*[,\])]")

def swap(text, where):
    # nurse -> med_tech: every role literal.
    text = re.sub(r"'nurse'", "'med_tech'", text)
    # cook joins dietary wherever dietary is listed.
    out, i = [], 0
    for m in re.finditer(r"'dietary'((?:::[a-z_]+)?)", text):
        before, after = text[:m.start()], text[m.end():]
        if not LIST_BEFORE.search(before) or not LIST_AFTER.match(after):
            sys.exit(f"dietary outside a list in {where}: ...{before[-60:]}|{m.group(0)}|{after[:40]}...")
        out.append(text[i:m.end()]); out.append(f", 'cook'{m.group(1)}"); i = m.end()
    out.append(text[i:])
    return "".join(out)

def ident(s): return '"' + s.replace('"', '""') + '"'

print("""-- Nurse is not used at Circle of Life (Brian, 2026-09-22): "Nurse is to not be used.
-- Use Med-Tech instead." and "make sure Cook and Housekeeper are added" — as login
-- roles and as staff positions, everywhere.
--
-- GENERATED by scripts/role-sweep/generate-nurse-to-med-tech.py from a full replay
-- of supabase/migrations (through 460), then checked against production: the policy
-- definitions fingerprint-match; the function definitions match except one comment.
-- Static on purpose — no catalog-driven loop runs on the hosted database.
--
--   * every RLS policy and every public/haven function that names 'nurse' as a role
--     now names 'med_tech' instead (med_tech inherits exactly what nurse had);
--   * every place that lists 'dietary' also lists 'cook' (a cook has a dietary
--     worker's access, including being excluded wherever dietary is excluded);
--   * haven.role_tier: med_tech takes nurse's tier, cook takes dietary's;
--   * role-keyed configuration rows move from nurse to med_tech (merged, never
--     narrowed) and dietary rows are copied for cook;
--   * the one active nurse login becomes med_tech. user_profiles is authoritative
--     for tokens (326); the role change advances auth_claim_version, so the next
--     token carries the new role.
-- History is not rewritten: audit rows, delivery receipts and actor_role columns
-- keep 'nurse' where nurse is what happened.
BEGIN;
""")

pol = q("""select schemaname, tablename, policyname, coalesce(qual,''), coalesce(with_check,'')
 from pg_policies where (coalesce(qual,'')||coalesce(with_check,'')) ~ '''(nurse|dietary)''' order by 1,2,3""")
print(f"-- {len(pol)} policies")
for s, t, p, qual, chk in pol:
    parts = []
    qual, chk = qual.strip(), chk.strip()
    if qual: parts.append(f"USING ({swap(qual, p)})")
    if chk: parts.append(f"WITH CHECK ({swap(chk, p)})")
    print(f"ALTER POLICY {ident(p)} ON {ident(s)}.{ident(t)}\n  " + "\n  ".join(parts) + ";")

fns = q("""select p.oid, n.nspname||'.'||p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace
 where n.nspname in ('public','haven') and p.prosrc ~ '''(nurse|dietary)''' and p.proname <> 'role_tier' order by 2, 1""")
print(f"\n-- {len(fns)} functions (role_tier is written out by hand below)")
for oid, name in fns:
    d = q(f"select pg_get_functiondef({oid})")[0][0]
    print(swap(d, name).rstrip() + ";\n")

print("""
CREATE OR REPLACE FUNCTION haven.role_tier(p_role public.app_role)
 RETURNS integer LANGUAGE sql IMMUTABLE SET search_path TO ''
AS $function$ SELECT CASE p_role WHEN 'owner' THEN 100 WHEN 'org_admin' THEN 90 WHEN 'facility_admin' THEN 80 WHEN 'manager' THEN 70 WHEN 'coordinator' THEN 60 WHEN 'admin_assistant' THEN 50 WHEN 'med_tech' THEN 50 WHEN 'nurse' THEN 50 WHEN 'dietary' THEN 40 WHEN 'cook' THEN 40 WHEN 'maintenance_role' THEN 40 WHEN 'broker' THEN 30 WHEN 'housekeeper' THEN 30 WHEN 'caregiver' THEN 20 WHEN 'dietary_aide' THEN 20 WHEN 'family' THEN 10 ELSE 0 END $function$;
""")
print("""
-- Role-keyed configuration: nurse moves to med_tech (merged, never narrowed); cook copies dietary.
INSERT INTO public.role_permissions(app_role, feature, permission_level, description)
SELECT 'med_tech', n.feature, n.permission_level, n.description FROM public.role_permissions n
WHERE n.app_role = 'nurse' AND NOT EXISTS (SELECT 1 FROM public.role_permissions m WHERE m.app_role = 'med_tech' AND m.feature = n.feature);
DELETE FROM public.role_permissions WHERE app_role = 'nurse';
INSERT INTO public.role_permissions(app_role, feature, permission_level, description)
SELECT 'cook', d.feature, d.permission_level, d.description FROM public.role_permissions d
WHERE d.app_role = 'dietary' AND NOT EXISTS (SELECT 1 FROM public.role_permissions c WHERE c.app_role = 'cook' AND c.feature = d.feature);

UPDATE public.search_tool_policies m SET enabled = m.enabled OR n.enabled, updated_at = now()
FROM public.search_tool_policies n
WHERE m.app_role = 'med_tech' AND n.app_role = 'nurse' AND n.organization_id = m.organization_id AND n.tool_name = m.tool_name;
INSERT INTO public.search_tool_policies(organization_id, tool_name, tool_tier, app_role, enabled)
SELECT n.organization_id, n.tool_name, n.tool_tier, 'med_tech', n.enabled FROM public.search_tool_policies n
WHERE n.app_role = 'nurse' AND NOT EXISTS (SELECT 1 FROM public.search_tool_policies m
  WHERE m.app_role = 'med_tech' AND m.organization_id = n.organization_id AND m.tool_name = n.tool_name);
DELETE FROM public.search_tool_policies WHERE app_role = 'nurse';
INSERT INTO public.search_tool_policies(organization_id, tool_name, tool_tier, app_role, enabled)
SELECT d.organization_id, d.tool_name, d.tool_tier, 'cook', d.enabled FROM public.search_tool_policies d
WHERE d.app_role = 'dietary' AND NOT EXISTS (SELECT 1 FROM public.search_tool_policies c
  WHERE c.app_role = 'cook' AND c.organization_id = d.organization_id AND c.tool_name = d.tool_name);

-- Arrays: replace nurse, keep order, drop the duplicate if med_tech was already listed; add cook beside dietary.
CREATE FUNCTION pg_temp.role_list_swap(p text[]) RETURNS text[] LANGUAGE sql IMMUTABLE AS $$
  SELECT array_agg(r ORDER BY o) FROM (
    SELECT DISTINCT ON (r) r, o FROM (
      SELECT CASE WHEN e = 'nurse' THEN 'med_tech' ELSE e END r, o * 2 o FROM unnest(p) WITH ORDINALITY u(e, o)
      UNION ALL SELECT 'cook', o * 2 + 1 FROM unnest(p) WITH ORDINALITY u(e, o) WHERE e = 'dietary'
    ) s ORDER BY r, o) d
$$;
UPDATE public.flow_workflow_definitions SET roles_allowed = pg_temp.role_list_swap(roles_allowed)
  WHERE roles_allowed && ARRAY['nurse','dietary'];
UPDATE public.documents SET role_tags = pg_temp.role_list_swap(role_tags)
  WHERE role_tags && ARRAY['nurse','dietary'];
UPDATE public.assessment_templates SET required_role = pg_temp.role_list_swap(required_role::text[])::public.app_role[]
  WHERE required_role && ARRAY['nurse','dietary']::public.app_role[];

-- The nurse login(s) become med_tech. The profile row is what the token hook reads.
UPDATE auth.users u SET raw_app_meta_data = coalesce(u.raw_app_meta_data, '{}'::jsonb) || jsonb_build_object('app_role', 'med_tech')
  FROM public.user_profiles p WHERE p.id = u.id AND p.app_role = 'nurse';
UPDATE public.user_profiles SET app_role = 'med_tech', updated_at = now() WHERE app_role = 'nurse';

DO $check$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_policies WHERE (coalesce(qual,'')||coalesce(with_check,'')) ~ '''nurse''') THEN
    RAISE EXCEPTION 'A policy still names nurse';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname IN ('public','haven') AND p.prosrc ~ '''nurse''' AND p.proname <> 'role_tier') THEN
    RAISE EXCEPTION 'A function still names nurse';
  END IF;
  IF EXISTS (SELECT 1 FROM public.user_profiles WHERE app_role = 'nurse' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'A nurse login remains';
  END IF;
END
$check$;

NOTIFY pgrst, 'reload schema';
COMMIT;""")
