-- COL-593: the two pg_cron jobs behind the Facility Operator Home.
--
-- Run this by hand in an admin session on the hosted project after migration
-- 459 is applied and the oce-task-scheduler Edge Function is deployed with the
-- COL-568 asset-schedule change. Do not run it from the build. Placeholders are
-- in angle brackets. Pattern: scripts/census/cron-schedules.sql.
--
-- Before running, create the Vault secret once (name only; the value is the
-- OCE_TASK_SCHEDULER_SECRET you set on the Edge Function):
--
--   select vault.create_secret('<the OCE_TASK_SCHEDULER_SECRET value>', 'oce_task_scheduler_secret');
--
-- The function verifies x-cron-secret against OCE_TASK_SCHEDULER_SECRET and
-- returns 401 otherwise (supabase/functions/oce-task-scheduler/index.ts).
--
-- Both jobs are idempotent: an existing job with the same name is unscheduled
-- first, so re-running this file replaces rather than duplicates.

-- ---------------------------------------------------------------------------
-- 1. Generate the Homewood operator queue for the coming week.
--
-- One live behaviour per week at Homewood (DEC-2026-09-21-11): the body pins
-- the scheduler to Homewood and to the `safety` category, which today holds
-- exactly one template — the generator weekly run (migration 459). Widening
-- the category list is how the next approved rows go live; nothing else in the
-- org-wide seed is generated by this job.
--
-- pg_cron runs in UTC. 09:00 UTC is 05:00 New York in summer and 04:00 in
-- winter; either is before anyone is on duty. The range is today .. today+7
-- so "Later this week" is populated and the scheduler's own dedupe (activity +
-- date + shift) keeps re-runs from duplicating.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from cron.job where jobname = 'oce-task-scheduler-homewood-daily') then
    perform cron.unschedule('oce-task-scheduler-homewood-daily');
  end if;
end
$$;

select cron.schedule(
  'oce-task-scheduler-homewood-daily',
  '0 9 * * *',
  $$
  select net.http_post(
    url := 'https://<project-ref>.supabase.co/functions/v1/oce-task-scheduler',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', (select decrypted_secret from vault.decrypted_secrets where name = 'oce_task_scheduler_secret')
    ),
    body := jsonb_build_object(
      'facility_id', '00000000-0000-0000-0002-000000000003',
      'category', jsonb_build_array('safety'),
      'date_from', to_char((now() at time zone 'America/New_York')::date, 'YYYY-MM-DD'),
      'date_to', to_char((now() at time zone 'America/New_York')::date + 7, 'YYYY-MM-DD')
    ),
    -- pg_net's 5-second default is shorter than a run (COL-547).
    timeout_milliseconds := 60000
  );
  $$
);

-- Retain the actual HTTP outcome, not just pg_cron's SQL success (COL-253).
select job_monitor.instrument(jobid) from cron.job where jobname = 'oce-task-scheduler-homewood-daily';

-- ---------------------------------------------------------------------------
-- 2. End-of-day escalation sweep (COL-593 §5.4).
--
-- Pure SQL, no Edge Function, no secret. Every 15 minutes it asks each
-- facility whether its operator day has ended (facilities.operator_end_of_day_local,
-- default 17:00 local) and escalates what is still open to level 1 for the
-- Facility Executive. Idempotent per row. Delivery is the "Escalated to you"
-- panel on the executive page; push/email waits on COL-152.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from cron.job where jobname = 'home-escalate-uncleared-15m') then
    perform cron.unschedule('home-escalate-uncleared-15m');
  end if;
end
$$;

select cron.schedule(
  'home-escalate-uncleared-15m',
  '*/15 * * * *',
  $$select public.home_escalate_uncleared();$$
);

-- Pure SQL, so it is registered, not rewritten; the monitor reads its
-- cron.job_run_details (COL-253). Without this it reports not_monitored (COL-547).
select job_monitor.register_native(jobid) from cron.job where jobname = 'home-escalate-uncleared-15m';

-- ---------------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------------
-- select jobid, jobname, schedule, active from cron.job
--  where jobname in ('oce-task-scheduler-homewood-daily', 'home-escalate-uncleared-15m');
-- select jobname, status, return_message, start_time from cron.job_run_details
--  where jobname = 'oce-task-scheduler-homewood-daily' order by start_time desc limit 5;
--
-- Homewood's generator rows for the coming week:
-- select assigned_shift_date, assigned_shift, status, due_at, authority_class
--   from public.operation_task_instances
--  where facility_id = '00000000-0000-0000-0002-000000000003' and deleted_at is null
--  order by assigned_shift_date desc limit 10;
