-- Smart Rounding scheduled ticks, spec 25A section 9.
--
-- The whole activation sequence for the module, in one place, all of it
-- commented out. Nothing here is applied by any gate and nothing here runs from
-- a build.
--
-- The repository holds no cron.schedule statement in any migration, and this
-- file is deliberately not one either: a schedule that arrives with a migration
-- starts firing against whichever project the migration lands on, including a
-- staging rehearsal. Run these against the hosted project by hand, after the
-- function is deployed and its secret is set.
--
-- ---------------------------------------------------------------------------
-- READ THIS BEFORE YOU SCHEDULE ANYTHING: STAGING IS ALREADY LIVE
-- ---------------------------------------------------------------------------
-- Activation record: 2026-09-19. Verify live state before changing schedules.
-- Staging and production both run the four Smart Rounding workers. Production
-- already had legacy generator/escalation jobs; activation updates those jobs
-- in place, preserving their history and avoiding duplicate dispatch.
--
-- Existing job names (names retain their legacy labels; read actual schedules):
--   production: observation-task-generator-4h, observation-escalation-15m,
--               smart-rounding-cadence-activator, smart-rounding-watchlist,
--               monitoring-order-expiry-daily
--   staging:    smart-rounding-task-generator, smart-rounding-escalation,
--               smart-rounding-cadence-activator, smart-rounding-watchlist,
--               monitoring-order-expiry-daily
--
-- Read jobid, jobname, schedule, active from cron.job first. Reuse job IDs with
-- cron.alter_job; do not blindly install the alternative example names below.
-- Live HTTP jobs read their worker secret from Supabase Vault at runtime and
-- set timeout_milliseconds := 120000. Never paste secret values into evidence.
-- See HANDOFFS/2026-09-19__smart-rounding-production-activation.md for proof.
--
-- Before running any of it, confirm which project the CLI is linked to.
-- Production and Haven HFO Staging are different buildings' worth of alerts,
-- and supabase/.temp/project-ref in the shared checkout follows whatever was
-- last rehearsed.
--
-- ---------------------------------------------------------------------------
-- ORDER OF ACTIVATION
-- ---------------------------------------------------------------------------
-- Within a minute where several fire, they want this order, and the cron
-- offsets below keep them apart rather than relying on luck:
--
--   :02  cadence-version-activator      a version takes force
--   :03  observation-task-generator     the board is built from the version in force
--   :04  observation-escalation-engine  the ladder walks tasks that already exist
--   :07  watchlist-signal-engine        signals read what the day recorded
--   03:20 (daily) expire_monitoring_orders
--
-- Run the activator before the generator, so the generator sees the version
-- that has just taken force rather than the one it replaced. Run the generator
-- before the escalation engine, so the engine never reads a queue the generator
-- is halfway through writing.

-- ---------------------------------------------------------------------------
-- Part 5: watchlist-signal-engine
--
-- Evaluates every enabled Watchlist rule at every building in the organization,
-- and queues the Acute push for anything newly in the Acute band.
--
-- Once an hour is the right cadence for this and not more often: every rule in
-- the table measures over days, so a five minute tick would re-read the same
-- spans twelve times an hour to reach the same answer, and the Acute push is
-- stamped once per signal anyway. It is also idempotent, so a missed tick costs
-- nothing but the delay.
--
-- Fill in the organization id, the function URL and the secret before running.
-- The secret is the value of the WATCHLIST_SIGNAL_SECRET function secret; do
-- not paste it into a migration, a commit or a ticket.
-- ---------------------------------------------------------------------------
-- select cron.schedule(
--   'watchlist-signal-engine-hourly',
--   '7 * * * *',
--   $$
--   select net.http_post(
--     url     := '<project-functions-url>/watchlist-signal-engine',
--     headers := jsonb_build_object(
--                  'Content-Type',  'application/json',
--                  'x-cron-secret', '<WATCHLIST_SIGNAL_SECRET>'),
--     body    := jsonb_build_object('organization_id', '<organization-id>')
--   );
--   $$
-- );

-- To take it back off:
-- select cron.unschedule('watchlist-signal-engine-hourly');

-- To run one building once, without a schedule, add "facility_id" to the body.

-- ---------------------------------------------------------------------------
-- Part 7: cadence-version-activator
--
-- Puts every scheduled cadence and escalation version into force once its
-- effective_from has passed, closing the outgoing version's effective_to at
-- exactly that instant, and asks the task generator to rebuild the board for
-- any building where pending tasks were cancelled.
--
-- Every five minutes, and this one does want to be that often. The default
-- effective timing is the next shift boundary, and a change that takes effect
-- at a shift boundary has to be in force before the incoming shift starts
-- reading its board. An hourly tick would leave a building working the old
-- schedule for up to an hour after the administrator was told the new one was
-- live. It is idempotent and cheap: with nothing scheduled it reads two indexed
-- queries and writes nothing.
--
-- Run it BEFORE observation-task-generator, not after. The Part 7 note here
-- said "after" and then gave the reason for "before" -- the generator has to
-- see the version that has just taken force rather than the one it replaced --
-- so the sentence is corrected rather than the offset. An offset of 2 against
-- the generator's 3 is what puts it first.
--
-- Fill in the organization id, the function URL and the secret before running.
-- The secret is the value of the CADENCE_VERSION_ACTIVATOR_SECRET function
-- secret; do not paste it into a migration, a commit or a ticket.
--
-- OBSERVATION_TASK_GENERATOR_URL and OBSERVATION_TASK_GENERATOR_SECRET are
-- optional function secrets on the activator. Without them the tick still
-- activates versions and reports regeneration_skipped_reason as
-- no_generator_endpoint_configured, which is honest rather than silent, and the
-- generator picks the change up on its own next run.
-- ---------------------------------------------------------------------------
-- select cron.schedule(
--   'cadence-version-activator-5min',
--   '2-59/5 * * * *',
--   $$
--   select net.http_post(
--     url     := '<project-functions-url>/cadence-version-activator',
--     headers := jsonb_build_object(
--                  'Content-Type',  'application/json',
--                  'x-cron-secret', '<CADENCE_VERSION_ACTIVATOR_SECRET>'),
--     body    := jsonb_build_object('organization_id', '<organization-id>')
--   );
--   $$
-- );

-- To take it back off:
-- select cron.unschedule('cadence-version-activator-5min');

-- To activate one building once, without a schedule, add "facility_id" to the body.


-- ---------------------------------------------------------------------------
-- Part 1: observation-task-generator
--
-- Builds the board. Reads the cadence version in force for the service date at
-- every building in the organization, projects its enabled windows across the
-- active roster, and stamps cadence_version_id on every task it writes. Skips a
-- resident under an active Monitoring Order, whose checks come from the order
-- instead.
--
-- Every 15 minutes, and the reason is the horizon rather than the cadence: the
-- generator writes one shift ahead, so it does not need to run often to keep
-- the board full. What it needs is to run soon after something changes -- an
-- admission, a discharge, a Monitoring Order cancelled, a cadence version
-- activated -- and 15 minutes is the longest an operator should wait to see the
-- board catch up. It is idempotent per (resident_id, window_key, service_date),
-- so a tick that has nothing to do writes nothing.
--
-- It answers HTTP 207 with ok:false when any building failed or has no cadence
-- in force. A facility with no cadence is a failure and not a quiet success, so
-- a monitor on this endpoint should treat 207 as an alert.
--
-- Fill in the organization id, the function URL and the secret before running.
-- The secret is the value of the OBSERVATION_TASK_GENERATOR_SECRET function
-- secret; do not paste it into a migration, a commit or a ticket.
-- ---------------------------------------------------------------------------
-- select cron.schedule(
--   'observation-task-generator-15min',
--   '3-59/15 * * * *',
--   $$
--   select net.http_post(
--     url     := '<project-functions-url>/observation-task-generator',
--     headers := jsonb_build_object(
--                  'Content-Type',  'application/json',
--                  'x-cron-secret', '<OBSERVATION_TASK_GENERATOR_SECRET>'),
--     body    := jsonb_build_object('organization_id', '<organization-id>')
--   );
--   $$
-- );

-- To take it back off:
-- select cron.unschedule('observation-task-generator-15min');

-- On staging this job already exists as 'smart-rounding-task-generator'. To
-- change its schedule rather than add a second one:
-- select cron.alter_job((select jobid from cron.job where jobname = 'smart-rounding-task-generator'), schedule := '3-59/15 * * * *');

-- To generate one building once, without a schedule, add "facility_id" to the body.

-- ---------------------------------------------------------------------------
-- Part 4: observation-escalation-engine
--
-- Walks the escalation ladder. Reads observation_escalations_due, resolves each
-- task's window close through public.observation_task_window_close, and fires
-- the rung the escalation version in force defines for that offset, through the
-- channels and recipient roles that version's rows carry.
--
-- Every five minutes, and this one genuinely wants to be that often: the
-- seeded ladder's first step lands before the window closes, and a nudge that
-- arrives twenty minutes late is not a nudge. Each rung writes one
-- observation_escalation_dispatches row per (task_id, rung_key), which is the
-- idempotency anchor, so a duplicate tick cannot double notify.
--
-- The due read returns up to 500 rows and the engine fires them one round trip
-- at a time, so minutes can separate the read from the call. A rung fired
-- against a task somebody completed in between answers
-- {"fired": false, "reason": "task_completed"} and writes nothing. Do not
-- shorten the interval to try to close that gap; the guard is the fix.
--
-- Fill in the organization id, the function URL and the secret before running.
-- The secret is the value of the OBSERVATION_ESCALATION_SECRET function secret.
-- DISPATCH_PUSH_SECRET and the SMS credentials are separate function secrets;
-- without them those channels record a skipped delivery with a reason rather
-- than failing the tick.
-- ---------------------------------------------------------------------------
-- select cron.schedule(
--   'observation-escalation-engine-5min',
--   '4-59/5 * * * *',
--   $$
--   select net.http_post(
--     url     := '<project-functions-url>/observation-escalation-engine',
--     headers := jsonb_build_object(
--                  'Content-Type',  'application/json',
--                  'x-cron-secret', '<OBSERVATION_ESCALATION_SECRET>'),
--     body    := jsonb_build_object('organization_id', '<organization-id>')
--   );
--   $$
-- );

-- To take it back off:
-- select cron.unschedule('observation-escalation-engine-5min');

-- On staging this job already exists as 'smart-rounding-escalation'.
-- select cron.alter_job((select jobid from cron.job where jobname = 'smart-rounding-escalation'), schedule := '4-59/5 * * * *');

-- To walk one building once, without a schedule, add "facility_id" to the body.

-- ---------------------------------------------------------------------------
-- Part 3: Monitoring Order expiry
--
-- public.expire_monitoring_orders() closes every order whose end date has
-- passed. It never expires an open ended order whatever its review date says: a
-- past review date is a Watchlist signal about a decision nobody made, not an
-- expiry, and expiring it would quietly drop the resident back to the standard
-- cadence without anybody deciding that.
--
-- This is the only tick in the module that is plain SQL rather than an HTTP
-- post. There is no function to deploy, no secret to set and no URL to fill in,
-- because nothing outside the database is involved.
--
-- Once a day at 03:20 America/New_York. Both hosted cron schedulers use GMT;
-- the two UTC candidate hours plus the local-time guard handle daylight saving
-- time without changing the timezone of unrelated jobs. An order's end date is
-- a date, so the finest granularity that means anything is daily, and running
-- it at 03:20 puts the status change before the morning shift reads the board
-- rather than in the middle of their round. It returns the number of rows it
-- closed.
--
-- expire_monitoring_orders is granted to service_role only; a cron job runs as
-- its owner, so schedule this as a role that can execute it.
-- ---------------------------------------------------------------------------
-- select cron.schedule(
--   'monitoring-order-expiry-daily',
--   '20 7,8 * * *',
--   $$ select public.expire_monitoring_orders()
--      where to_char(now() at time zone 'America/New_York', 'HH24:MI') = '03:20'; $$
-- );

-- To take it back off:
-- select cron.unschedule('monitoring-order-expiry-daily');

-- To close what is due right now, without a schedule:
-- select public.expire_monitoring_orders();

-- ---------------------------------------------------------------------------
-- What is scheduled, and whether it is working
-- ---------------------------------------------------------------------------
-- Every job in the module, with its schedule and whether it is on:
-- select jobid, jobname, schedule, active from cron.job order by jobname;

-- The last few runs of each, which is the only way to notice a job that is
-- installed, active and failing every time:
-- select j.jobname, d.status, d.return_message, d.start_time
--   from cron.job_run_details d
--   join cron.job j on j.jobid = d.jobid
--  order by d.start_time desc
--  limit 40;
