"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { corporateDeliverableCommandSchema, corporateDeliverableHistorySchema, corporateDeliverableKeys, corporateDeliverablesReplySchema, type CorporateDeliverableHistory, type CorporateDeliverablesReply } from "@/lib/operations/corporate-deliverables";
import { CONTROL, DateTimeInput, typedValues } from "./work-inputs";
type Props={taskId:string;activityKey:string|null|undefined;facilityId:string;actorId:string;subjectId:string|null;timezone:string};
export function CorporateDeliverablePanel(props:Props){if(!corporateDeliverableKeys.includes(props.activityKey as never))return null;return <Panel key={`${props.taskId}:${props.facilityId}:${props.actorId}:${props.subjectId}`} {...props}/>;}
function Panel({taskId,facilityId,timezone}:Props){
 const [opened,setOpened]=useState(false),[start,setStart]=useState(""),[end,setEnd]=useState(""),[data,setData]=useState<CorporateDeliverablesReply|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[pending,setPending]=useState<string|null>(null),[attempt,setAttempt]=useState(0),[coverageSource,setCoverageSource]=useState(""),[selectedSites,setSelectedSites]=useState<string[]>([]),[presentationMode,setPresentationMode]=useState<"none"|"date"|"datetime">("none"),[presentationValue,setPresentationValue]=useState(""),[presentationSource,setPresentationSource]=useState("");
 const alive=useRef(true),generation=useRef(0),read=useRef<AbortController|null>(null),command=useRef<AbortController|null>(null),sending=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;read.current?.abort();command.current?.abort();};},[]);
 const validate=useCallback((raw:unknown)=>{const reply=corporateDeliverablesReplySchema.parse(raw);if(reply.task_id!==taskId||reply.period_start!==start||reply.period_end!==end||!reply.complete||reply.front_office_boundary!=="standup_weekly_allowlist_only")throw Error("Wrong corporate scope");return reply;},[taskId,start,end]);
 useEffect(()=>{if(!opened||!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))return;const abort=new AbortController();read.current=abort;const version=++generation.current;setData(null);setError("");void fetch(`/api/admin/operations/corporate-deliverables?${new URLSearchParams({task_id:taskId,period_start:start,period_end:end})}`,{credentials:"same-origin",cache:"no-store",signal:abort.signal}).then(async response=>{if(!response.ok)throw Error("Unavailable");const reply=validate(await response.json());if(alive.current&&!abort.signal.aborted&&version===generation.current)setData(reply);}).catch(()=>{if(alive.current&&!abort.signal.aborted&&version===generation.current){setData(null);setError("Corporate coverage is unavailable under current source and site authority. No partial result is treated as complete.");}});return()=>abort.abort();},[opened,start,end,taskId,attempt,validate]);
 async function send(body:string){if(sending.current)return;sending.current=true;read.current?.abort();generation.current++;setBusy(true);setPending(body);setData(null);setError("");command.current=new AbortController();try{const response=await fetch("/api/admin/operations/corporate-deliverables",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body,signal:command.current.signal});if(!response.ok){if(response.status<500&&![408,429].includes(response.status)){setPending(null);setError("Corporate change was rejected. Reload current detail before another action.");return;}throw Error("Unknown");}const reply=validate(await response.json());if(alive.current){setPending(null);setData(reply);}}catch{if(alive.current)setError("Corporate save result is unknown. Retry the identical request before another change.");}finally{sending.current=false;if(alive.current)setBusy(false);}}
 function submit(action:string,payload:Record<string,unknown>){if(busy||pending)return;try{void send(JSON.stringify(corporateDeliverableCommandSchema.parse({action,task_id:taskId,request_key:crypto.randomUUID(),...payload})));}catch{setError("Complete the attributable fields and use the actual date precision.");}}
 const current=data?.sites.find(site=>site.facility_id===facilityId)?.expectation??null;
 return <details onToggle={event=>{if(event.currentTarget.open)setOpened(true);}}><summary className={`${CONTROL} cursor-pointer`}>Corporate deliverables and meeting history</summary><div className="space-y-3 pt-3">
  <p>Haven records preparation and operator evidence only. It does not send email, contact a provider, call Front Office, or establish operating acceptance.</p>
  <div className="grid gap-3 sm:grid-cols-2"><label>Period start<input className={CONTROL} type="date" value={start} disabled={!!pending} onChange={e=>setStart(e.target.value)}/></label><label>Period end<input className={CONTROL} type="date" value={end} disabled={!!pending} onChange={e=>setEnd(e.target.value)}/></label></div>
  {error?<p role="alert">{error}</p>:null}{pending?<button className={CONTROL} disabled={busy} onClick={()=>void send(pending)}>Retry identical corporate request</button>:null}
  {data?<><p>{data.component_label}. {data.reason}</p><p>Front Office boundary: existing allowlisted Stand Up aggregate only. Corporate packet details stay in Haven.</p>
   {data.coverage?<><p>Expected site set version {data.coverage.version}: {data.coverage.facility_ids.length} site(s). Captured from: {data.coverage.provenance}</p><ul>{data.sites.map(site=><li key={site.facility_id}>{data.available_sites.find(item=>item.id===site.facility_id)?.label??(site.status==='unavailable'?'Site label withheld':site.facility_id)}: {site.status}{site.expectation?` · ${site.expectation.current_state}`:""}</li>)}</ul><CoverageEditor key={data.coverage.revision} currentFacilityId={facilityId} coverage={data.coverage} availableSites={data.available_sites} busy={busy||!!pending} submit={submit} start={start} end={end}/></>:<form className="space-y-2" onSubmit={event=>{event.preventDefault();submit("register",{period_start:start,period_end:end,period_provenance:coverageSource,expected_facility_ids:selectedSites});}}><p>Expected site set: Unknown. Select every site expected for this component and cite the source; incomplete registration is never inferred.</p>{data.available_sites.map(site=><label className="block" key={site.id}><input type="checkbox" checked={selectedSites.includes(site.id)} onChange={event=>setSelectedSites(current=>event.target.checked?[...current,site.id]:current.filter(id=>id!==site.id))}/> {site.label}</label>)}<label className="block">Expected coverage source<input className={CONTROL} value={coverageSource} onChange={event=>setCoverageSource(event.target.value)}/></label><button className={CONTROL} disabled={busy||!!pending||!coverageSource||selectedSites.length===0}>Register expected site set</button></form>}
   {data.coverage&&!current&&data.coverage.facility_ids.includes(facilityId)?<button className={CONTROL} disabled={busy||!!pending} onClick={()=>submit("register",{period_start:start,period_end:end,period_provenance:data.coverage!.provenance,expected_facility_ids:data.coverage!.facility_ids})}>Register this task site in the expected set</button>:null}
   {!data.coverage_complete&&data.coverage?<p role="alert">Protected detail is withheld because every expected site is not currently readable.</p>:null}
   {current?<ExpectationActions key={`${current.revision}:${current.current_version_id??"none"}`} taskId={taskId} expectation={current} issueCandidates={data.issue_candidates} busy={busy||!!pending} submit={submit}/>:null}
   {data.coverage&&data.coverage_complete?<form className="space-y-2" onSubmit={event=>{event.preventDefault();let presented_at:null|string=null,presented_on:null|string=null;try{if(presentationMode==='datetime')presented_at=String(typedValues([{key:'presented_at',label:'Presented at',type:'datetime',required:true}],{presented_at:presentationValue},timezone).presented_at);else if(presentationMode==='date')presented_on=presentationValue;}catch{setError('Enter a valid facility presentation date and time.');return;}submit("capture_meeting",{period_start:start,period_end:end,coverage_revision:data.coverage!.revision,presented_at,presented_on,presentation_provenance:presentationMode==='none'?null:presentationSource});}}><label>Presentation evidence precision<select className={CONTROL} value={presentationMode} onChange={event=>{setPresentationMode(event.target.value as typeof presentationMode);setPresentationValue("");}}><option value="none">Capture only; no meeting occurrence asserted</option><option value="date">Actual presented date</option><option value="datetime">Actual presented date and time</option></select></label>{presentationMode==='date'?<label>Presented date<input className={CONTROL} type="date" value={presentationValue} onChange={event=>setPresentationValue(event.target.value)}/></label>:presentationMode==='datetime'?<DateTimeInput id="corporate-presented-at" timezone={timezone} label="Presented at" value={presentationValue} onChange={setPresentationValue}/>:null}{presentationMode!=='none'?<label>Presentation source<input className={CONTROL} value={presentationSource} onChange={event=>setPresentationSource(event.target.value)}/></label>:null}<button className={CONTROL} disabled={busy||!!pending||(presentationMode!=='none'&&(!presentationValue||!presentationSource))}>Capture current meeting view</button></form>:null}
   <details><summary>Immutable meeting captures</summary>{data.meetings.length?<ul>{data.meetings.map(m=><MeetingView key={m.id} meeting={m}/>)}</ul>:<p>No meeting view captured for this period.</p>}</details>
  </>:null}
  <button className={CONTROL} disabled={!!pending} onClick={()=>{setData(null);setError("");setAttempt(n=>n+1);}}>Reload corporate coverage</button>
 </div></details>;
}
function CoverageEditor({currentFacilityId,coverage,availableSites,busy,submit,start,end}:{currentFacilityId:string;coverage:NonNullable<CorporateDeliverablesReply["coverage"]>;availableSites:CorporateDeliverablesReply["available_sites"];busy:boolean;submit:(action:string,payload:Record<string,unknown>)=>void;start:string;end:string}){
 const [sites,setSites]=useState([...coverage.facility_ids]),[source,setSource]=useState(coverage.provenance);
 const sameSites=[...sites].sort().join(',')===[...coverage.facility_ids].sort().join(','),changed=!sameSites||source.trim()!==coverage.provenance;
 return <details><summary>Edit expected site set</summary><form className="space-y-2" onSubmit={event=>{event.preventDefault();submit("register",{period_start:start,period_end:end,period_provenance:source,expected_facility_ids:sites});}}><p>The current task site remains selected. Any revised set needs an attributable revised source.</p>{availableSites.map(site=><label className="block" key={site.id}><input type="checkbox" checked={sites.includes(site.id)} disabled={site.id===currentFacilityId} onChange={event=>setSites(current=>event.target.checked?[...current,site.id]:current.filter(id=>id!==site.id))}/> {site.label}</label>)}<label className="block">Revised coverage source<input className={CONTROL} value={source} onChange={event=>setSource(event.target.value)}/></label><button className={CONTROL} disabled={busy||!changed||!source.trim()||(!sameSites&&source.trim()===coverage.provenance)}>Save new coverage version</button></form></details>;
}
function MeetingView({meeting}:{meeting:CorporateDeliverablesReply["meetings"][number]}){
 const rawSites=Array.isArray(meeting.snapshot.sites)?meeting.snapshot.sites:[];
 return <li><details><summary>Captured {meeting.captured_at} · Presented: {meeting.presented_at??meeting.presented_on??"Unknown; no meeting occurrence inferred"}</summary>{meeting.presentation_provenance?<p>Presentation source: {meeting.presentation_provenance}</p>:null}<ul>{rawSites.map((raw,index)=>{const site=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const expectation=site.expectation&&typeof site.expectation==='object'&&!Array.isArray(site.expectation)?site.expectation as Record<string,unknown>:null;const currentVersion=expectation?.current_version;return <li key={`${String(site.facility_id)}:${index}`}><p>{String(site.facility_label??"Site label withheld")}: {String(site.status??"unavailable")}{expectation?` · captured state ${String(expectation.current_state??"unknown")}`:""}</p>{currentVersion&&typeof currentVersion==='object'?<details><summary>Captured packet version</summary><pre className="overflow-x-auto whitespace-pre-wrap">{JSON.stringify(currentVersion,null,2)}</pre></details>:null}</li>;})}</ul></details></li>;
}
function ExpectationActions({taskId,expectation,issueCandidates,busy,submit}:{taskId:string;expectation:NonNullable<CorporateDeliverablesReply["sites"][number]["expectation"]>;issueCandidates:CorporateDeliverablesReply["issue_candidates"];busy:boolean;submit:(action:string,payload:Record<string,unknown>)=>void}){
 const [recipient,setRecipient]=useState(expectation.recipient_label??""),[backup,setBackup]=useState(expectation.backup_label??""),[due,setDue]=useState(expectation.due_on??""),[provenance,setProvenance]=useState(""),[week,setWeek]=useState(""),[source,setSource]=useState<"census"|"stand_up">("census"),[action,setAction]=useState<"sent"|"received"|"accepted">("sent"),[version,setVersion]=useState(expectation.current_version_id??""),[evidence,setEvidence]=useState(""),[party,setParty]=useState(""),[date,setDate]=useState(""),[issueId,setIssueId]=useState(""),[problem,setProblem]=useState<"missing"|"late"|"rejected">("missing"),[reason,setReason]=useState("");
 const [historyCursor,setHistoryCursor]=useState(expectation.history_cursor),[olderVersions,setOlderVersions]=useState<CorporateDeliverableHistory["versions"]>([]),[olderEvents,setOlderEvents]=useState<CorporateDeliverableHistory["events"]>([]),[historyBusy,setHistoryBusy]=useState(false),[historyError,setHistoryError]=useState("");
 const trustSource=expectation.component_key==='hfo-al-m09-03'||expectation.component_key==='hfo-al-q01-01';
 const allVersions=[...expectation.versions,...olderVersions],allEvents=[...expectation.events,...olderEvents],selectedEvents=allEvents.filter(event=>event.version_id===version),terminal=selectedEvents.some(event=>event.kind==='accepted'||event.kind==='rejected'),received=selectedEvents.some(event=>event.kind==='received'),sent=selectedEvents.some(event=>event.kind==='sent'),eventHistoryExhausted=!historyCursor||historyCursor.before_sequence===0;
 const allowedActions={sent:eventHistoryExhausted&&!sent&&!received&&!terminal,received:eventHistoryExhausted&&!received&&!terminal,accepted:eventHistoryExhausted&&received&&!terminal};
 async function loadHistory(){if(!historyCursor||historyBusy)return;setHistoryBusy(true);setHistoryError("");try{const response=await fetch(`/api/admin/operations/corporate-deliverables/history?${new URLSearchParams({task_id:taskId,expectation_id:expectation.id,before_version:String(historyCursor.before_version),before_sequence:String(historyCursor.before_sequence)})}`,{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw Error();const page=corporateDeliverableHistorySchema.parse(await response.json());if(page.task_id!==taskId||page.expectation_id!==expectation.id)throw Error();setOlderVersions(current=>[...new Map([...current,...page.versions].map(item=>[item.id,item])).values()]);setOlderEvents(current=>[...new Map([...current,...page.events].map(item=>[item.id,item])).values()]);setHistoryCursor(page.complete?null:{before_version:page.next_before_version,before_sequence:page.next_before_sequence});}catch{setHistoryError("Older corporate history is unavailable under current authority.");}finally{setHistoryBusy(false);}}
 return <div className="space-y-3"><p>Current state: {expectation.current_state}. Recipient: {expectation.recipient_label??"Unknown"}. Backup: {expectation.backup_label??"Unknown"}. Due: {expectation.due_on??"Unknown; late is not inferred"}.</p>
  {expectation.follow_up?<section aria-label="Current packet follow-up"><p>Issue {expectation.follow_up.id} · {expectation.follow_up.status}</p><p>Owner: {expectation.follow_up.owner_user_id??expectation.follow_up.owner_role??"Unassigned"} · {expectation.follow_up.owner_current?"current":"not current"}</p><p>Backup: {expectation.follow_up.backup_user_id??expectation.follow_up.backup_role??"Unknown"} · {expectation.follow_up.backup_current?"current":"not current"}</p><p>Follow up at: {expectation.follow_up.follow_up_at??"Unknown"}</p><p>Next action: {expectation.follow_up.next_action}</p></section>:<p>Current follow-up ownership: Unknown or not linked.</p>}
  <details><summary>Record recipient, backup and due configuration</summary><form className="space-y-2" onSubmit={e=>{e.preventDefault();submit("configure",{expectation_id:expectation.id,expected_revision:expectation.revision,recipient_label:recipient||null,backup_label:backup||null,due_on:due||null,configuration_provenance:provenance,due_provenance:due?provenance:null});}}><label className="block">Confirmed recipient<input className={CONTROL} value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><label className="block">Confirmed backup<input className={CONTROL} value={backup} onChange={e=>setBackup(e.target.value)}/></label><label className="block">Approved due date<input className={CONTROL} type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label className="block">Configuration source<input className={CONTROL} value={provenance} onChange={e=>setProvenance(e.target.value)}/></label><button className={CONTROL} disabled={busy}>Save known or unknown configuration</button></form></details>
  {expectation.mapping_state==='unconfirmed'?<p>{expectation.component_key==='hfo-al-c08-01'?'Contract recipient and a canonical native contract-document classification remain unconfirmed. Preparation is unavailable; an arbitrary resident document is not accepted.':'FPC mapping and subject remain unconfirmed. Preparation is unavailable until the source meaning is approved.'}</p>:expectation.component_key==='hfo-al-m09-01'?<div className="space-y-2"><label>Preparation source<select className={CONTROL} value={source} onChange={e=>setSource(e.target.value as typeof source)}><option value="census">Current census source</option><option value="stand_up">Exact Stand Up revision</option></select></label>{source==='stand_up'?<label>Stand Up Monday<input className={CONTROL} type="date" value={week} onChange={e=>setWeek(e.target.value)}/></label>:null}<button className={CONTROL} disabled={busy||source==='stand_up'&&!week} onClick={()=>submit("prepare",{expectation_id:expectation.id,expected_revision:expectation.revision,source_family:source,...(source==='stand_up'?{stand_up_week_start:week}:{})})}>Prepare from current {source==='stand_up'?'Stand Up':'census'} source</button></div>:trustSource?<button className={CONTROL} disabled={busy} onClick={()=>submit("prepare",{expectation_id:expectation.id,expected_revision:expectation.revision,source_family:"trust"})}>Prepare from current trust source</button>:null}
  {expectation.current_version_id?<details><summary>Record a distinct sent, received or accepted fact</summary><form className="space-y-2" onSubmit={e=>{e.preventDefault();const dateField=`${action}_on`;submit(action,{expectation_id:expectation.id,expected_revision:expectation.revision,version_id:version,...(action==='accepted'?{approver_label:party}:{channel:party}),source_evidence:evidence,[dateField]:date});}}><p>Each immutable version has its own non-regressing lifecycle. Load older event history before changing an older version.</p><label>Packet version<select className={CONTROL} value={version} onChange={e=>setVersion(e.target.value)}>{allVersions.map(v=><option key={v.id} value={v.id}>Version {v.version} · {v.source_family}</option>)}</select></label><label>State<select className={CONTROL} value={action} onChange={e=>setAction(e.target.value as typeof action)}><option value="sent" disabled={!allowedActions.sent}>Sent</option><option value="received" disabled={!allowedActions.received}>Received</option><option value="accepted" disabled={!allowedActions.accepted}>Accepted</option></select></label><label>{action==='accepted'?"Actual approver":"Actual channel"}<input className={CONTROL} value={party} onChange={e=>setParty(e.target.value)}/></label><label>Source evidence<input className={CONTROL} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><label>Actual date<input className={CONTROL} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className={CONTROL} disabled={busy||!allowedActions[action]}>Record operator evidence</button></form></details>:null}
  <details><summary>Packet version and event history</summary><p>{expectation.history_complete&&!historyCursor?'Complete bounded history.':'More history is available through bounded pages.'}</p>{[...expectation.versions,...olderVersions].map((item,index)=><pre key={`version-${index}`} className="overflow-x-auto whitespace-pre-wrap">{JSON.stringify(item,null,2)}</pre>)}{[...expectation.events,...olderEvents].map((item,index)=><pre key={`event-${index}`} className="overflow-x-auto whitespace-pre-wrap">{JSON.stringify(item,null,2)}</pre>)}{historyCursor?<button className={CONTROL} disabled={historyBusy} onClick={()=>void loadHistory()}>Load older packet history</button>:null}{historyError?<p role="alert">{historyError}</p>:null}</details>
  <details><summary>Link existing issue ownership and next action</summary>{issueCandidates.length?<form className="space-y-2" onSubmit={event=>{event.preventDefault();submit("link_follow_up",{expectation_id:expectation.id,expected_revision:expectation.revision,problem_state:problem,issue_id:issueId});}}><label>Problem state<select className={CONTROL} value={problem} onChange={event=>setProblem(event.target.value as typeof problem)}><option value="missing">Missing</option><option value="late">Late under documented due rule</option><option value="rejected">Rejected</option></select></label><label>Existing issue<select className={CONTROL} value={issueId} onChange={event=>setIssueId(event.target.value)}><option value="">Select a current-owned issue</option>{issueCandidates.filter(issue=>issue.owner_current).map(issue=><option key={issue.id} value={issue.id}>{issue.label} · {issue.status} · {issue.owner_label??"Unassigned"}</option>)}</select></label><button className={CONTROL} disabled={busy||!issueId}>Link existing issue</button></form>:<p>Use the existing Report an issue action first; no second issue engine is created here.</p>}</details>
  {expectation.current_version_id&&issueCandidates.some(issue=>issue.owner_current)?<details><summary>Record rejected packet</summary><form className="space-y-2" onSubmit={event=>{event.preventDefault();submit("rejected",{expectation_id:expectation.id,expected_revision:expectation.revision,version_id:version,reason,issue_id:issueId,channel:party,source_evidence:evidence,rejected_on:date});}}><p>Rejection requires prior receipt of this exact selected version; preparation alone is insufficient.</p><label>Rejection reason<input className={CONTROL} value={reason} onChange={event=>setReason(event.target.value)}/></label><label>Actual rejection channel<input className={CONTROL} value={party} onChange={event=>setParty(event.target.value)}/></label><label>Rejection source evidence<input className={CONTROL} value={evidence} onChange={event=>setEvidence(event.target.value)}/></label><label>Actual rejection date<input className={CONTROL} type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>Owned next-action issue<select className={CONTROL} value={issueId} onChange={event=>setIssueId(event.target.value)}><option value="">Select</option>{issueCandidates.filter(issue=>issue.owner_current).map(issue=><option key={issue.id} value={issue.id}>{issue.label} · {issue.owner_label}</option>)}</select></label><button className={CONTROL} disabled={busy||!issueId||!reason||!party||!evidence||!date||!received||terminal||!eventHistoryExhausted}>Record rejected version</button></form></details>:null}
 </div>;
}
