import { render, screen, cleanup, fireEvent, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import axe from "axe-core";
import { FinanceSourcePanel } from "./finance-source-panel";
import { financeSourceMap } from "@/lib/operations/finance-source-map";
const id="00000000-0000-0000-0000-000000000001",other="00000000-0000-0000-0000-000000000002";
const props={taskId:id,activityKey:"hfo-al-m09-01",facilityId:id,actorId:id,subjectId:null};
const row={id,version:"a".repeat(64),native_version:"1",economic_date:"2026-08-15",service_period_start:"2026-07-01",service_period_end:"2026-07-31",recorded_at:"2026-09-13T12:00:00Z",state:"recorded",amount_cents:"12345",metrics:{}};
const reply=(extra={})=>({task_id:id,activity_key:props.activityKey,subject_kind:"facility",resident_id:null,facility_id:id,start_date:"2026-08-01",end_date:"2026-08-31",timezone:"America/New_York",source_version:"b".repeat(64),complete:true,families:["census","payments","trust","finance_handoff"].map(family=>({family,availability:"available",reason:"Native context only",records:family==="payments"?[row]:family==="trust"?[{...row,metrics:{canonical_balance_cents:"100",legacy_balance_cents:"200",legacy_review_required:true,external_reconciliation:"NOT_VERIFIED"}}]:[],missing_dates:family==="census"?["2026-08-03"]:[]})),history:[],history_complete:false,fields:financeSourceMap.map(m=>({source_id:m.sourceId,component_key:m.key,label:m.label,kind:m.kind,families:m.families,reason:m.gap,state:"unknown"})),...extra});
const response=(body:unknown)=>({ok:true,status:200,json:async()=>body});const fetchMock=vi.fn();
beforeEach(()=>{fetchMock.mockReset();vi.stubGlobal("fetch",fetchMock);});afterEach(()=>{cleanup();vi.unstubAllGlobals();});
async function open(){await userEvent.click(screen.getByText("Finance and census source context"));fireEvent.change(screen.getByLabelText("Source period start"),{target:{value:"2026-08-01"}});fireEvent.change(screen.getByLabelText("Source period end"),{target:{value:"2026-08-31"}});}
it("maps22items27components and does not equate nativecontext with finality",()=>{expect(financeSourceMap).toHaveLength(27);expect(new Set(financeSourceMap.map(row=>row.sourceId)).size).toBe(22);expect(financeSourceMap.find(row=>row.key==="hfo-al-m09-02")?.families).toEqual([]);expect(financeSourceMap.every(row=>Boolean(row.gap))).toBe(true);});
it("keeps latepayment economic/service/recording dates distinct with truthful coverage",async()=>{fetchMock.mockResolvedValue(response(reply()));const {container}=render(<FinanceSourcePanel {...props}/>);await open();await screen.findByText("Recorded payment context");await userEvent.click(screen.getByText("Recorded payment context"));expect(within(screen.getByText("Recorded payment context").closest("details")!).getByText("Economic / source date: 2026-08-15")).toBeVisible();expect(within(screen.getByText("Recorded payment context").closest("details")!).getByText("Service period: 2026-07-01 to 2026-07-31")).toBeVisible();expect(within(screen.getByText("Recorded payment context").closest("details")!).getByText("Recorded at: 2026-09-13T12:00:00Z")).toBeVisible();await userEvent.click(screen.getByText("Daily census snapshots"));expect(screen.getByText(/Missing source dates: 2026-08-03/)).toBeVisible();await userEvent.click(screen.getByText("Finance source change history"));expect(screen.getByText(/Latest 100 source changes only/)).toBeVisible();expect((await axe.run(container,{rules:{"color-contrast":{enabled:false}}})).violations).toEqual([]);});
it("keeps canonical and legacy trust balances separate",async()=>{fetchMock.mockResolvedValue(response(reply()));render(<FinanceSourcePanel {...props}/>);await open();await userEvent.click(await screen.findByText("Trust source context"));expect(screen.getByText("Canonical balance: $1.00")).toBeVisible();expect(screen.getByText("Legacy balance (separate, not added): $2.00")).toBeVisible();expect(screen.queryByText(/300/)).toBeNull();});
it("retries an uncertain refresh bytewise and locks its period without financial commands",async()=>{fetchMock.mockResolvedValueOnce(response(reply())).mockRejectedValueOnce(new Error("lost")).mockResolvedValueOnce(response(reply()));render(<FinanceSourcePanel {...props}/>);await open();await userEvent.click(await screen.findByRole("button",{name:"Refresh and record finance source changes"}));await screen.findByText(/Refresh result unknown/);expect(screen.getByLabelText("Source period end")).toBeDisabled();await userEvent.click(screen.getByRole("button",{name:"Retry same finance source refresh"}));await screen.findByText("Daily census snapshots");expect(fetchMock.mock.calls[1][1].body).toBe(fetchMock.mock.calls[2][1].body);expect(Object.keys(JSON.parse(fetchMock.mock.calls[1][1].body)).sort()).toEqual(["end_date","request_key","start_date","task_id"]);});
it("clears records when period changes and aborts actor-scope requests",async()=>{fetchMock.mockResolvedValueOnce(response(reply())).mockImplementation(()=>new Promise(()=>{}));const {rerender}=render(<FinanceSourcePanel {...props}/>);await open();await screen.findByText("Recorded payment context");fireEvent.change(screen.getByLabelText("Source period end"),{target:{value:"2026-08-30"}});expect(screen.queryByText("Recorded payment context")).toBeNull();await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(2));const signal=fetchMock.mock.calls[1][1].signal;rerender(<FinanceSourcePanel {...props} actorId={other}/>);expect(signal.aborted).toBe(true);});
it("failsclosed for wrongperiod and incomplete source replies",async()=>{fetchMock.mockResolvedValue(response(reply({end_date:"2026-09-13",complete:false})));render(<FinanceSourcePanel {...props}/>);await open();await screen.findByText(/Current finance sources unavailable/);expect(screen.queryByText("Recorded payment context")).toBeNull();});

it("formats dollar amounts exactly beyond Number precision",async()=>{
 const value=reply();value.families.find(f=>f.family==="payments")!.records=[{...row,amount_cents:"9007199254740993",metrics:{allocated_cents:"9007199254740992",unapplied_cents:"1"}}];
 fetchMock.mockResolvedValue(response(value));render(<FinanceSourcePanel {...props}/>);await open();await userEvent.click(await screen.findByText("Recorded payment context"));
 expect(screen.getByText("Native amount: $90071992547409.93")).toBeVisible();expect(screen.getByText("Allocated amount: $90071992547409.92")).toBeVisible();expect(screen.getByText("Unapplied amount: $0.01")).toBeVisible();
});
