"use client";
import { useEffect,useRef,useState } from 'react';
import { providerContactCreateSchema,providerContactReplySchema } from '@/lib/operations/provider-reports';
import { CONTROL } from './work-inputs';
export function ProviderContactIntake({taskId,residentId,disabled,onLock,onSaved}:{taskId:string;residentId:string;disabled:boolean;onLock:(value:boolean)=>void;onSaved:()=>void}){
 const [name,setName]=useState(''),[type,setType]=useState(''),[pending,setPending]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const active=useRef(true),sending=useRef(false),abort=useRef<AbortController|null>(null);
 useEffect(()=>{active.current=true;return()=>{active.current=false;abort.current?.abort();onLock(false);};},[onLock]);
 async function send(body:string){if(sending.current||disabled)return;sending.current=true;setPending(body);setBusy(true);setMessage('');onLock(true);abort.current=new AbortController();try{const response=await fetch('/api/admin/operations/provider-reports/contacts',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body,signal:abort.current.signal});if(!active.current)return;if(!response.ok){if(response.status<500&&![408,429].includes(response.status)){setPending(null);onLock(false);setMessage('Contact creation rejected. Check current native write access and fields.');return;}throw Error('Unknown');}const reply=providerContactReplySchema.parse(await response.json());if(reply.task_id!==taskId||reply.resident_id!==residentId)throw Error('Wrong contact scope');if(!active.current)return;setPending(null);onLock(false);setName('');setType('');setMessage('Native contact created. Select it when recording a service attestation; contact existence does not confirm service.');onSaved();}catch{if(active.current)setMessage('Contact result unknown. Retry the same request; names are not merged automatically.');}finally{sending.current=false;if(active.current)setBusy(false);}}
 function submit(){if(pending||disabled)return;try{void send(JSON.stringify(providerContactCreateSchema.parse({task_id:taskId,request_key:crypto.randomUUID(),name,contact_type:type})));}catch{setMessage('Enter a contact name and type.');}}
 return <details><summary className={`${CONTROL} cursor-pointer`}>Add native resident contact</summary><p>Select an existing contact when appropriate. Creating a new contact does not establish provider identity, service or report finality.</p>{message?<p role="status">{message}</p>:null}{pending?<button type="button" className={CONTROL} disabled={busy||disabled} onClick={()=>void send(pending)}>Retry same contact request</button>:null}<form onSubmit={e=>{e.preventDefault();submit();}}><fieldset className="space-y-3" disabled={busy||disabled||pending!==null}><legend>New native contact</legend><label className="block">Contact name<input className={CONTROL} value={name} onChange={e=>setName(e.target.value)}/></label><label className="block">Contact type<input className={CONTROL} value={type} onChange={e=>setType(e.target.value)}/></label><button className={CONTROL}>Create native contact</button></fieldset></form></details>;
}
