"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { providerReportsReplySchema, providerReportCommandSchema, type ProviderReportsReply } from "@/lib/operations/provider-reports";
import { CONTROL, DateTimeInput, typedValues } from "./work-inputs";
import { ProviderContactIntake } from "./provider-contact-intake";
import { ProviderDocumentIntake } from "./provider-document-intake";
import { enumLabel } from "@/lib/display/enum-label";
type Props={taskId:string;activityKey:string|null|undefined;facilityId:string;actorId:string;subjectId:string|null;timezone:string};
export function ProviderReportPanel(props:Props){if(props.activityKey!=='hfo-al-h01-01')return null;return <Panel key={`${props.taskId}:${props.facilityId}:${props.actorId}:${props.subjectId}`} {...props}/>;}
const eventFields=['signed_on','signed_at','signer_role','signer_label','page','page_verification','source_provenance','corrects_event_id','version_id','result','findings','receipt_provenance','received_at','approval_reference','approver_label','approved_at','effective_date','due_at','due_on','received_on','approved_on'];
function Panel({taskId,facilityId,timezone}:Props){
 const [opened,setOpened]=useState(false),[data,setData]=useState<ProviderReportsReply|null>(null),[error,setError]=useState(''),[pending,setPending]=useState<string|null>(null),[busy,setBusy]=useState(false),[uploadLocked,setUploadLocked]=useState(false),[contactLocked,setContactLocked]=useState(false),[attempt,setAttempt]=useState(0);
 const active=useRef(true),sending=useRef(false),generation=useRef(0),read=useRef<AbortController|null>(null),command=useRef<AbortController|null>(null),downloadRequest=useRef<AbortController|null>(null);
 useEffect(()=>{active.current=true;return()=>{active.current=false;read.current?.abort();command.current?.abort();downloadRequest.current?.abort();};},[]);
 const validate=useCallback((raw:unknown)=>{const reply=providerReportsReplySchema.parse(raw);if(reply.task_id!==taskId||!reply.complete||reply.versions.some(v=>(v.state==='prepared'&&v.task_id!==taskId)||v.facility_id!==facilityId||v.resident_id!==reply.resident_id))throw Error('Incomplete/wrong report scope');return reply;},[taskId,facilityId]);
 useEffect(()=>{if(!opened)return;const abort=new AbortController();read.current=abort;const version=++generation.current;void fetch(`/api/admin/operations/provider-reports?task_id=${taskId}`,{credentials:'same-origin',cache:'no-store',signal:abort.signal}).then(async response=>{if(!response.ok)throw Error('Unavailable');const reply=validate(await response.json());if(active.current&&!abort.signal.aborted&&version===generation.current)setData(reply);}).catch(()=>{if(active.current&&!abort.signal.aborted&&version===generation.current){setData(null);setError('Provider report details unavailable under current access. Earlier values are not current proof.');}});return()=>abort.abort();},[opened,attempt,taskId,validate]);
 async function send(body:string){if(sending.current||uploadLocked||contactLocked)return;sending.current=true;read.current?.abort();generation.current++;setPending(body);setBusy(true);setError('');command.current=new AbortController();try{const response=await fetch('/api/admin/operations/provider-reports',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body,signal:command.current.signal});if(!active.current)return;if(!response.ok){if(response.status<500&&![408,429].includes(response.status)){setPending(null);setData(null);setError('Report change rejected. Reload current details before another change.');return;}throw Error('Unknown');}const reply=validate(await response.json());if(!active.current)return;setPending(null);setData(reply);}catch{if(active.current){setData(null);setError('Report save result unknown. Retry the same change before another action.');}}finally{sending.current=false;if(active.current)setBusy(false);}}
 function submit(payload:Record<string,unknown>){if(busy||pending||uploadLocked||contactLocked)return;try{void send(JSON.stringify(providerReportCommandSchema.parse({...payload,task_id:taskId,request_key:crypto.randomUUID()})));}catch{setError('Complete the required factual fields. Version, dates and provenance must match the selected action.');}}
 function reload(){if(pending||uploadLocked||contactLocked)return;setData(null);setError('');setAttempt(n=>n+1);}
 async function download(versionId:string){setError('');downloadRequest.current?.abort();const controller=new AbortController();downloadRequest.current=controller;try{const response=await fetch(`/api/admin/operations/provider-reports/documents/${versionId}/download?task_id=${taskId}`,{credentials:'same-origin',cache:'no-store',signal:controller.signal});if(!response.ok)throw Error('Denied');const blob=await response.blob();if(!active.current||controller.signal.aborted)return;const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='resident-report';link.click();URL.revokeObjectURL(url);}catch{if(active.current&&!controller.signal.aborted){setData(null);setError('Document download unavailable. Current native and operations access are both required.');}}}
 const locked=busy||pending!==null||uploadLocked||contactLocked;
 return <details onToggle={e=>{if(e.currentTarget.open)setOpened(true);}}><summary className={`${CONTROL} cursor-pointer`}>Provider reports and support plans</summary>{opened?<div role="group" aria-label="Provider reports and support plans" className="min-w-0 space-y-4 pt-3 [overflow-wrap:anywhere]">
 <p>AL-H01 Community Support Plan. Applicability, Plantation/Hope identity, monthly review and six-month renewal rules remain unconfirmed. No automatic deadline or required signer set is activated.</p>
 {error?<p role="alert">{error}</p>:null}{pending?<button type="button" className={CONTROL} disabled={busy||uploadLocked} onClick={()=>void send(pending)}>Retry same report change</button>:<button type="button" className={CONTROL} disabled={uploadLocked||contactLocked} onClick={reload}>Reload provider reports</button>}
 {data?.availability==='available'&&data.eligible?<>
 <p>{data.reason}</p>
 {data.can_manage?<ReportForm prefix={taskId} key={`create:${attempt}`} timezone={timezone} contacts={data.contacts} chaseCandidates={data.chase_candidates} versions={data.versions} disabled={locked} onSubmit={submit}/>:<p>Report management unavailable under current authority.</p>}
 {data.can_intake&&data.resident_id?<ProviderContactIntake taskId={taskId} residentId={data.resident_id} disabled={busy||pending!==null||uploadLocked} onLock={setContactLocked} onSaved={()=>setAttempt(n=>n+1)}/>:null}
 {data.can_intake&&data.resident_id?<ProviderDocumentIntake taskId={taskId} facilityId={facilityId} residentId={data.resident_id} versions={data.versions} disabled={busy||pending!==null||contactLocked} onLock={setUploadLocked} onSaved={()=>{setAttempt(n=>n+1);}}/>:<p>Native document upload requires current clinical write permission.</p>}
 <details><summary className={`${CONTROL} cursor-pointer`}>Native document versions</summary><ul>{data.versions.map(v=><li key={v.id}>{v.title} · {enumLabel(v.document_type, { case: "lower" })} · {v.state} · {v.native_current?'Current native binding':'Historical or unverified native binding'} · Origin task {v.task_id} · Version {v.id}<p>{v.supersedes_version_id?`Supersedes version ${v.supersedes_version_id}`:'Original native version'} · {v.page_count===null?'PDF page count unverified; reported page numbers are operator observations.':`Technical page count: ${v.page_count}`}</p>{v.state==='finalized'&&v.native_current?<button type="button" className={CONTROL} disabled={locked} onClick={()=>void download(v.id)}>Download native version {v.title}</button>:null}</li>)}</ul></details>
 {data.expectations.map(e=><div key={e.id} className="space-y-2 border-l border-border pl-3"><p className="font-medium">Expected {enumLabel(e.document_type, { case: "lower" })} · {e.expected_version}</p><p>Service: operator-attested · {e.service_at??`${e.service_on??'Unknown date'} (time unknown)`} · {e.service_provenance}</p>
 <p>Service contact: {e.contact_label} · {e.contact_current?'Current contact metadata':'Contact metadata changed since attestation'}</p><p>Report: {e.current_version_id?'Received':'Outstanding — not received'}{e.received_at||e.received_on?` · ${e.received_at??`${e.received_on} (time unknown)`}`:''}</p><p>Due rule: {e.due_state==='unknown'?'Unknown; overdue is not inferred':e.due_state==='documented_approval_pending_effective'?'Documented approval pending effective date; not overdue':`${e.due_at??`${e.due_on} (date only)`} · ${e.overdue?'Overdue under documented approval':'Documented approval'}`}</p><p>Current task review: {enumLabel(e.review_state, { case: "lower" })}. Renewal: separate; no renewal rule confirmed.</p>{e.last_review?<p>Last recorded review (historical): {enumLabel(e.last_review.result, { case: "lower" })} · {e.last_review.recorded_at} · {e.last_review.task_id===taskId?'This task':'Earlier task'}</p>:null}<p>Required signers: unknown. Individual observations do not establish signature completeness.</p><p>Owner: {e.owner_label??e.owner_role??(e.owner_user_id?'Assigned person name unavailable':'Unassigned')} · Chase commitment: {e.follow_up_at??'None recorded'} (not an approved report deadline)</p><p>Current received native version: {e.current_version_id??'None'}</p>
 {data.can_manage?<ReportForm prefix={taskId} key={`${e.id}:${e.revision}`} expectation={e} timezone={timezone} contacts={data.contacts} chaseCandidates={data.chase_candidates} versions={data.versions} disabled={locked} onSubmit={submit}/>:null}
 <details><summary className={`${CONTROL} cursor-pointer`}>Report provenance history</summary><p>{e.events_complete?'Complete available event history.':'Latest events only; older history is not included.'}</p><ul>{e.events.map(event=><li key={event.id}><p>{enumLabel(event.kind, { case: "lower" })} · {event.recorded_at} · Recorded by {event.actor_id}</p>{event.kind==='signature_observation'?<><p>Operator-observed documentary signature evidence; not cryptographic or provider-verified signing.</p><p>Signed date: {String(event.details.signed_on??event.details.signed_at??'Unknown')}</p></>:null}{Object.entries(event.details).filter(([key,value])=>eventFields.includes(key)&&['string','number'].includes(typeof value)).map(([key,value])=><p key={key}>{enumLabel(key, { case: "lower" })}: {String(value)}</p>)}</li>)}</ul></details>
 </div>)}
 </>:data?<p>Provider details unavailable. No empty-report or completion conclusion can be drawn.</p>:null}
 </div>:null}</details>;
}
function ReportForm({prefix,expectation,contacts,chaseCandidates,versions,timezone,disabled,onSubmit}:{prefix:string;expectation?:ProviderReportsReply['expectations'][number];contacts:ProviderReportsReply['contacts'];chaseCandidates:ProviderReportsReply['chase_candidates'];versions:ProviderReportsReply['versions'];timezone:string;disabled:boolean;onSubmit:(payload:Record<string,unknown>)=>void}){
 const [action,setAction]=useState(expectation?'attach_receipt':'create'),[values,setValues]=useState<Record<string,string>>({}),[formError,setFormError]=useState(''),[exactTimes,setExactTimes]=useState<Record<string,boolean>>({});
 const set=(key:string,value:string)=>setValues(v=>{const next={...v,[key]:value};if(key==='version_id')delete next.corrects_event_id;return next;});
 const text=(key:string,label:string)=><label className="block" key={key}>{label}<input className={CONTROL} value={values[key]??''} onChange={e=>set(key,e.target.value)}/></label>;
 const time=(key:string,label:string)=>{const dateKey=key.replace(/_at$/,'_on');return <div key={key}><label className="block"><input type="checkbox" checked={!!exactTimes[key]} onChange={e=>{setExactTimes(t=>({...t,[key]:e.target.checked}));setValues(v=>{const next={...v};delete next[key];delete next[dateKey];return next;});}}/> Exact clock time is evidenced for {label.toLowerCase()}</label>{exactTimes[key]?<DateTimeInput id={`provider-${prefix}-${expectation?.id??'new'}-${key}`} timezone={timezone} label={label} value={values[key]??''} onChange={value=>set(key,value)}/>:<label className="block">{label}<input type="date" className={CONTROL} value={values[dateKey]??''} onChange={e=>set(dateKey,e.target.value)}/></label>}<p>{exactTimes[key]?'Use the actual evidenced time.':'Date only; no clock time is inferred.'}</p></div>;};
 const select=(key:string,label:string,options:{value:string;label:string}[])=><label className="block">{label}<select className={CONTROL} value={values[key]??''} onChange={e=>set(key,e.target.value)}><option value="">Select</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
 function submit(){setFormError('');const payload:Record<string,unknown>={action,...values,...(expectation?{expectation_id:expectation.id,expected_revision:expectation.revision}:{})};for(const key of ['service_at','received_at','due_at','approved_at','signed_at'])if(values[key]){try{payload[key]=typedValues([{key,label:key,type:'datetime',required:true}],{[key]:values[key]},timezone)[key];}catch{setFormError('Enter a valid facility date and time for '+enumLabel(key, { case: "lower" }));return;}}if(action==='signature_observation')payload.page=Number(values.page);if(!values.corrects_event_id)delete payload.corrects_event_id;if(!values.signed_at)delete payload.signed_at;if(!values.signed_on)delete payload.signed_on;onSubmit(payload);}
 return <details><summary className={`${CONTROL} cursor-pointer`}>{expectation?'Record a distinct report event':'Record an expected report after service'}</summary><form onSubmit={e=>{e.preventDefault();submit();}}><fieldset disabled={disabled} className="space-y-3"><legend>{expectation?'One factual event':'Operator-attested service; report remains outstanding'}</legend>{formError?<p role="alert">{formError}</p>:null}
 {expectation?<label className="block">Report event<select className={CONTROL} value={action} onChange={e=>{setAction(e.target.value);setValues({});setExactTimes({});}}>{['attach_receipt','review','signature_observation','set_due','link_chase','create_chase'].map(value=><option key={value} value={value}>{enumLabel(value)}</option>)}</select></label>:<>{select('contact_id','Service contact',contacts.map(c=>({value:c.id,label:c.label})))}{select('document_type','Expected document type',['form_1823','hospice_plan','community_support_plan','support_plan','provider_report','other'].map(value=>({value,label:enumLabel(value)})))}{text('expected_version','Expected version description')}{time('service_at','Actual service date')}{text('service_provenance','Operator service confirmation source')}</>}
 {['attach_receipt','review','signature_observation'].includes(action)?select('version_id','Exact native document version',versions.filter(v=>v.state==='finalized'&&v.native_current).map(v=>({value:v.id,label:`${v.title} · ${v.id}`}))):null}
 {action==='attach_receipt'?<>{time('received_at','Actual report receipt date')}{text('receipt_provenance','Receipt source / channel')}</>:null}
 {action==='review'?<>{select('result','Review result',[{value:'reviewed',label:'Reviewed'},{value:'follow_up_needed',label:'Follow-up needed'}])}{text('findings','Review findings')}<p>Review does not renew, approve clinical content or sign for another person.</p></>:null}
 {action==='signature_observation'?<>{select('signer_role','Observed signer role',['caseworker','resident','administrator','other'].map(value=>({value,label:value})))}{text('signer_label','Name shown on document')}{text('page','Observed page number')}{time('signed_at','Signature date evidenced on document (optional)')}{text('source_provenance','Observed signature evidence source')}{select('corrects_event_id','Earlier signature observation to correct (optional)',(expectation?.events??[]).filter(event=>event.kind==='signature_observation'&&event.details.version_id===values.version_id).map(event=>({value:event.id,label:`${event.details.signer_role??'Unknown role'} · ${event.details.signer_label??'Name unknown'} · ${event.details.signed_on??event.details.signed_at??'Signed date unknown'} · ${event.recorded_at}`})))}<p>Paper-signature observation only. PDF page count is unverified; do not infer a validated electronic signature or required signer set.</p></>:null}
 {action==='set_due'?<>{time('due_at','Approved report due date')}{select('source_version_id','Native version containing due approval',versions.filter(v=>v.state==='finalized'&&v.native_current).map(v=>({value:v.id,label:v.title})))}{text('approval_reference','Approval source / page reference')}{text('approver_label','Attributable approver')}{time('approved_at','Actual approval date')}<label className="block">Approval effective date<input type="date" className={CONTROL} value={values.effective_date??''} onChange={e=>set('effective_date',e.target.value)}/></label><p>Use attributable documented approval, not a chase commitment or assumed cadence.</p></>:null}
 {action==='link_chase'?<>{select('issue_id','Existing follow-up issue',chaseCandidates.map(issue=>({value:issue.id,label:`${issue.label} · ${issue.status} · ${issue.owner_label??'Unassigned'}`})))}{chaseCandidates.length===0?<p>No eligible follow-up issue exists. Use the existing Report an issue action, or choose create chase for a generic follow-up.</p>:null}<p>Use a generic follow-up issue without provider, report type, signature or document details. Sensitive linkage stays in this report history.</p></>:null}
 {action==='create_chase'?<p>Create a generic follow-up through the existing issue workflow. No provider or document details are copied into that issue.</p>:null}
 <button className={CONTROL}>Save factual report event</button>
 </fieldset></form></details>;
}
