import { render,screen,cleanup,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach,afterEach,it,expect,vi } from 'vitest';
import { ProviderDocumentIntake } from './provider-document-intake';
const upload=vi.hoisted(()=>vi.fn());vi.mock('@/lib/supabase/client',()=>({createClient:()=>({storage:{from:()=>({upload})}})}));
const id='00000000-0000-0000-0000-000000000001',versionId='00000000-0000-0000-0000-000000000002';
const hash='ab'.repeat(32);const version={id:versionId,document_id:versionId,native_document_id:null,task_id:id,resident_id:id,facility_id:id,document_type:'community_support_plan',title:'Synthetic',state:'prepared',revision:id,declared_mime:'application/pdf',declared_size_bytes:5,declared_sha256:hash,bucket:'resident-documents',object_path:`${id}/${versionId}/${versionId}/source`,supersedes_version_id:null,prepared_at:'2026-09-13T12:00:00Z',finalized_at:null,checksum_verified:false,page_count:null};
const props=()=>({taskId:id,facilityId:id,residentId:id,versions:[],disabled:false,onLock:vi.fn(),onSaved:vi.fn()});const response=(v=version)=>({ok:true,status:200,json:async()=>({version:v})});const fetchMock=vi.fn();
beforeEach(()=>{upload.mockReset();fetchMock.mockReset();vi.stubGlobal('fetch',fetchMock);vi.spyOn(crypto.subtle,'digest').mockResolvedValue(new Uint8Array(32).fill(171).buffer);});afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function fill(){await userEvent.click(screen.getByText('Native report document intake'));await userEvent.type(screen.getByLabelText('Document title'),'Synthetic');const file=new File(['%PDF-'],'report.pdf',{type:'application/pdf'});Object.defineProperty(file,'arrayBuffer',{value:async()=>new TextEncoder().encode('%PDF-').buffer});await userEvent.upload(screen.getByLabelText('Native report file'),file);await userEvent.click(screen.getByRole('button',{name:'Upload and finalize native version'}));}
it.each([{label:'oversized',size:20971521,mime:'application/pdf'},{label:'unsupported',size:5,mime:'application/octet-stream'}])('rejects $label files before reading bytes or making requests',async({size,mime})=>{
 const user=userEvent.setup({applyAccept:false});render(<ProviderDocumentIntake {...props()}/>);
 await user.click(screen.getByText('Native report document intake'));await user.type(screen.getByLabelText('Document title'),'Synthetic');
 const file=new File(['%PDF-'],'report.pdf',{type:mime});const readBytes=vi.fn();Object.defineProperty(file,'size',{value:size});Object.defineProperty(file,'arrayBuffer',{value:readBytes});
 await user.upload(screen.getByLabelText('Native report file'),file);await user.click(screen.getByRole('button',{name:'Upload and finalize native version'}));
 await screen.findByText('Choose a PDF, JPEG or PNG up to 20 MB and a document title.');expect(readBytes).not.toHaveBeenCalled();expect(crypto.subtle.digest).not.toHaveBeenCalled();expect(fetchMock).not.toHaveBeenCalled();expect(upload).not.toHaveBeenCalled();
});
it('uploads native bytes once and claims finalized transport only after server verification',async()=>{const p=props();fetchMock.mockResolvedValueOnce(response()).mockResolvedValueOnce(response({...version,state:'finalized',checksum_verified:true}));upload.mockResolvedValue({error:null});render(<ProviderDocumentIntake {...p}/>);await fill();await screen.findByText(/Native document version finalized/);expect(upload.mock.calls[0][0]).toBe(version.object_path);expect(upload.mock.calls[0][2]).toEqual({upsert:false,contentType:'application/pdf'});expect(p.onSaved).toHaveBeenCalledOnce();expect(JSON.parse(fetchMock.mock.calls[0][1].body)).toMatchObject({declared_sha256:hash,declared_size_bytes:5});});
it('rejects wrong native object scope before uploading',async()=>{fetchMock.mockResolvedValue(response({...version,object_path:'wrong/path'}));render(<ProviderDocumentIntake {...props()}/>);await fill();await screen.findByText(/Document intake is unfinished/);expect(upload).not.toHaveBeenCalled();});
it('retries lost finalize response without reuploading a now-forbidden finalized object',async()=>{fetchMock.mockResolvedValueOnce(response()).mockRejectedValueOnce(new Error('lost')).mockResolvedValueOnce(response({...version,state:'finalized',checksum_verified:true}));upload.mockResolvedValueOnce({error:null}).mockResolvedValueOnce({error:{statusCode:'403'}});render(<ProviderDocumentIntake {...props()}/>);await fill();await screen.findByText(/Document intake is unfinished/);await userEvent.click(screen.getByRole('button',{name:'Retry same document intake'}));await screen.findByText(/Native document version finalized/);expect(fetchMock.mock.calls[1][1].body).toBe(fetchMock.mock.calls[2][1].body);expect(fetchMock).toHaveBeenCalledTimes(3);expect(upload).toHaveBeenCalledOnce();});
it('does not finalize after component scope is removed during upload',async()=>{fetchMock.mockResolvedValue(response());let resolve!:(value:unknown)=>void;upload.mockImplementation(()=>new Promise(r=>{resolve=r;}));const p=props();const {unmount}=render(<ProviderDocumentIntake {...p}/>);await fill();await waitFor(()=>expect(upload).toHaveBeenCalledOnce());unmount();resolve({error:null});await Promise.resolve();expect(fetchMock).toHaveBeenCalledOnce();expect(p.onSaved).not.toHaveBeenCalled();});
it('does not claim completion for a server reply without verified checksum',async()=>{fetchMock.mockResolvedValueOnce(response()).mockResolvedValueOnce(response({...version,state:'finalized',checksum_verified:false}));upload.mockResolvedValue({error:null});const p=props();render(<ProviderDocumentIntake {...p}/>);await fill();await screen.findByText(/Document intake is unfinished/);expect(p.onSaved).not.toHaveBeenCalled();});
