import { render, screen, cleanup, waitFor, fireEvent } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach,afterEach,it,expect,vi } from "vitest";
import axe from "axe-core";
import { ProviderReportPanel } from "./provider-report-panel";
const id='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002';
const props={taskId:id,activityKey:'hfo-al-h01-01',facilityId:id,actorId:id,subjectId:id,timezone:'America/New_York'};
const expectation={id,revision:id,document_type:'community_support_plan',expected_version:'Synthetic plan',contact_id:id,contact_label:'Synthetic contact',contact_current:true,owner_label:null,service_at:'2026-09-13T12:00:00Z',service_provenance:'Operator reviewed service note',service_confirmation:'operator_attested',due_at:null,due_state:'unknown',due_provenance:null,overdue:true,current_version_id:null,received_at:null,receipt_provenance:null,review_state:'not_reviewed',required_signers:'unknown',chase_issue_id:null,owner_user_id:null,owner_role:null,follow_up_at:'2026-09-15T12:00:00Z',events:[],events_complete:true};
const version={id:other,document_id:other,native_document_id:other,task_id:id,resident_id:id,facility_id:id,document_type:'community_support_plan',title:'Synthetic report',state:'finalized',revision:id,declared_mime:'application/pdf',declared_size_bytes:100,declared_sha256:'a'.repeat(64),bucket:'resident-documents',object_path:`${id}/${other}/${other}/source`,supersedes_version_id:null,prepared_at:'2026-09-13T12:00:00Z',finalized_at:'2026-09-13T12:00:00Z',checksum_verified:true,native_current:true,page_count:null};
const reply=(extra={})=>({task_id:id,eligible:true,availability:'available',reason:'Separate report facts',resident_id:id,can_manage:true,can_intake:false,chase_candidates:[],contacts:[{id,label:'Synthetic contact',type:'other'}],expectations:[expectation],versions:[version],complete:true,...extra});
const response=(body:unknown,status=200)=>({ok:status<400,status,json:async()=>body});const fetchMock=vi.fn();beforeEach(()=>{fetchMock.mockReset();vi.stubGlobal('fetch',fetchMock);});afterEach(()=>{cleanup();vi.unstubAllGlobals();});
async function open(){await userEvent.click(screen.getByText('Provider reports and support plans'));await screen.findByText('Separate report facts');}
it('keeps service without report outstanding and unknown due never overdue',async()=>{fetchMock.mockResolvedValue(response(reply()));render(<ProviderReportPanel {...props}/>);await open();expect(screen.getByText(/Outstanding — not received/)).toBeVisible();expect(screen.getByText('Due rule: Unknown; overdue is not inferred')).toBeVisible();expect(screen.queryByText(/Overdue under documented approval/)).toBeNull();expect(screen.getByText(/Chase commitment: 2026-09-15/)).toBeVisible();expect(screen.getByText(/Required signers: unknown/)).toBeVisible();});
it('requires native write capability for intake even when report readable',async()=>{fetchMock.mockResolvedValue(response(reply()));render(<ProviderReportPanel {...props}/>);await open();expect(screen.queryByText('Native report document intake')).toBeNull();expect(screen.getByText(/Native document upload requires current clinical write permission/)).toBeVisible();});
it('keeps receipt review and renewal distinct and old signature evidence version bound',async()=>{const old={...expectation,current_version_id:other,received_at:'2026-09-13T12:00:00Z',events:[{id,kind:'signature_observation',actor_id:id,recorded_at:'2026-09-13T12:00:00Z',details:{version_id:id,signer_role:'resident',page:2,page_verification:'operator_reported_unverified',object_path:'NEVER SHOW THIS'}}]};fetchMock.mockResolvedValue(response(reply({expectations:[old]})));render(<ProviderReportPanel {...props}/>);await open();expect(screen.getByText(/Current task review: not reviewed. Renewal: separate/)).toBeVisible();await userEvent.click(screen.getByText('Report provenance history'));expect(screen.getByText(`version ID: ${id}`)).toBeVisible();expect(screen.queryByText(/NEVER SHOW THIS/)).toBeNull();expect(screen.getByText(/not cryptographic or provider-verified/)).toBeVisible();});
it('retries exact version-bound review after lost reply without marking all states done',async()=>{fetchMock.mockResolvedValueOnce(response(reply())).mockRejectedValueOnce(new Error('lost')).mockResolvedValueOnce(response(reply()));render(<ProviderReportPanel {...props}/>);await open();await userEvent.click(screen.getByText('Record a distinct report event'));await userEvent.selectOptions(screen.getByLabelText('Report event'),'review');await userEvent.selectOptions(screen.getByLabelText('Exact native document version'),other);await userEvent.selectOptions(screen.getByLabelText('Review result'),'follow_up_needed');await userEvent.type(screen.getByLabelText('Review findings'),'Missing detail');await userEvent.click(screen.getAllByRole('button',{name:'Save factual report event'})[1]);await screen.findByText(/Report save result unknown/);await userEvent.click(screen.getByRole('button',{name:'Retry same report change'}));await screen.findByText('Separate report facts');expect(fetchMock.mock.calls[1][1].body).toBe(fetchMock.mock.calls[2][1].body);expect(JSON.parse(fetchMock.mock.calls[1][1].body)).toMatchObject({action:'review',version_id:other,expected_revision:id,result:'follow_up_needed'});});
it('clears private data after current read failure and aborts scope changes',async()=>{fetchMock.mockResolvedValueOnce(response(reply())).mockRejectedValueOnce(new Error('denied'));const {rerender}=render(<ProviderReportPanel {...props}/>);await open();await userEvent.click(screen.getByRole('button',{name:'Reload provider reports'}));await screen.findByText(/Provider report details unavailable/);expect(screen.queryByText('Synthetic plan')).toBeNull();fetchMock.mockImplementation(()=>new Promise(()=>{}));await userEvent.click(screen.getByRole('button',{name:'Reload provider reports'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(3));const signal=fetchMock.mock.calls[2][1].signal;rerender(<ProviderReportPanel {...props} actorId={other}/>);expect(signal.aborted).toBe(true);});
it('passes structural accessibility with two open task panels',async()=>{fetchMock.mockImplementation((url:string)=>Promise.resolve(response(url.includes(other)?reply({task_id:other,expectations:[],versions:[]}):reply())));const {container}=render(<><ProviderReportPanel {...props}/><ProviderReportPanel {...props} taskId={other}/></>);for(const summary of screen.getAllByText('Provider reports and support plans'))await userEvent.click(summary);await waitFor(()=>expect(screen.getAllByText('Separate report facts')).toHaveLength(2));expect((await axe.run(container,{rules:{'color-contrast':{enabled:false}}})).violations).toEqual([]);});

it.each(['caseworker','resident','administrator'])('records only the selected %s paper observation on its exact version/page',async(role)=>{
 fetchMock.mockResolvedValue(response(reply()));render(<ProviderReportPanel {...props}/>);await open();await userEvent.click(screen.getByText('Record a distinct report event'));await userEvent.selectOptions(screen.getByLabelText('Report event'),'signature_observation');await userEvent.selectOptions(screen.getByLabelText('Exact native document version'),other);await userEvent.selectOptions(screen.getByLabelText('Observed signer role'),role);await userEvent.type(screen.getByLabelText('Name shown on document'),'Synthetic '+role);await userEvent.type(screen.getByLabelText('Observed page number'),'2');await userEvent.type(screen.getByLabelText('Observed signature evidence source'),'Visible synthetic signature mark on page2');await userEvent.click(screen.getAllByRole('button',{name:'Save factual report event'})[1]);await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(2));const body=JSON.parse(fetchMock.mock.calls[1][1].body);expect(body).toMatchObject({action:'signature_observation',signer_role:role,version_id:other,page:2});expect(body.signed_at).toBeUndefined();expect(body.required_signers).toBeUndefined();
});

it('reuses an earlier task document without treating the historical review as the current review',async()=>{
 const past={...expectation,origin_task_id:other,current_version_id:other,last_review:{task_id:other,recorded_at:'2026-08-13T12:00:00Z',reviewer_id:id,result:'reviewed'}};
 fetchMock.mockResolvedValue(response(reply({expectations:[past],versions:[{...version,task_id:other}]})));render(<ProviderReportPanel {...props}/>);await open();expect(screen.getByText(/Current task review: not reviewed/)).toBeVisible();expect(screen.getByText(/Last recorded review.*Earlier task/)).toBeVisible();await userEvent.click(screen.getByText('Record a distinct report event'));await userEvent.selectOptions(screen.getByLabelText('Report event'),'review');await userEvent.selectOptions(screen.getByLabelText('Exact native document version'),other);expect(fetchMock).toHaveBeenCalledOnce();
});
it('preserves historical transport metadata while excluding stale native binding from current actions',async()=>{
 fetchMock.mockResolvedValue(response(reply({versions:[{...version,native_current:false}]})));render(<ProviderReportPanel {...props}/>);await open();await userEvent.click(screen.getByText('Native document versions'));expect(screen.getByText(/Historical or unverified native binding/)).toBeVisible();expect(screen.queryByRole('button',{name:/Download native version/})).toBeNull();await userEvent.click(screen.getByText('Record a distinct report event'));expect(screen.getByLabelText('Exact native document version').querySelectorAll('option')).toHaveLength(1);
});
it('records a date-only service without inventing midnight',async()=>{
 fetchMock.mockResolvedValue(response(reply()));render(<ProviderReportPanel {...props}/>);await open();await userEvent.click(screen.getByText('Record an expected report after service'));await userEvent.selectOptions(screen.getByLabelText('Service contact'),id);await userEvent.selectOptions(screen.getByLabelText('Expected document type'),'support_plan');await userEvent.type(screen.getByLabelText('Expected version description'),'Separate support plan');const date=screen.getByLabelText('Actual service date');fireEvent.change(date,{target:{value:'2026-09-01'}});await userEvent.type(screen.getByLabelText('Operator service confirmation source'),'Paper visit record');await userEvent.click(screen.getAllByRole('button',{name:'Save factual report event'})[0]);await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(2));const body=JSON.parse(fetchMock.mock.calls[1][1].body);expect(body.service_on).toBe('2026-09-01');expect(body.service_at).toBeUndefined();
});
it('offers readable issue and same-version signature correction pickers instead of ID textboxes',async()=>{
 const observed={...expectation,events:[{id,kind:'signature_observation',actor_id:id,recorded_at:'2026-09-01T12:00:00Z',details:{version_id:other,signer_role:'caseworker',signer_label:'Synthetic worker',page:2}}]};fetchMock.mockResolvedValue(response(reply({expectations:[observed],chase_candidates:[{id,label:'Generic follow-up',status:'open',owner_label:'Case owner'}]})));render(<ProviderReportPanel {...props}/>);await open();await userEvent.click(screen.getByText('Record a distinct report event'));await userEvent.selectOptions(screen.getByLabelText('Report event'),'link_chase');expect(screen.getByRole('option',{name:'Generic follow-up · open · Case owner'})).toBeInTheDocument();await userEvent.selectOptions(screen.getByLabelText('Report event'),'signature_observation');await userEvent.selectOptions(screen.getByLabelText('Exact native document version'),other);expect(screen.getByRole('option',{name:/caseworker · Synthetic worker/})).toBeInTheDocument();expect(screen.queryByRole('textbox',{name:/ID/})).toBeNull();
});
