import type { RawCorrection, RawFloorUnlock, RawPunch, RawSyncRejection } from "@/lib/timeclock/compute";

export type PayrollMethod = "phone" | "run";
export type PacketStatus = "draft" | "approved" | "reported" | "reconciled";
export type PayBasis = "hourly" | "salary";
export type PayrollPolicy = {
  employerName: string;
  payFrequency: "weekly" | "biweekly";
  anchorDate: string;
  workweekDay: number;
  workweekTime: string;
  timeZone: string;
  overtimeThresholdMinutes: number;
  overtimeFacilityIds: string[];
  calculationMode: "automatic" | "reviewed";
  mealPolicy: "punched_unpaid" | "paid";
  roundingMinutes: 0 | 5 | 6 | 15;
  salaryTreatment: "hours" | "amount" | "unchanged";
  approvalRole: "central" | "facility";
  defaultMethod: PayrollMethod;
  policyNote: string;
};
export type PayrollPolicyRecord = {
  organization_id: string;
  facility_id: string;
  config: Partial<PayrollPolicy>;
  revision: number;
  confirmed_at: string | null;
  confirmed_by: string | null;
  updated_by?: string | null;
  updated_by_name?: string | null;
  updated_at: string;
};
export type PacketInput = {
  staffId: string;
  payrollId: string;
  payBasis: PayBasis | null;
  department: "administration" | "operations";
  regularMinutes: number | null;
  overtimeMinutes: number | null;
  holidayMinutes: number;
  personalMinutes: number;
  trainingMinutes: number;
  onCallCents: number;
  bonusCents: number;
  salaryCents: number | null;
  note: string;
  reason: string;
  reviewed: boolean;
};
export type PayrollPerson = {
  id: string;
  name: string;
  facilityId: string;
  role: string;
  employmentStatus: string;
  userId: string | null;
  employeeNumber: string | null;
  hireDate?: string | null;
  terminationDate?: string | null;
};
export type PayrollSource = {
  facilityId: string;
  facilityName: string;
  sourceRevision: string;
  policy: PayrollPolicyRecord | null;
  groupPolicies: PayrollPolicyRecord[];
  people: PayrollPerson[];
  punches: RawPunch[];
  corrections: RawCorrection[];
  rejections: RawSyncRejection[];
  floorUnlocks: Array<RawFloorUnlock & { facility_id: string }>;
};
export type PacketRow = PacketInput & {
  name: string;
  role: string;
  workedMinutes: number | null;
  mealMinutes: number | null;
  paidWorkMinutes: number | null;
  paidMinutes: number | null;
  issues: string[];
  sourcePunchIds: string[];
  sourceCorrectionIds: string[];
};
export type PacketTotals = {
  regularMinutes: number | null;
  overtimeMinutes: number | null;
  holidayMinutes: number;
  personalMinutes: number;
  trainingMinutes: number;
  paidMinutes: number | null;
  workedMinutes: number | null;
  onCallCents: number;
  bonusCents: number;
  salaryCents: number | null;
};
export type PacketSnapshot = {
  schemaVersion: 1;
  facilityId: string;
  facilityName: string;
  employerName: string;
  periodStart: string;
  periodEnd: string;
  checkDate: string;
  generatedAt: string;
  sourceRevision: string;
  policy: Partial<PayrollPolicy> | null;
  policyConfirmedAt: string | null;
  rows: PacketRow[];
  totals: PacketTotals;
  blockers: string[];
  warnings: string[];
};
export type PayrollPacket = {
  id: string;
  root_id: string;
  amends_packet_id: string | null;
  version: number;
  revision: number;
  organization_id: string;
  facility_id: string;
  period_start: string;
  period_end: string;
  check_date: string;
  status: PacketStatus;
  inputs: PacketInput[];
  snapshot: PacketSnapshot;
  source_revision: string;
  policy_revision: number;
  created_at: string;
  created_by: string;
  created_by_name?: string | null;
  updated_at: string;
  approved_at: string | null;
  approved_by: string | null;
  approved_by_name: string | null;
  document_hash: string | null;
  reported_at: string | null;
  reported_by: string | null;
  reported_by_name?: string | null;
  report_method: PayrollMethod | null;
  report_reference: string | null;
  reconciled_at: string | null;
  reconciled_by: string | null;
  reconciled_by_name?: string | null;
  reconciliation_note: string | null;
  amendment_reason: string | null;
};
export type PacketEvent = { id: string; packet_id: string; action: string; actor_id: string; actor_name?: string | null; created_at: string; detail: Record<string, unknown> };
export type PacketDetail = { packet: PayrollPacket; events: PacketEvent[]; versions: Array<Pick<PayrollPacket, "id" | "version" | "status">>; stale: boolean };
export type PacketHub = { packets: PayrollPacket[]; policy: PayrollPolicyRecord | null; facilities: Array<{ id: string; name: string }>; canConfigure: boolean };
