import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";
import { chromium } from "playwright";
import AxeBuilder from "@axe-core/playwright";

const origin = "http://127.0.0.1:8949";
const output = process.env.PAYROLL_PROOF_DIR;
if (!output?.includes("/.hermes/tmp/agent-runs/")) throw new Error("Owned proof output required");
await fs.mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const checks = [], errors = [], external = [], accessibility = [];
const sha = bytes => createHash("sha256").update(bytes).digest("hex");
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: "reduce" });
  await context.route("**/*", route => { const u = new URL(route.request().url()); if (u.origin === origin || ["data:", "blob:"].includes(u.protocol)) return route.continue(); external.push(u.origin); return route.abort(); });
  const page = await context.newPage(); page.on("pageerror", e => errors.push(e.message));
  const proof = () => page.request.get(`${origin}/__proof`).then(r => r.json());
  const screenshot = async (name) => { await page.screenshot({ path: path.join(output, name), fullPage: true }); accessibility.push(...(await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations); };
  await page.goto(`${origin}/admin/payroll?scenario=missing-rules`);
  await page.getByRole("heading", { name: "Payroll", exact: true }).waitFor();
  await page.getByRole("button", { name: "Payroll rules", exact: true }).click();
  assert.equal(await page.getByRole("combobox", { name: "Pay frequency", exact: true }).inputValue(), "");
  assert.equal(await page.getByRole("combobox", { name: "Workweek starts on", exact: true }).inputValue(), "");
  assert(await page.getByRole("button", { name: "Confirm payroll rules", exact: true }).isDisabled());
  await screenshot("policy-desktop.png");
  checks.push("Unconfirmed settings do not select a financial rule or enable confirmation without explicit attestation.");
  await page.goto(`${origin}/admin/payroll`);
  await page.getByRole("link", { name: "2026-09-14 – 2026-09-20", exact: true }).click();
  await page.getByRole("heading", { name: /Payroll packet/ }).waitFor();
  assert(await page.getByRole("button", { name: "Approve packet", exact: true }).isDisabled());
  const firstId = (await proof()).firstId;
  const draftPdf = await page.request.get(`${origin}/api/admin/payroll-packets/${firstId}/document?format=pdf`);
  assert((await draftPdf.body()).subarray(0, 5).toString() === "%PDF-");
  assert.equal((await proof()).packets.find(p => p.id === firstId).status, "draft");
  await page.getByLabel("Check date", { exact: true }).fill("2026-09-26");
  await page.getByRole("spinbutton", { name: "Synthetic Employee A: Regular", exact: true }).fill("38.50");
  await page.getByRole("spinbutton", { name: "Synthetic Employee A: Overtime", exact: true }).fill("1.50");
  await page.getByRole("spinbutton", { name: "Synthetic Employee A: On call", exact: true }).fill("12.34");
  const reviews = page.getByLabel("I reviewed this employee’s hours, pay basis and amounts.", { exact: true });
  for (let i = 0; i < await reviews.count(); i++) await reviews.nth(i).check();
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await page.getByText("Totals and checks reflect the saved draft.", { exact: true }).waitFor();
  const saved = (await proof()).packets.find(p => p.id === firstId);
  const employee = saved.snapshot.rows.find(p => p.name === "Synthetic Employee A");
  assert.equal(employee.regularMinutes, 2310); assert.equal(employee.overtimeMinutes, 90); assert.equal(employee.onCallCents, 1234); assert.equal(saved.check_date, "2026-09-26");
  assert.equal(employee.workedMinutes, null); assert.equal(employee.paidMinutes, 2400);
  await screenshot("packet-draft-desktop.png");
  await page.setViewportSize({ width: 390, height: 844 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth));
  await screenshot("packet-draft-phone.png");
  await page.setViewportSize({ width: 1440, height: 1000 });
  checks.push("Draft date and reviewed hours/dollars save with correct minute/cents units; unknown kiosk hours remain unknown; downloads do not report payroll.");
  await page.getByLabel("I reviewed the employees, hours, amounts, period and check date and authorize this packet for payroll entry.", { exact: true }).check();
  await page.getByRole("button", { name: "Approve packet", exact: true }).click();
  await page.getByRole("heading", { name: "Approved payroll record", exact: true }).waitFor();
  assert(await page.getByRole("spinbutton", { name: "Synthetic Employee A: Regular", exact: true }).isDisabled());
  const frozen = await page.request.get(`${origin}/api/admin/payroll-packets/${firstId}/document?format=pdf`).then(r => r.body());
  const frozenHash = sha(frozen);
  await screenshot("packet-approved-desktop.png");
  await page.getByRole("button", { name: "Record phone call / RUN entry", exact: true }).click();
  await page.getByRole("combobox", { name: "How was payroll reported?", exact: true }).selectOption("phone");
  await page.getByLabel("Confirmation reference / call notes", { exact: true }).fill("Synthetic phone confirmation");
  await page.getByRole("button", { name: "Save record", exact: true }).click();
  await page.getByRole("button", { name: "Record a difference", exact: true }).waitFor();
  await page.getByRole("button", { name: "Record a difference", exact: true }).click();
  await page.getByLabel("Reconciliation notes / reference", { exact: true }).fill("Synthetic comparison difference recorded for review");
  await page.getByRole("button", { name: "Save record", exact: true }).click();
  await page.getByRole("button", { name: "Reconcile with ADP", exact: true }).waitFor();
  assert.equal((await proof()).packets.find(p => p.id === firstId).status, "reported");
  await page.getByRole("button", { name: "Reconcile with ADP", exact: true }).click();
  await page.getByLabel("Reconciliation notes / reference", { exact: true }).fill("Synthetic ADP rows and category totals matched");
  await page.getByLabel("I compared the ADP preview or confirmation with this packet and all employees, hours and amounts match.", { exact: true }).check();
  await page.getByRole("button", { name: "Save record", exact: true }).click();
  await page.getByText(/Reconciled on/).waitFor();
  assert.equal(sha(await page.request.get(`${origin}/api/admin/payroll-packets/${firstId}/document?format=pdf`).then(r => r.body())), frozenHash);
  checks.push("Approval freezes the document; Phone reporting and mismatch recording remain separate from explicit ADP reconciliation; original PDF bytes stay identical.");
  await page.getByRole("button", { name: "Create amendment", exact: true }).click();
  await page.getByLabel("Reason for amendment", { exact: true }).fill("Synthetic late correction");
  await page.getByRole("button", { name: "Save record", exact: true }).click();
  await page.getByRole("heading", { name: /Payroll packet v2/ }).waitFor();
  assert(await page.getByRole("button", { name: "Approve packet", exact: true }).isDisabled());
  const amendmentReviews = page.getByLabel("I reviewed this employee’s hours, pay basis and amounts.", { exact: true });
  for (let i = 0; i < await amendmentReviews.count(); i++) await amendmentReviews.nth(i).check();
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await page.getByLabel("I reviewed the employees, hours, amounts, period and check date and authorize this packet for payroll entry.", { exact: true }).check();
  await page.getByRole("button", { name: "Approve packet", exact: true }).click();
  await page.getByRole("button", { name: "Record phone call / RUN entry", exact: true }).click();
  await page.getByRole("combobox", { name: "How was payroll reported?", exact: true }).selectOption("run");
  await page.getByLabel("Confirmation reference / call notes", { exact: true }).fill("Synthetic RUN entry confirmation");
  await page.getByRole("button", { name: "Save record", exact: true }).click();
  await page.getByRole("button", { name: "Reconcile with ADP", exact: true }).waitFor();
  const final = await proof();
  assert.equal(final.packets.find(p => p.version === 2).report_method, "run");
  assert.equal(final.packets.find(p => p.id === firstId).status, "reconciled");
  assert.equal(final.artifactHashes[firstId], frozenHash);
  checks.push("A linked amendment starts with fresh row review and can be reported through RUN while retaining the reconciled original and its exact document.");
  await page.goto(`${origin}/admin/payroll?scenario=error`);
  await page.getByRole("alert").filter({ hasText: "Synthetic source unavailable" }).waitFor();
  assert.equal(await page.getByText("No payroll packets yet", { exact: true }).count(), 0);
  checks.push("A failed source does not turn into an empty or successful payroll state.");
  assert.equal(errors.length, 0, errors.join("\n")); assert.equal(external.length, 0, "Unexpected external requests");
  const violations = accessibility.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.length }));
  await fs.writeFile(path.join(output, "browser-proof.json"), JSON.stringify({ checked_at: new Date().toISOString(), scope: "Actual UI/calculation/document components with synthetic local persistence; not hosted auth, database, provider or staff acceptance", checks, page_errors: errors, external_requests: external, axe_violations: violations, production_mutations: false }, null, 2));
  assert.equal(violations.length, 0, JSON.stringify(violations));
  console.log(`PASS payroll browser proof: ${checks.length} workflow groups, desktop/phone views, frozen document and both delivery methods.`);
} finally { await browser.close(); }
