import { describe, expect, it } from "vitest";
import { providerReportCommandSchema, providerDocumentPrepareSchema, providerContactCreateSchema } from "./provider-reports";
const id="00000000-0000-0000-0002-000000000003";
const create={action:"create",task_id:id,request_key:"testcase",contact_id:id,document_type:"support_plan",expected_version:"Observed plan",service_on:"2026-09-12",service_provenance:"Operator confirmed from source"};
describe("provider report provenance shapes",()=>{
 it("preserves date-only service without inventing midnight",()=>{const p=providerReportCommandSchema.parse(create);expect(p).not.toHaveProperty("service_at");expect(p).toHaveProperty("service_on","2026-09-12");});
 it("rejects missing or ambiguous service time precision",()=>{expect(providerReportCommandSchema.safeParse({...create,service_on:undefined}).success).toBe(false);expect(providerReportCommandSchema.safeParse({...create,service_at:"2026-09-12T12:00:00Z"}).success).toBe(false);});
 it("keeps support and community plans separate and rejects invented approval flags",()=>{expect(providerReportCommandSchema.parse({...create,document_type:"community_support_plan"})).toHaveProperty("document_type","community_support_plan");expect(providerReportCommandSchema.safeParse({...create,approved:true}).success).toBe(false);});
 it("retains signature date separately from recording time and permits unknown date",()=>{const p={action:"signature_observation",task_id:id,request_key:"testsign",expectation_id:id,expected_revision:id,version_id:id,signer_role:"caseworker",signer_label:"Observed signer",page:2,source_provenance:"Observed on cited version"};expect(providerReportCommandSchema.safeParse(p).success).toBe(true);expect(providerReportCommandSchema.safeParse({...p,signed_on:"2026-09-01"}).success).toBe(true);expect(providerReportCommandSchema.safeParse({...p,signed_on:"2026-09-01",signed_at:"2026-09-01T12:00:00Z"}).success).toBe(false);});
 it("requires explicit due approval provenance with date precision",()=>{const p={action:"set_due",task_id:id,request_key:"due-0001",expectation_id:id,expected_revision:id,due_on:"2026-09-20",approval_reference:"Observed approval document",approver_label:"Named approver",approved_on:"2026-09-01",effective_date:"2026-09-01",source_version_id:id};expect(providerReportCommandSchema.safeParse(p).success).toBe(true);expect(providerReportCommandSchema.safeParse({...p,approval_reference:undefined}).success).toBe(false);});
 it("does not accept caller bucket/path or unbounded upload metadata",()=>{const p={task_id:id,request_key:"intake-001",document_type:"provider_report",title:"Native report",declared_mime:"application/pdf",declared_size_bytes:12,declared_sha256:"a".repeat(64)};expect(providerDocumentPrepareSchema.safeParse(p).success).toBe(true);expect(providerDocumentPrepareSchema.safeParse({...p,object_path:"elsewhere"}).success).toBe(false);expect(providerDocumentPrepareSchema.safeParse({...p,declared_size_bytes:20971521}).success).toBe(false);});
 it("creates native contact inputs without name-based merge instructions",()=>{expect(providerContactCreateSchema.safeParse({task_id:id,request_key:"contact-001",name:"Caseworker",contact_type:"caseworker"}).success).toBe(true);expect(providerContactCreateSchema.safeParse({task_id:id,request_key:"contact-001",name:"Caseworker",contact_type:"caseworker",merge:true}).success).toBe(false);});
});
