import { beforeEach, describe, expect, it, vi } from "vitest";
import { createHash } from "node:crypto";
vi.mock("./auth",()=>({requireOperationsActor:vi.fn(),revalidateOperationsActor:vi.fn()}));
vi.mock("@/lib/supabase/service-role",()=>({createServiceRoleClient:vi.fn()}));
import { requireOperationsActor,revalidateOperationsActor } from "./auth";
import { createServiceRoleClient } from "@/lib/supabase/service-role";
import { validateProviderDocumentBytes,finalizeProviderDocument,downloadProviderDocument } from "./provider-report-documents";
const id="00000000-0000-0000-0002-000000000003",doc="00000000-0000-0000-0002-000000000004",rev="00000000-0000-0000-0002-000000000005";
const bytes=new TextEncoder().encode("%PDF-1.7 abc"),sha=createHash("sha256").update(bytes).digest("hex"),md5=createHash("md5").update(bytes).digest("hex");
const rpc=vi.fn(),service=vi.fn(),download=vi.fn(),actor={id,organizationId:id,appRole:"owner",currentActor:{client:{rpc,storage:{from:()=>({download})}}}};
let finalized=false,created=0,lost=false;
function target(){return {task_id:id,resident_id:id,version:{id,document_id:doc,native_document_id:finalized?doc:null,task_id:id,resident_id:id,facility_id:id,document_type:"support_plan",title:"Native report",state:finalized?"finalized":"prepared",revision:rev,declared_mime:"application/pdf",declared_size_bytes:12,declared_sha256:sha,bucket:"resident-documents",object_path:`${id}/${doc}/${id}/source`,supersedes_version_id:null,prepared_at:"2026-09-13T12:00:00Z",finalized_at:finalized?"2026-09-13T12:01:00Z":null,checksum_verified:finalized,page_count:null},uploader_id:id,object:{id:doc,version:"object-v1",etag:md5,size:12,mime:"application/pdf"}};}
function request(){return new Request("https://local.test",{method:"POST",body:JSON.stringify({task_id:id,request_key:"finalize-001",expected_revision:rev})});}
beforeEach(()=>{vi.resetAllMocks();finalized=false;created=0;lost=false;vi.mocked(requireOperationsActor).mockResolvedValue({actor} as never);vi.mocked(revalidateOperationsActor).mockResolvedValue({actor} as never);vi.mocked(createServiceRoleClient).mockReturnValue({rpc:service} as never);service.mockResolvedValue({data:null,error:null});download.mockResolvedValue({data:new Blob([bytes]),error:null});rpc.mockImplementation(async(name:string)=>{if(name==="provider_document_target")return {data:target(),error:null};if(name==="finalize_provider_document"){if(!finalized)created++;finalized=true;if(lost){lost=false;throw new Error("lost response");}return {data:{version:target().version},error:null};}throw new Error(name);});});
describe("actual native document byte validation",()=>{
 it("computes both hashes from actual bytes and rejects false size/hash/format",()=>{expect(validateProviderDocumentBytes(bytes,"application/pdf",12,sha)).toEqual({sha256:sha,md5});expect(()=>validateProviderDocumentBytes(bytes,"application/pdf",13,sha)).toThrow();expect(()=>validateProviderDocumentBytes(bytes,"application/pdf",12,"a".repeat(64))).toThrow();expect(()=>validateProviderDocumentBytes(bytes,"image/png",12,sha)).toThrow();});
 it("attests only bytes downloaded with current user access before native finalize",async()=>{const r=await finalizeProviderDocument(request(),id);expect(r.status).toBe(200);expect(created).toBe(1);expect(service).toHaveBeenCalledWith("attest_resident_document_bytes",expect.objectContaining({p_sha256:sha,p_md5:md5,p_size:12,p_uploader:id}));});
 it("rejects changed object identity without a server attestation",async()=>{let n=0;rpc.mockImplementation(async()=>({data:{...target(),object:{...target().object,version:++n===1?"old":"new"}},error:null}));expect((await finalizeProviderDocument(request(),id)).status).toBe(409);expect(service).not.toHaveBeenCalled();});
 it("retains uncertainty and retries a lost successful finalization without duplicate native document",async()=>{lost=true;expect((await finalizeProviderDocument(request(),id)).status).toBe(503);expect(finalized).toBe(true);expect((await finalizeProviderDocument(request(),id)).status).toBe(200);expect(created).toBe(1);});
 it("does not return bytes after current actor revocation",async()=>{finalized=true;vi.mocked(revalidateOperationsActor).mockResolvedValueOnce({actor} as never).mockResolvedValueOnce({response:new Response(null,{status:401})} as never);const r=await downloadProviderDocument(new Request(`https://local.test?task_id=${id}`),id);expect(r.status).toBe(401);});
});
