#!/usr/bin/env npx tsx
/**
 * Generates supabase/migrations/109_onboarding_question_tiers.sql from seed modules.
 * Usage: npx tsx scripts/emit-onboarding-migration-109.ts > supabase/migrations/109_onboarding_question_tiers.sql
 */
import type { OnboardingQuestion } from "../src/lib/onboarding/types";
import { CORE_ONBOARDING_QUESTIONS } from "../src/lib/onboarding/seed-questions-core";
import { EXTENDED_DISCOVERY_QUESTIONS } from "../src/lib/onboarding/seed-questions-extended";

function esc(s: string) {
  return s.replace(/'/g, "''");
}

function rowValues(q: OnboardingQuestion): string {
  const options =
    q.options && q.options.length > 0 ? `'${esc(JSON.stringify(q.options))}'::jsonb` : "NULL::jsonb";
  const help = q.helpText != null ? `'${esc(q.helpText)}'` : "NULL";
  const assigned = q.assignedTo != null ? `'${esc(q.assignedTo)}'` : "NULL";
  const cat = q.category != null ? `'${esc(q.category)}'` : "NULL";
  const sort = q.sortOrder != null ? String(q.sortOrder) : "NULL";
  const req = q.required === false ? "false" : "true";
  const tier = q.tier === "extended" ? "extended" : "core";
  return `('${esc(q.id)}', '${esc(q.prompt)}', ${help}, ${assigned}, '${esc(q.department)}', ${cat}, '${q.importance}', '${q.answerType}', ${req}, ${options}, ${sort}, '${tier}')`;
}

/** Former core.* ids removed in favor of extended.* (same order as first 12 in EXTENDED_DISCOVERY_QUESTIONS). */
const OLD_CORE_IDS = [
  "core.ops.housekeeping",
  "core.hr.turnover",
  "core.expansion.multi-site",
  "core.sales.marketing",
  "core.broker.relations",
  "core.integrations.lab",
  "core.policies.source",
  "core.contracts.key",
  "core.transportation",
  "core.facilities.assets",
  "core.success.story",
  "core.open.questions",
] as const;

const migratedExtended = EXTENDED_DISCOVERY_QUESTIONS.slice(0, 12);
const newExtended = EXTENDED_DISCOVERY_QUESTIONS.filter((q) => (q.sortOrder ?? 0) >= 13);

if (migratedExtended.length !== OLD_CORE_IDS.length) {
  throw new Error("migrated extended slice must match OLD_CORE_IDS length");
}
for (let i = 0; i < OLD_CORE_IDS.length; i++) {
  const q = migratedExtended[i];
  if (!q?.id.startsWith("extended.")) {
    throw new Error(`Expected extended id at index ${i}, got ${q?.id}`);
  }
}

console.log(`-- 109: Core vs Extended tiers — column, renames (FK-safe), core row sync, new extended discovery rows.
-- Generated by scripts/emit-onboarding-migration-109.ts — do not hand-edit without re-running the emitter.

ALTER TABLE public.onboarding_questions
  ADD COLUMN IF NOT EXISTS tier text NOT NULL DEFAULT 'core';

ALTER TABLE public.onboarding_questions
  DROP CONSTRAINT IF EXISTS onboarding_questions_tier_check;

ALTER TABLE public.onboarding_questions
  ADD CONSTRAINT onboarding_questions_tier_check CHECK (tier IN ('core', 'extended'));

-- Rename former core questions to extended.* (insert → re-point responses → delete old id)
`);

for (let i = 0; i < OLD_CORE_IDS.length; i++) {
  const oldId = OLD_CORE_IDS[i];
  const q = migratedExtended[i]!;
  console.log(`
INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
${rowValues(q)};

UPDATE public.onboarding_responses
  SET question_id = '${esc(q.id)}'
  WHERE question_id = '${esc(oldId)}';

DELETE FROM public.onboarding_questions WHERE id = '${esc(oldId)}';
`);
}

console.log(`
-- Sync remaining core.* rows to seed (sort order, tier, and any copy updates e.g. Dietary department)
`);

for (const q of CORE_ONBOARDING_QUESTIONS) {
  console.log(`UPDATE public.onboarding_questions SET
  prompt = '${esc(q.prompt)}',
  help_text = ${q.helpText != null ? `'${esc(q.helpText)}'` : "NULL"},
  assigned_to = ${q.assignedTo != null ? `'${esc(q.assignedTo)}'` : "NULL"},
  department = '${esc(q.department)}',
  category = ${q.category != null ? `'${esc(q.category)}'` : "NULL"},
  importance = '${q.importance}',
  answer_type = '${q.answerType}',
  required = ${q.required === false ? "false" : "true"},
  options = ${q.options && q.options.length > 0 ? `'${esc(JSON.stringify(q.options))}'::jsonb` : "NULL::jsonb"},
  sort_order = ${q.sortOrder != null ? String(q.sortOrder) : "NULL"},
  tier = 'core'
WHERE id = '${esc(q.id)}';
`);
}

console.log(`
-- Net-new extended discovery questions (sort_order 13–58)
INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
${newExtended.map((q) => rowValues(q)).join(",\n")}
ON CONFLICT (id) DO NOTHING;
`);
