#!/usr/bin/env python3
"""Fresh isolated COL157 fixture preparation/retirement. Never touches existing HR drafts."""
import argparse,base64,datetime,json,os,pathlib,secrets,urllib.request,urllib.error,uuid
from guarded import Runtime,ROOT,OUT,REF,NoRedirect,require
PRIVATE=pathlib.Path.home()/'.config/haven-staging/col157-fixture.json'
def lit(value):return "'"+str(value).replace("'","''")+"'"
def main():
 p=argparse.ArgumentParser();p.add_argument('action',choices=['setup','serve','cleanup']);p.add_argument('--ready',required=True);args=p.parse_args();r=Runtime(args.ready,stage=True);r.identify()
 if args.action=='serve':os.chdir(ROOT);os.execvpe('npm',['npm','run','dev','--','--hostname','127.0.0.1','--port','4357'],{**os.environ,**r.env})
 if PRIVATE.exists():require(PRIVATE.stat().st_mode&0o077==0,'Private state required')
 s=json.loads(PRIVATE.read_text()) if PRIVATE.exists() else {'run':'col157-'+secrets.token_hex(6),'target':REF,'sourceSha':r.ready['sourceSha'],**{key:str(uuid.uuid4()) for key in ['org','entity','site','other_site','resident','activity','subject','invoice','payment','census','account','trust_tx','legacy','debit','credit','control','stop_control','connection','rules','batch']},'users':{},'passwords':{},'sessions':{}}
 require(s['target']==REF and s['sourceSha']==r.ready['sourceSha'] and s['run'].startswith('col157-') and not s.get('cleaned'),'Wrong/retired fixture')
 def save():
  fd=os.open(PRIVATE,os.O_CREAT|os.O_TRUNC|os.O_WRONLY,0o600)
  with os.fdopen(fd,'w') as f:json.dump(s,f,indent=2)
 def checkpoint(key,fn):
  if key in s:return s[key]
  require(s.get('pending')!=key,'Uncertain previous fixture mutation: '+key);s['pending']=key;save();value=fn();s[key]=value;s.pop('pending');save();return value
 def auth(path,body=None,method='POST',admin=False):
  r.verify();r.identify();key=r.env['SUPABASE_SERVICE_ROLE_KEY'] if admin else r.env['NEXT_PUBLIC_SUPABASE_ANON_KEY'];headers={'apikey':key,'Authorization':'Bearer '+key,'Content-Type':'application/json'}
  with urllib.request.build_opener(NoRedirect()).open(urllib.request.Request(r.base+'/auth/v1/'+path,data=json.dumps(body).encode() if body is not None else None,method=method,headers=headers),timeout=60) as response:return json.load(response)
 def sql_user(query):
  session=s['sessions']['owner'];claims=json.loads(base64.urlsafe_b64decode(session['access_token'].split('.')[1]+'=='));require(claims.get('session_id') and claims.get('auth_claim_version') is not None,'Actual hooked session required')
  return json.loads(r.sql('BEGIN; SET LOCAL ROLE authenticated; SELECT set_config(\'request.jwt.claims\','+lit(json.dumps(claims))+',true); '+query+'; COMMIT;').splitlines()[-1])
 save()
 if args.action=='setup':
  for actor in ['owner','limited']:
   if actor not in s['users']:
    s['passwords'][actor]=secrets.token_urlsafe(30);save();user=checkpoint('auth_'+actor,lambda actor=actor:auth('admin/users',{'email':s['run']+'-'+actor+'@example.invalid','password':s['passwords'][actor],'email_confirm':True,'user_metadata':{'full_name':'COL157 Synthetic '+actor}},admin=True));s['users'][actor]=user['id'];save()
  today=datetime.date.fromisoformat(r.sql("SELECT (now() AT TIME ZONE 'America/New_York')::date"));s['period']={'start_date':str(today-datetime.timedelta(days=40)),'end_date':str(today-datetime.timedelta(days=39))};s['service_period']={'start_date':str(today-datetime.timedelta(days=70)),'end_date':str(today-datetime.timedelta(days=41))};save()
  def rows():
   q=f"BEGIN; INSERT INTO public.organizations(id,name) VALUES({lit(s['org'])},{lit(s['run'])}); INSERT INTO public.entities(id,organization_id,name,entity_type) VALUES({lit(s['entity'])},{lit(s['org'])},{lit(s['run'])},'llc');"
   for site in ['site','other_site']:q+=f"INSERT INTO public.facilities(id,organization_id,entity_id,name,address_line_1,city,zip,total_licensed_beds,timezone) VALUES({lit(s[site])},{lit(s['org'])},{lit(s['entity'])},{lit(s['run']+' '+site)},'Synthetic','Test','00000',20,'America/New_York');"
   for actor,role in [('owner','owner'),('limited','maintenance_role')]:
    q+=f"INSERT INTO public.user_profiles(id,email,full_name,organization_id,app_role,is_active) VALUES({lit(s['users'][actor])},{lit(s['run']+'-'+actor+'@example.invalid')},{lit('COL157 Synthetic '+actor)},{lit(s['org'])},{lit(role)},true); INSERT INTO public.user_facility_access(user_id,facility_id,organization_id,granted_by) VALUES({lit(s['users'][actor])},{lit(s['site'])},{lit(s['org'])},{lit(s['users']['owner'])}); INSERT INTO public.operation_subject_access(organization_id,facility_id,user_id,scope,granted_by,reason,can_record) VALUES({lit(s['org'])},{lit(s['site'])},{lit(s['users'][actor])},'financial',{lit(s['users']['owner'])},'Synthetic source context',true);"
   q+=f"INSERT INTO public.residents(id,organization_id,facility_id,first_name,last_name,date_of_birth,gender) VALUES({lit(s['resident'])},{lit(s['org'])},{lit(s['site'])},'COL157','Synthetic','1940-01-01','female'); INSERT INTO public.operation_activities(id,organization_id,activity_key,name,activity_kind,subject_kind,origin) VALUES({lit(s['activity'])},{lit(s['org'])},'hfo-al-d17-01','COL157 Synthetic finance source context','linked_domain_action','facility','admin_log'); INSERT INTO public.operation_activity_subjects(id,organization_id,facility_id,subject_kind) VALUES({lit(s['subject'])},{lit(s['org'])},{lit(s['site'])},'facility'); INSERT INTO public.census_daily_log(id,facility_id,organization_id,log_date,total_licensed_beds,occupied_beds,available_beds,hold_beds,maintenance_beds,occupancy_rate) VALUES({lit(s['census'])},{lit(s['site'])},{lit(s['org'])},{lit(s['period']['start_date'])},20,10,10,2,0,0.5);"
   for key,code in [('debit','100'),('credit','200')]:q+=f"INSERT INTO public.gl_accounts(id,organization_id,entity_id,code,name,account_type) VALUES({lit(s[key])},{lit(s['org'])},{lit(s['entity'])},{lit(code)},'Synthetic account','asset');"
   q+=f"INSERT INTO public.entity_gl_settings(organization_id,entity_id,accounts_receivable_id,cash_id,revenue_id) VALUES({lit(s['org'])},{lit(s['entity'])},{lit(s['debit'])},{lit(s['credit'])},{lit(s['credit'])}); INSERT INTO public.invoices(id,resident_id,facility_id,organization_id,entity_id,invoice_number,invoice_date,due_date,period_start,period_end,total,subtotal,balance_due,status) VALUES({lit(s['invoice'])},{lit(s['resident'])},{lit(s['site'])},{lit(s['org'])},{lit(s['entity'])},{lit(s['run'])},{lit(s['period']['start_date'])},{lit(s['period']['end_date'])},{lit(s['service_period']['start_date'])},{lit(s['service_period']['end_date'])},10000,10000,10000,'sent'); INSERT INTO public.resident_trust_accounts(id,organization_id,facility_id,resident_id,balance_cents) VALUES({lit(s['account'])},{lit(s['org'])},{lit(s['site'])},{lit(s['resident'])},0); INSERT INTO public.resident_trust_transactions(id,organization_id,facility_id,resident_id,account_id,direction,amount_cents,balance_after_cents,description,occurred_at,created_by) VALUES({lit(s['trust_tx'])},{lit(s['org'])},{lit(s['site'])},{lit(s['resident'])},{lit(s['account'])},'deposit',500,500,'Synthetic native trust',({lit(s['period']['start_date'])}::timestamp AT TIME ZONE 'America/New_York'),{lit(s['users']['owner'])}); INSERT INTO public.trust_account_entries(id,resident_id,facility_id,organization_id,entry_date,entry_type,amount_cents,balance_after_cents,notes,created_by) VALUES({lit(s['legacy'])},{lit(s['resident'])},{lit(s['site'])},{lit(s['org'])},{lit(s['period']['start_date'])},'adjustment',900,900,'Synthetic separate legacy balance',{lit(s['users']['owner'])}); COMMIT;"
   return r.sql(q)
  checkpoint('rows',rows)
  for actor in s['users']:s['sessions'][actor]=auth('token?grant_type=password',{'email':s['run']+'-'+actor+'@example.invalid','password':s['passwords'][actor]});save()
  rule=checkpoint('hfo_rule',lambda:sql_user('SELECT public.save_operation_requirement_draft_review('+lit(s['activity'])+','+lit(json.dumps({'title':'COL157 Synthetic finance source context','wording':'Source context only','allowed_recorder_roles':['owner'],'subject_kind':'facility'}))+'::jsonb)'))
  checkpoint('hfo_published',lambda:sql_user('SELECT public.publish_operation_requirement_review('+lit(rule['id'])+',clock_timestamp())'))
  site=checkpoint('hfo_site',lambda:sql_user('SELECT public.save_operation_facility_requirement_draft_review('+lit(s['activity'])+','+lit(s['site'])+','+lit(json.dumps({'applicability':'applicable','requirement_version_id':rule['id'],'schedule_status':'needs_confirmation'}))+'::jsonb)'))
  checkpoint('hfo_site_published',lambda:sql_user('SELECT public.publish_operation_facility_requirement_review('+lit(site['id'])+',clock_timestamp())'))
  task=checkpoint('hfo_task',lambda:sql_user('SELECT public.create_operation_manual_occurrence_review('+lit(s['activity'])+','+lit(s['site'])+','+lit(s['subject'])+','+lit(s['run']+'-manual')+",'{}'::jsonb)"));s['task']=task['id'];save()
  checkpoint('payment_recorded',lambda:sql_user('SELECT public.record_finance_payment('+lit(s['payment'])+','+lit(s['resident'])+','+lit(s['invoice'])+','+lit(s['period']['start_date'])+",2500,'check','Synthetic prior-period local payment')"))
  checkpoint('staging_control',lambda:sql_user('SELECT public.set_finance_staging_control('+lit(s['control'])+','+lit(s['entity'])+",0,false,"+lit(s['connection'])+",repeat('a',64),NULL)"))
  checkpoint('batch_rules',lambda:sql_user('SELECT public.register_finance_batch_rules('+lit(s['rules'])+','+lit(s['entity'])+','+lit(json.dumps({'companyReference':'123','accountReferences':['100','200'],'accountingBasis':'accrual','effectiveFrom':'2000-01-01','effectiveTo':'2199-12-31'}))+"::jsonb,repeat('b',64),0)"))
  event=r.sql('SELECT id FROM public.finance_source_events WHERE receipt_id='+lit(s['payment'])+' AND source_id='+lit(s['payment'])+' AND organization_id='+lit(s['org']));require(bool(event),'Authoritative payment event absent')
  members=[{'eventId':event,'lines':[{'accountReference':'100','side':'debit','amountCents':'2500'},{'accountReference':'200','side':'credit','amountCents':'2500'}]}]
  checkpoint('prepared_batch',lambda:sql_user('SELECT public.prepare_finance_batch('+lit(s['batch'])+','+lit(s['entity'])+','+lit(s['site'])+','+lit(s['period']['start_date'])+','+lit(s['rules'])+','+lit(json.dumps(members))+'::jsonb)'))
  s['setupPassed']=True;save();print('Fresh isolated finance fixture prepared')
 else:
  for user in s['users'].values():auth('admin/users/'+user,{'ban_duration':'876000h'},method='PUT',admin=True)
  ids=','.join(lit(user) for user in s['users'].values());org=lit(s['org'])
  r.sql('BEGIN; UPDATE public.operation_subject_access SET revoked_at=coalesce(revoked_at,clock_timestamp()) WHERE organization_id='+org+'; UPDATE public.user_facility_access SET revoked_at=coalesce(revoked_at,clock_timestamp()) WHERE organization_id='+org+'; UPDATE public.user_profiles SET is_active=false WHERE id IN('+ids+'); UPDATE public.facilities SET deleted_at=clock_timestamp() WHERE organization_id='+org+'; UPDATE public.entities SET deleted_at=clock_timestamp() WHERE organization_id='+org+'; UPDATE public.organizations SET deleted_at=clock_timestamp() WHERE id='+org+'; COMMIT;')
  for user in s['users'].values():require(datetime.datetime.fromisoformat(auth('admin/users/'+user,method='GET',admin=True)['banned_until'].replace('Z','+00:00'))>datetime.datetime.now(datetime.timezone.utc),'Ban not verified')
  facts=json.loads(r.sql('SELECT json_build_object(\'inactive\',(SELECT count(*)=2 AND bool_and(NOT is_active) FROM public.user_profiles WHERE id IN('+ids+')),\'site_grants\',(SELECT count(*)=0 FROM public.user_facility_access WHERE organization_id='+org+' AND revoked_at IS NULL),\'subject_grants\',(SELECT count(*)=0 FROM public.operation_subject_access WHERE organization_id='+org+' AND revoked_at IS NULL),\'sites_retired\',(SELECT count(*)=2 AND bool_and(deleted_at IS NOT NULL) FROM public.facilities WHERE organization_id='+org+'),\'org_retired\',(SELECT deleted_at IS NOT NULL FROM public.organizations WHERE id='+org+'))'))
  require(all(facts.values()),'Incomplete cleanup');s['cleaned']=True;save();(OUT/'cleanup.json').write_text(json.dumps({'result':'PASS','facts':facts,'bansVerified':True,'financialAndAuditHistoryRetained':True,'ownedListenerClosed':False},indent=2)+'\n')
if __name__=='__main__':main()
