-- 109: Core vs Extended tiers — column, renames (FK-safe), core row sync, new extended discovery rows.
-- Generated by scripts/emit-onboarding-migration-109.ts — do not hand-edit without re-running the emitter.

ALTER TABLE public.onboarding_questions
  ADD COLUMN IF NOT EXISTS tier text NOT NULL DEFAULT 'core';

ALTER TABLE public.onboarding_questions
  DROP CONSTRAINT IF EXISTS onboarding_questions_tier_check;

ALTER TABLE public.onboarding_questions
  ADD CONSTRAINT onboarding_questions_tier_check CHECK (tier IN ('core', 'extended'));

-- 006's haven_set_updated_at() assigns NEW.updated_by; onboarding_questions has no updated_by (108).
CREATE OR REPLACE FUNCTION public.haven_set_updated_at_onboarding_questions ()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public
  AS $func$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$func$;

DROP TRIGGER IF EXISTS tr_onboarding_questions_set_updated_at ON public.onboarding_questions;
CREATE TRIGGER tr_onboarding_questions_set_updated_at
  BEFORE UPDATE ON public.onboarding_questions
  FOR EACH ROW
  EXECUTE PROCEDURE public.haven_set_updated_at_onboarding_questions ();

-- Rename former core questions to extended.* (insert → re-point responses → delete old id)


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.ops.housekeeping', 'Describe housekeeping and maintenance request flows (submit → assign → verify complete).', 'Environmental issues affect falls, infection control, and satisfaction—mapping reduces blind spots.', 'Maintenance', 'Maintenance / Facilities', 'operations', 'normal', 'long_text', false, NULL::jsonb, 1, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.ops.housekeeping'
  WHERE question_id = 'core.ops.housekeeping';

DELETE FROM public.onboarding_questions WHERE id = 'core.ops.housekeeping';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.hr.turnover', 'What is typical staff turnover and float patterns that could affect super-user availability?', 'Churn changes who holds institutional knowledge—plan champions accordingly.', 'HR', 'HR / Workforce', 'training', 'normal', 'long_text', false, NULL::jsonb, 2, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.hr.turnover'
  WHERE question_id = 'core.hr.turnover';

DELETE FROM public.onboarding_questions WHERE id = 'core.hr.turnover';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.expansion.multi-site', 'What is the roadmap for adding facilities/entities after pilot (standards, governance, timelines)?', 'Multi-site patterns affect configuration, roles, and reporting design early.', 'President', 'Executive / Ownership', 'governance', 'normal', 'long_text', false, NULL::jsonb, 3, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.expansion.multi-site'
  WHERE question_id = 'core.expansion.multi-site';

DELETE FROM public.onboarding_questions WHERE id = 'core.expansion.multi-site';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.sales.marketing', 'What CRM or lead tracking is used for inquiries and move-ins, and who owns the pipeline metrics?', 'Admissions workflows connect to census and revenue—avoid duplicate entry and dropped leads.', 'Sales / Admissions', 'Sales / Admissions', 'operations', 'normal', 'long_text', false, NULL::jsonb, 4, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.sales.marketing'
  WHERE question_id = 'core.sales.marketing';

DELETE FROM public.onboarding_questions WHERE id = 'core.sales.marketing';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.broker.relations', 'Are broker or referral relationships material to census—and what data must stay out of general staff view?', 'Sensitive commercial relationships need role separation and clean permissions.', 'CEO', 'Executive / Ownership', 'governance', 'normal', 'long_text', false, NULL::jsonb, 5, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.broker.relations'
  WHERE question_id = 'core.broker.relations';

DELETE FROM public.onboarding_questions WHERE id = 'core.broker.relations';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.integrations.lab', 'What lab, imaging, or external clinical integrations exist (or are planned) and who owns them?', 'Integration ownership prevents orphaned interfaces and unsafe manual workarounds.', 'IT', 'IT / Devices', 'infrastructure', 'normal', 'long_text', false, NULL::jsonb, 6, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.integrations.lab'
  WHERE question_id = 'core.integrations.lab';

DELETE FROM public.onboarding_questions WHERE id = 'core.integrations.lab';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.policies.source', 'Where is the authoritative policy manual stored today, and how often is it updated?', 'Policy sources anchor training content and in-app guardrails.', 'Compliance', 'Compliance', 'compliance', 'normal', 'long_text', false, NULL::jsonb, 7, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.policies.source'
  WHERE question_id = 'core.policies.source';

DELETE FROM public.onboarding_questions WHERE id = 'core.policies.source';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.contracts.key', 'What key managed care or payer contracts constrain billing workflows or authorizations?', 'Payer rules change prior auth and billing steps—surface constraints early.', 'CFO', 'Finance', 'reporting', 'normal', 'long_text', false, NULL::jsonb, 8, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.contracts.key'
  WHERE question_id = 'core.contracts.key';

DELETE FROM public.onboarding_questions WHERE id = 'core.contracts.key';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.ops.transportation', 'How are transportation and appointments scheduled, tracked, and billed (if applicable)?', 'Transport touches liability, resident experience, and staffing—don’t treat it as an afterthought.', 'COO', 'Operations', 'operations', 'normal', 'long_text', false, NULL::jsonb, 9, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.ops.transportation'
  WHERE question_id = 'core.transportation';

DELETE FROM public.onboarding_questions WHERE id = 'core.transportation';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.ops.facility-assets', 'What facility maintenance and capital projects are planned during the pilot window?', 'Construction and network changes can invalidate training and connectivity assumptions.', 'Maintenance', 'Maintenance / Facilities', 'operations', 'normal', 'long_text', false, NULL::jsonb, 10, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.ops.facility-assets'
  WHERE question_id = 'core.facilities.assets';

DELETE FROM public.onboarding_questions WHERE id = 'core.facilities.assets';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.pilot.success-story', 'What does “success” look like for staff on the floor 90 days after go-live (one paragraph)?', 'A concrete staff-level success picture keeps UX and training grounded in reality.', 'COO', 'Operations', 'pilot', 'normal', 'long_text', false, NULL::jsonb, 11, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.pilot.success-story'
  WHERE question_id = 'core.success.story';

DELETE FROM public.onboarding_questions WHERE id = 'core.success.story';


INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.governance.open-questions', 'What unanswered questions or risks should the implementation team track as explicit follow-ups?', 'Capture unknowns so they become tasks instead of hidden assumptions.', 'All leadership', 'Executive / Ownership', 'governance', 'normal', 'long_text', false, NULL::jsonb, 12, 'extended');

UPDATE public.onboarding_responses
  SET question_id = 'extended.governance.open-questions'
  WHERE question_id = 'core.open.questions';

DELETE FROM public.onboarding_questions WHERE id = 'core.open.questions';


-- Sync remaining core.* rows to seed (sort order, tier, and any copy updates e.g. Dietary department)

UPDATE public.onboarding_questions SET
  prompt = 'Who holds final authority for product/build decisions, pilot scope approval, and resolving disagreements?',
  help_text = 'We need a single accountable owner so scope changes, tradeoffs, and sign-off don’t stall the pilot or create rework from conflicting directions.',
  assigned_to = 'CEO',
  department = 'Executive / Ownership',
  category = 'governance',
  importance = 'critical',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 1,
  tier = 'core'
WHERE id = 'core.governance.decision-rights';

UPDATE public.onboarding_questions SET
  prompt = 'What is the escalation path when clinical, operations, and finance disagree on a go-live decision?',
  help_text = 'Clear escalation prevents unsafe shortcuts, budget surprises, or silent overrides that break auditability later.',
  assigned_to = 'COO',
  department = 'Executive / Ownership',
  category = 'governance',
  importance = 'critical',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 2,
  tier = 'core'
WHERE id = 'core.governance.escalation';

UPDATE public.onboarding_questions SET
  prompt = 'What is explicitly in scope for the pilot, and what is explicitly out of scope?',
  help_text = 'Boundaries keep delivery predictable and protect residents/staff from half-built workflows during rollout.',
  assigned_to = 'President',
  department = 'Executive / Ownership',
  category = 'pilot',
  importance = 'critical',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 3,
  tier = 'core'
WHERE id = 'core.pilot.scope';

UPDATE public.onboarding_questions SET
  prompt = 'How will we measure pilot success (metrics, timelines, and who owns each metric)?',
  help_text = 'Success criteria align build priorities with operational reality and give a fair stop/continue decision.',
  assigned_to = 'COO',
  department = 'Executive / Ownership',
  category = 'pilot',
  importance = 'critical',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 4,
  tier = 'core'
WHERE id = 'core.pilot.success';

UPDATE public.onboarding_questions SET
  prompt = 'What is the planned cutover strategy: big-bang, phased by facility, or parallel run—and for how long?',
  help_text = 'Cutover choices drive staffing, training intensity, and risk during the highest-stress window.',
  assigned_to = 'COO',
  department = 'Executive / Ownership',
  category = 'pilot',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 5,
  tier = 'core'
WHERE id = 'core.pilot.cutover';

UPDATE public.onboarding_questions SET
  prompt = 'Which workflows must not break on day one, and what paper or offline fallback exists for each?',
  help_text = 'Identifying cannot-fail workflows focuses testing, support, and rollback planning where harm is highest.',
  assigned_to = 'Director of Nursing',
  department = 'Clinical / Resident Care',
  category = 'workflows',
  importance = 'critical',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 6,
  tier = 'core'
WHERE id = 'core.risk.cannot-fail';

UPDATE public.onboarding_questions SET
  prompt = 'Summarize medication pass, reorder, and pharmacy communication workflows today (who touches what, when).',
  help_text = 'Med workflows are high-risk; mapping real steps prevents dangerous gaps during digital transition.',
  assigned_to = 'Director of Nursing',
  department = 'Clinical / Resident Care',
  category = 'workflows',
  importance = 'critical',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 7,
  tier = 'core'
WHERE id = 'core.clinical.meds';

UPDATE public.onboarding_questions SET
  prompt = 'How are assessments and care plan updates completed, reviewed, and communicated across shifts?',
  help_text = 'Continuity across shifts is where systems fail silently—this clarifies handoffs and accountability.',
  assigned_to = 'Director of Nursing',
  department = 'Clinical / Resident Care',
  category = 'workflows',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 8,
  tier = 'core'
WHERE id = 'core.clinical.assessments';

UPDATE public.onboarding_questions SET
  prompt = 'What is the current incident / elopement reporting path, including regulatory notification expectations?',
  help_text = 'Compliance timing and documentation rules must be reflected in workflows—not discovered after go-live.',
  assigned_to = 'Compliance',
  department = 'Compliance',
  category = 'compliance',
  importance = 'critical',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 9,
  tier = 'core'
WHERE id = 'core.clinical.incidents';

UPDATE public.onboarding_questions SET
  prompt = 'What spreadsheets, binders, side systems, or informal workflows actually run the operation today?',
  help_text = 'Shadow systems hide real process; surfacing them prevents building a tool nobody actually uses.',
  assigned_to = 'COO',
  department = 'Operations',
  category = 'systems',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 10,
  tier = 'core'
WHERE id = 'core.ops.shadow-systems';

UPDATE public.onboarding_questions SET
  prompt = 'How are exceptions handled (e.g., vendor delays, staffing shortfalls) and who approves workarounds?',
  help_text = 'Exception paths become the real process—without them, staff improvise outside the system.',
  assigned_to = 'COO',
  department = 'Operations',
  category = 'operations',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 11,
  tier = 'core'
WHERE id = 'core.ops.exceptions';

UPDATE public.onboarding_questions SET
  prompt = 'How are diets, allergies, and meal service exceptions communicated between dietary and care staff?',
  help_text = 'Meal errors are preventable harm; clarity here protects residents and survey outcomes.',
  assigned_to = 'Dietary Manager',
  department = 'Dietary',
  category = 'operations',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 12,
  tier = 'core'
WHERE id = 'core.ops.dietary';

UPDATE public.onboarding_questions SET
  prompt = 'What does leadership need to see weekly vs daily vs monthly across entities and facilities?',
  help_text = 'Reporting cadence drives dashboards, exports, and who must keep data clean.',
  assigned_to = 'CFO',
  department = 'Finance',
  category = 'reporting',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 13,
  tier = 'core'
WHERE id = 'core.finance.reporting';

UPDATE public.onboarding_questions SET
  prompt = 'Summarize billing, collections, and trust-account practices that must remain accurate during rollout.',
  help_text = 'Financial controls are regulated; mistakes here create legal exposure and family conflict.',
  assigned_to = 'CFO',
  department = 'Finance',
  category = 'reporting',
  importance = 'critical',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 14,
  tier = 'core'
WHERE id = 'core.finance.ar';

UPDATE public.onboarding_questions SET
  prompt = 'What are the payroll and timekeeping integrations (or manual steps) that must not break?',
  help_text = 'Pay impacts morale and compliance; parallel-run plans should cover pay periods explicitly.',
  assigned_to = 'CFO',
  department = 'Finance',
  category = 'operations',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 15,
  tier = 'core'
WHERE id = 'core.finance.payroll';

UPDATE public.onboarding_questions SET
  prompt = 'Summarize device, WiFi, and connectivity constraints by facility (or enterprise-wide if uniform).',
  help_text = 'Hardware and connectivity constraints decide what can run on the floor in real conditions.',
  assigned_to = 'IT',
  department = 'IT / Devices',
  category = 'infrastructure',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 16,
  tier = 'core'
WHERE id = 'core.it.devices';

UPDATE public.onboarding_questions SET
  prompt = 'What security policies apply to PHI on workstations, mobile devices, and personal phones?',
  help_text = 'BYOD and shared logins are common failure modes—policies should match how staff actually work.',
  assigned_to = 'IT',
  department = 'IT / Devices',
  category = 'infrastructure',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 17,
  tier = 'core'
WHERE id = 'core.it.security';

UPDATE public.onboarding_questions SET
  prompt = 'What licensure, regulatory, or survey flags should implementation know about (past citations, plans of correction)?',
  help_text = 'Known risk areas change testing priorities and documentation requirements.',
  assigned_to = 'Compliance',
  department = 'Compliance',
  category = 'compliance',
  importance = 'critical',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 18,
  tier = 'core'
WHERE id = 'core.compliance.flags';

UPDATE public.onboarding_questions SET
  prompt = 'What record retention and legal hold requirements apply to clinical and financial records?',
  help_text = 'Retention drives archive strategy and what must be auditable in-platform.',
  assigned_to = 'Compliance',
  department = 'Compliance',
  category = 'compliance',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 19,
  tier = 'core'
WHERE id = 'core.compliance.retention';

UPDATE public.onboarding_questions SET
  prompt = 'What training approach will be used (role-based, by facility, bilingual needs) and who certifies completion?',
  help_text = 'Training plans determine rollout pacing and support staffing.',
  assigned_to = 'HR',
  department = 'HR / Workforce',
  category = 'training',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 20,
  tier = 'core'
WHERE id = 'core.hr.training';

UPDATE public.onboarding_questions SET
  prompt = 'What resident/staff data must migrate from legacy systems, and what is the source of truth?',
  help_text = 'Migration scope affects timelines, validation, and cutover risk.',
  assigned_to = 'IT',
  department = 'IT / Devices',
  category = 'data',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 21,
  tier = 'core'
WHERE id = 'core.data.migration';

UPDATE public.onboarding_questions SET
  prompt = 'Where is data quality weakest today (duplicates, stale contacts, inconsistent diagnoses) and how is it cleaned?',
  help_text = 'Bad data in means bad workflows out—cleansing rules should be explicit.',
  assigned_to = 'COO',
  department = 'Operations',
  category = 'data',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 22,
  tier = 'core'
WHERE id = 'core.data.quality';

UPDATE public.onboarding_questions SET
  prompt = 'Where must AI or automation NEVER replace human judgment (clinical, consent, billing disputes)?',
  help_text = 'Clear boundaries protect residents and keep the operator defensible under licensure and liability.',
  assigned_to = 'CEO',
  department = 'Executive / Ownership',
  category = 'governance',
  importance = 'critical',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 23,
  tier = 'core'
WHERE id = 'core.ai.boundaries';

UPDATE public.onboarding_questions SET
  prompt = 'What audit artifacts are required when AI suggests actions (who reviewed, when, overrides)?',
  help_text = 'Auditability is a regulatory and liability requirement—not optional polish.',
  assigned_to = 'Compliance',
  department = 'Compliance',
  category = 'compliance',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 24,
  tier = 'core'
WHERE id = 'core.ai.audit';

UPDATE public.onboarding_questions SET
  prompt = 'How should families receive updates and who approves messaging that could be clinical or financial?',
  help_text = 'Family communication touches satisfaction and privacy—roles must be explicit.',
  assigned_to = 'Executive Director',
  department = 'Executive / Ownership',
  category = 'operations',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 25,
  tier = 'core'
WHERE id = 'core.family.engagement';

UPDATE public.onboarding_questions SET
  prompt = 'Which vendor or outsourced services are critical path for daily operations (pharmacy, laundry, IT MSP)?',
  help_text = 'Vendor dependencies affect integrations, SLAs, and incident response.',
  assigned_to = 'COO',
  department = 'Operations',
  category = 'operations',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 26,
  tier = 'core'
WHERE id = 'core.vendor.critical';

UPDATE public.onboarding_questions SET
  prompt = 'Summarize emergency preparedness communications (weather, power, clinical surge) used today.',
  help_text = 'Emergency comms must remain reliable if systems change—identify single points of failure.',
  assigned_to = 'COO',
  department = 'Operations',
  category = 'operations',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 27,
  tier = 'core'
WHERE id = 'core.emergency.preparedness';

UPDATE public.onboarding_questions SET
  prompt = 'How is QAPI or quality review conducted today (cadence, metrics, accountable roles)?',
  help_text = 'Quality cycles should map to reporting so leadership sees the same truth operations uses.',
  assigned_to = 'Director of Nursing',
  department = 'Clinical / Resident Care',
  category = 'reporting',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 28,
  tier = 'core'
WHERE id = 'core.quality.qapi';

UPDATE public.onboarding_questions SET
  prompt = 'What board or owner reporting pack is required monthly (finance + clinical + compliance highlights)?',
  help_text = 'Executive reporting sets the minimum credible narrative for governance oversight.',
  assigned_to = 'CFO',
  department = 'Finance',
  category = 'reporting',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 29,
  tier = 'core'
WHERE id = 'core.reporting.board';

UPDATE public.onboarding_questions SET
  prompt = 'What staffing ratio or acuity rules must be reflected in scheduling and census planning?',
  help_text = 'Regulatory staffing expectations affect scheduling modules and alerts.',
  assigned_to = 'Director of Nursing',
  department = 'Clinical / Resident Care',
  category = 'workflows',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 30,
  tier = 'core'
WHERE id = 'core.staffing.ratios';

UPDATE public.onboarding_questions SET
  prompt = 'How are behavioral care plans and interventions coordinated with activities and care staff?',
  help_text = 'Behavior support spans departments—clear ownership reduces inconsistent responses.',
  assigned_to = 'Director of Nursing',
  department = 'Clinical / Resident Care',
  category = 'workflows',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 31,
  tier = 'core'
WHERE id = 'core.behavior.care';

UPDATE public.onboarding_questions SET
  prompt = 'What infection control surveillance and reporting is performed today (outbreaks, tracking tools)?',
  help_text = 'Infection processes often have external reporting obligations—capture them explicitly.',
  assigned_to = 'Compliance',
  department = 'Compliance',
  category = 'compliance',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 32,
  tier = 'core'
WHERE id = 'core.infection.control';

UPDATE public.onboarding_questions SET
  prompt = 'What phone system and on-call escalation tree is used after hours for clinical and maintenance issues?',
  help_text = 'After-hours paths are high-risk; they must remain coherent during system changes.',
  assigned_to = 'COO',
  department = 'Operations',
  category = 'operations',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 33,
  tier = 'core'
WHERE id = 'core.telephony';

UPDATE public.onboarding_questions SET
  prompt = 'Who handles privacy requests, record releases, and resident/family data corrections?',
  help_text = 'Privacy workflows must be assignable and auditable—especially across entities.',
  assigned_to = 'Compliance',
  department = 'Compliance',
  category = 'compliance',
  importance = 'high',
  answer_type = 'long_text',
  required = true,
  options = NULL::jsonb,
  sort_order = 34,
  tier = 'core'
WHERE id = 'core.privacy.requests';

UPDATE public.onboarding_questions SET
  prompt = 'Preferred pilot length (select one)',
  help_text = 'Pilot duration affects resourcing, parallel-run cost, and how much feedback we can incorporate.',
  assigned_to = 'President',
  department = 'Executive / Ownership',
  category = 'pilot',
  importance = 'high',
  answer_type = 'single_select',
  required = true,
  options = '["30 days","60 days","90 days","120+ days"]'::jsonb,
  sort_order = 35,
  tier = 'core'
WHERE id = 'core.single-select.pilot-length';

UPDATE public.onboarding_questions SET
  prompt = 'Will you require a mandatory parallel run with legacy systems before decommissioning?',
  help_text = 'Parallel run reduces risk but increases workload—leadership should confirm expectations explicitly.',
  assigned_to = 'CFO',
  department = 'Finance',
  category = 'pilot',
  importance = 'high',
  answer_type = 'yes_no',
  required = true,
  options = NULL::jsonb,
  sort_order = 36,
  tier = 'core'
WHERE id = 'core.yes-no.parallel-run';


-- Net-new extended discovery questions (sort_order 13–58)
INSERT INTO public.onboarding_questions (
  id, prompt, help_text, assigned_to, department, category, importance, answer_type, required, options, sort_order, tier
) VALUES
('extended.software.resident-records', 'What system is the source of truth for resident clinical and demographic records today (vendor, version, hosting)?', 'Resident data lineage drives migration scope and integration design.', 'IT', 'IT / Devices', 'systems', 'high', 'long_text', false, NULL::jsonb, 13, 'extended'),
('extended.software.emar', 'Describe the eMAR / medication administration system in use (or paper process) and who administers it.', 'Med tech choices affect safety checks, pharmacy interfaces, and training.', 'Director of Nursing', 'Clinical / Resident Care', 'systems', 'high', 'long_text', false, NULL::jsonb, 14, 'extended'),
('extended.software.billing-ar', 'What billing and accounts receivable system(s) are used (per entity or shared), and who owns each?', 'AR stack drives integrations, statements, and trust accounting.', 'CFO', 'Finance', 'systems', 'high', 'long_text', false, NULL::jsonb, 15, 'extended'),
('extended.software.incident-reporting', 'What tool or process is used for internal incident reporting and RCA today (outside of regulatory portals)?', 'Incident tooling affects timelines, notifications, and analytics.', 'Compliance', 'Compliance', 'systems', 'high', 'long_text', false, NULL::jsonb, 16, 'extended'),
('extended.software.scheduling-staffing', 'What scheduling and staffing systems are in use (nursing, dietary, maintenance) and how do they integrate with payroll?', 'Scheduling integrations affect ratios, overtime, and time clocks.', 'HR', 'HR / Workforce', 'systems', 'high', 'long_text', false, NULL::jsonb, 17, 'extended'),
('extended.software.family-comms', 'What tools are used for family communication (calls, email, texting apps, portal) and who sends from each?', 'Channel sprawl affects consent, documentation, and satisfaction.', 'Executive Director', 'Family / Communications', 'systems', 'normal', 'long_text', false, NULL::jsonb, 18, 'extended'),
('extended.software.admissions-census', 'How are admissions pipeline and census tracked today (CRM, spreadsheet, EHR module)?', 'Census truth drives revenue recognition and capacity planning.', 'Sales / Admissions', 'Sales / Admissions', 'systems', 'high', 'long_text', false, NULL::jsonb, 19, 'extended'),
('extended.software.accounting-gl', 'What general ledger / accounting system is used at the entity level, and is it consolidated across facilities?', 'GL boundaries affect intercompany, allocations, and reporting.', 'CFO', 'Finance', 'systems', 'normal', 'long_text', false, NULL::jsonb, 20, 'extended'),
('extended.software.payroll-timekeeping', 'List payroll and timekeeping vendors per entity (or enterprise), including mobile clock rules.', 'Payroll integrations are high-risk during cutover.', 'CFO', 'Finance', 'systems', 'high', 'long_text', false, NULL::jsonb, 21, 'extended'),
('extended.vendor.pharmacy-detail', 'Who is the primary pharmacy vendor per facility, and how are orders, deliveries, and errors escalated?', 'Pharmacy interfaces are clinical-critical and heavily regulated.', 'Director of Nursing', 'Clinical / Resident Care', 'vendors', 'high', 'long_text', false, NULL::jsonb, 22, 'extended'),
('extended.vendor.lab-imaging-telehealth', 'Which lab, imaging, and telehealth vendors are under contract, and how are orders and results routed?', 'External clinical data paths affect orders, results, and billing.', 'IT', 'IT / Devices', 'vendors', 'normal', 'long_text', false, NULL::jsonb, 23, 'extended'),
('extended.vendor.nurse-call-alerts', 'What nurse call, pendant, or wander alert systems are installed, and who responds after hours?', 'Alert infrastructure ties to life safety and liability.', 'Maintenance', 'Maintenance / Facilities', 'vendors', 'high', 'long_text', false, NULL::jsonb, 24, 'extended'),
('extended.vendor.outside-billing-rcm', 'Is any billing or revenue cycle management outsourced? Describe scope and SLAs.', 'RCM handoffs affect claims, denials, and family statements.', 'CFO', 'Finance', 'vendors', 'normal', 'long_text', false, NULL::jsonb, 25, 'extended'),
('extended.vendor.it-msp-detail', 'Who is the IT managed service provider (if any), what do they manage, and how are after-hours escalations handled?', 'MSP boundaries affect access, patching, and incident response.', 'IT', 'IT / Devices', 'vendors', 'high', 'long_text', false, NULL::jsonb, 26, 'extended'),
('extended.vendor.outsourced-services', 'Which services are fully outsourced (laundry, dietary prep, housekeeping, transportation) and how are they supervised?', 'Outsourced lanes still need accountability in the platform.', 'COO', 'Operations', 'vendors', 'normal', 'long_text', false, NULL::jsonb, 27, 'extended'),
('extended.facility.staffing-model-diffs', 'How does staffing model differ by facility (ratios, agency use, PD shifts)?', 'Per-site staffing reality affects scheduling rules and alerts.', 'COO', 'Operations', 'facilities', 'high', 'long_text', false, NULL::jsonb, 28, 'extended'),
('extended.facility.connectivity-hardware-diffs', 'Where do connectivity, devices, or hardware differ materially by facility?', 'Uneven tech stacks break one-size-fits-all rollouts.', 'IT', 'IT / Devices', 'facilities', 'high', 'long_text', false, NULL::jsonb, 29, 'extended'),
('extended.facility.licensure-care-mix', 'How does licensure, memory care mix, or specialty populations differ by facility?', 'Care mix changes workflows, assessments, and compliance surfaces.', 'Compliance', 'Compliance', 'facilities', 'high', 'long_text', false, NULL::jsonb, 30, 'extended'),
('extended.facility.administrator-workflows', 'How do administrator daily workflows differ by facility (approvals, rounds, family contact)?', 'Local admin habits drive adoption and permissions.', 'COO', 'Operations', 'facilities', 'normal', 'long_text', false, NULL::jsonb, 31, 'extended'),
('extended.facility.pilot-site', 'Which facility is the best pilot site and why (readiness, leadership, tech, census stability)?', 'Pilot site selection de-risks the first go-live.', 'President', 'Executive / Ownership', 'pilot', 'high', 'long_text', false, NULL::jsonb, 32, 'extended'),
('extended.lifecycle.admissions-steps', 'List the concrete admissions steps from inquiry to move-in, including approvals and paperwork owners.', 'Admissions sequencing drives CRM, assessments, and bed management.', 'Sales / Admissions', 'Sales / Admissions', 'lifecycle', 'high', 'long_text', false, NULL::jsonb, 33, 'extended'),
('extended.lifecycle.move-in-paperwork', 'What move-in paperwork packets are required and where do signed copies live?', 'Document control affects compliance and family disputes.', 'Sales / Admissions', 'Sales / Admissions', 'lifecycle', 'normal', 'long_text', false, NULL::jsonb, 34, 'extended'),
('extended.lifecycle.discharge-transfer', 'Describe discharge and transfer workflows (hospital return, hospice, another community).', 'Transitions are high-risk for medication and billing errors.', 'Director of Nursing', 'Clinical / Resident Care', 'lifecycle', 'high', 'long_text', false, NULL::jsonb, 35, 'extended'),
('extended.lifecycle.census-management', 'Who owns census changes (bed holds, LOA, hospital holds) and how often is census reconciled to billing?', 'Census drift breaks AR and staffing plans.', 'CFO', 'Finance', 'lifecycle', 'high', 'long_text', false, NULL::jsonb, 36, 'extended'),
('extended.lifecycle.room-bed-logic', 'How are rooms, beds, and level-of-care locations assigned and updated?', 'Bed logic ties to acuity billing and fire safety.', 'COO', 'Operations', 'lifecycle', 'high', 'long_text', false, NULL::jsonb, 37, 'extended'),
('extended.lifecycle.pricing-model', 'How is resident pricing structured (base rate, care levels, ancillary bundles)?', 'Pricing models drive rate tables and statements.', 'CFO', 'Finance', 'revenue', 'high', 'long_text', false, NULL::jsonb, 38, 'extended'),
('extended.lifecycle.loc-pricing', 'How does level-of-care or acuity pricing work in practice (assessment triggers, rate changes)?', 'LOC pricing connects clinical assessments to finance.', 'CFO', 'Finance', 'revenue', 'high', 'long_text', false, NULL::jsonb, 39, 'extended'),
('extended.lifecycle.ancillary-charges', 'What ancillary charges exist (salon, transport, supplies) and how are they authorized and posted?', 'Ancillary leakage affects satisfaction and AR.', 'CFO', 'Finance', 'revenue', 'normal', 'long_text', false, NULL::jsonb, 40, 'extended'),
('extended.lifecycle.collections', 'Describe collections workflow for private pay and third-party payers (roles, scripts, write-offs).', 'Collections touch regulated communications and trust rules.', 'CFO', 'Finance', 'revenue', 'high', 'long_text', false, NULL::jsonb, 41, 'extended'),
('extended.lifecycle.payer-mix', 'Summarize payer mix, Medicaid waiver usage, hospice transitions, and long-term care insurance handling.', 'Payer complexity drives claims workflows and reporting.', 'CFO', 'Finance', 'revenue', 'high', 'long_text', false, NULL::jsonb, 42, 'extended'),
('extended.family.top-complaints', 'What are the top recurring family complaints today, and how are they tracked?', 'Complaint themes inform portal design and service recovery.', 'Executive Director', 'Family / Communications', 'family', 'normal', 'long_text', false, NULL::jsonb, 43, 'extended'),
('extended.family.who-communicates', 'Who is allowed to communicate clinical vs financial information to families, and how is that enforced?', 'Role clarity reduces HIPAA issues and family confusion.', 'Compliance', 'Family / Communications', 'family', 'high', 'long_text', false, NULL::jsonb, 44, 'extended'),
('extended.family.portal-exposure', 'What information should never be exposed in a family portal or automated message?', 'Hard boundaries prevent harmful disclosures.', 'Compliance', 'Family / Communications', 'family', 'high', 'long_text', false, NULL::jsonb, 45, 'extended'),
('extended.family.portal-adoption', 'What is leadership’s appetite for family portal adoption (targets, support model, languages)?', 'Adoption assumptions drive training and support staffing.', 'COO', 'Family / Communications', 'family', 'normal', 'long_text', false, NULL::jsonb, 46, 'extended'),
('extended.family.care-conference-escalation', 'How are care conferences and formal complaints or legal escalations handled today?', 'Escalation paths affect documentation and notifications.', 'Executive Director', 'Family / Communications', 'family', 'normal', 'long_text', false, NULL::jsonb, 47, 'extended'),
('extended.legal.baa-status', 'What is the status of Business Associate Agreements with key vendors and cloud services?', 'BAA gaps block compliant data sharing.', 'Compliance', 'Compliance', 'legal', 'high', 'long_text', false, NULL::jsonb, 48, 'extended'),
('extended.legal.phi-handling', 'What are explicit PHI handling expectations for email, texting, fax, and shared drives?', 'Channel policy must match how staff actually work.', 'Compliance', 'Compliance', 'legal', 'high', 'long_text', false, NULL::jsonb, 49, 'extended'),
('extended.legal.covered-entity', 'How is covered entity vs business associate responsibility allocated across entities and vendors?', 'Structure affects contracts and breach response.', 'CEO', 'Executive / Ownership', 'legal', 'normal', 'long_text', false, NULL::jsonb, 50, 'extended'),
('extended.legal.data-ownership', 'Who owns operational and clinical data at exit (operator vs vendor vs owner), and what export rights exist?', 'Data ownership affects contract terms and migration.', 'CEO', 'Executive / Ownership', 'legal', 'normal', 'long_text', false, NULL::jsonb, 51, 'extended'),
('extended.legal.export-ip', 'What are expectations for data export, reporting IP, and customization ownership at contract end?', 'Export/IP clauses affect build-vs-buy and customization.', 'CEO', 'Executive / Ownership', 'legal', 'normal', 'long_text', false, NULL::jsonb, 52, 'extended'),
('extended.legal.retention-hold', 'Beyond baseline retention, what legal hold or litigation workflows exist that affect records?', 'Holds change what can be deleted or archived.', 'Compliance', 'Compliance', 'legal', 'normal', 'long_text', false, NULL::jsonb, 53, 'extended'),
('extended.product.command-center-metrics', 'What command-center metrics does leadership want on day one vs within 12 months post go-live?', 'Metric phasing prevents dashboard overload at launch.', 'COO', 'Executive / Ownership', 'product', 'normal', 'long_text', false, NULL::jsonb, 54, 'extended'),
('extended.product.cross-facility', 'What cross-facility comparisons are required (benchmarks, rankings, variance thresholds)?', 'Comparisons affect permissions and data model.', 'President', 'Executive / Ownership', 'product', 'normal', 'long_text', false, NULL::jsonb, 55, 'extended'),
('extended.product.multi-entity-expansion', 'What are expectations for adding entities, brands, or management contracts after pilot?', 'Expansion assumptions shape tenancy and reporting.', 'CEO', 'Executive / Ownership', 'product', 'normal', 'long_text', false, NULL::jsonb, 56, 'extended'),
('extended.product.insurance-risk', 'What insurance and enterprise risk workflows should be prioritized after pilot (claims, OSHA, certificates)?', 'Risk workflows often follow clinical and HR stabilization.', 'CFO', 'Finance', 'product', 'normal', 'long_text', false, NULL::jsonb, 57, 'extended'),
('extended.product.module-priorities', 'Rank advanced module priorities after pilot (e.g. referrals, reputation, advanced analytics).', 'Roadmap sequencing protects delivery focus.', 'President', 'Executive / Ownership', 'product', 'normal', 'long_text', false, NULL::jsonb, 58, 'extended')
ON CONFLICT (id) DO NOTHING;

