import fs from "node:fs";
import path from "node:path";

import { parseActivityCatalog } from "../../src/lib/operations/activity-catalog";

// This compiles a reviewed source catalog, never worksheet Y/N cells or executions.
// Run with --check in verification; regenerate only before this migration is deployed.
const root = process.cwd();
const catalog = parseActivityCatalog(JSON.parse(fs.readFileSync(
  path.join(root, "src/lib/operations/activity-catalog.json"), "utf8",
)));
const migration = path.join(root, "supabase/migrations/336_hfo_activity_catalog.sql");
const start = "-- HFO_SOURCE_SEED_BEGIN";
const end = "-- HFO_SOURCE_SEED_END";
const literal = JSON.stringify(catalog).replaceAll("'", "''");
const generated = `${start}
-- Generated by scripts/facility-operations/sync-activity-catalog-seed.ts.
-- All source definitions remain draft; no template/occurrence/performance is created.
DO $hfo_seed$
DECLARE
  v_org constant uuid := '00000000-0000-0000-0000-000000000001';
  v_catalog jsonb := '${literal}'::jsonb;
  v_entry jsonb;
  v_component jsonb;
  v_source uuid;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.organizations WHERE id = v_org) THEN
    RAISE EXCEPTION 'COL organization required for the reviewed Admin Log catalog';
  END IF;
  FOR v_entry IN SELECT value FROM jsonb_array_elements(v_catalog->'entries') LOOP
    v_source := md5(v_org::text || ':' || (v_catalog->>'catalogKey') || ':' || (v_entry->>'sourceId'))::uuid;
    INSERT INTO public.operation_activity_source_items
      (id, organization_id, source_item_id, intake_version, source_file, source_sha256, source_payload, status)
    VALUES (v_source, v_org, v_entry->>'sourceId', v_catalog->>'catalogKey',
      v_catalog->'source'->>'name', v_catalog->'source'->>'sha256', v_entry, 'draft');
    FOR v_component IN SELECT value FROM jsonb_array_elements(v_entry->'components') LOOP
      INSERT INTO public.operation_activities
        (id, organization_id, activity_key, name, activity_kind, subject_kind, origin)
      VALUES ((v_component->>'id')::uuid, v_org, v_component->>'key',
        v_component->>'label', v_component->>'kind', v_component->>'subjectKind', 'admin_log');
      INSERT INTO public.operation_activity_source_mappings (organization_id, source_item_id, activity_id)
      VALUES (v_org, v_source, (v_component->>'id')::uuid);
    END LOOP;
  END LOOP;
END;
$hfo_seed$;
${end}`;
const source = fs.readFileSync(migration, "utf8");
const from = source.indexOf(start);
const through = source.indexOf(end);
if (from < 0 || through < from) throw new Error("Migration source seed markers are missing");
const expected = source.slice(0, from) + generated + source.slice(through + end.length);
if (process.argv.includes("--check")) {
  if (source !== expected) throw new Error("Migration source catalog differs from the validated catalog; regenerate the seed");
  console.log(`PASS: ${catalog.entries.length} source mappings match the migration seed`);
} else {
  fs.writeFileSync(migration, expected);
  console.log(`Wrote ${catalog.entries.length} draft source mappings`);
}
