import { spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";
import path from "node:path";
async function main(){
const frontOffice=process.env.FRONT_OFFICE_ROOT;if(!frontOffice)throw Error("FRONT_OFFICE_ROOT is required for the read-only consumer contract check");
const python=spawnSync("python3",["-B","-c",`import json,sys;from datetime import date,datetime,timezone;sys.path.insert(0,'scripts/stand-up');from worker import source_payload,FACILITIES,KEYS;from test_workbook import MAP;reports=[{'facility_id':MAP[n],'week_start':'2026-09-07','status':'ready','version':2,'source_as_of':'2026-09-07T00:00:00Z','values':dict.fromkeys(KEYS,1),'field_dispositions':dict.fromkeys(KEYS,'provided'),'entry_origin':'manual','first_submitted_at':'2026-09-07T00:00:00Z','last_submitted_at':'2026-09-07T00:01:00Z'} for n in FACILITIES];print(json.dumps([source_payload({'reports':[]},MAP,date(2026,9,7),1,datetime(2026,9,7,tzinfo=timezone.utc)),source_payload({'reports':reports},MAP,date(2026,9,7),2,datetime(2026,9,7,tzinfo=timezone.utc))]))`],{cwd:path.resolve(import.meta.dirname,"../.."),encoding:"utf8"});if(python.status!==0)throw Error(python.stderr);
const payloads=JSON.parse(python.stdout),payload=payloads[0];const model=await import(pathToFileURL(path.join(frontOffice,"src/lib/stand-up/model.ts")).href);const protocol=await import(pathToFileURL(path.join(frontOffice,"src/backend/ingest/protocol.ts")).href);
const allowed=model.allowedStandUpMetrics(false),secret="synthetic-read-only-contract-secret-123456",keyId="col160-local",sentAt="1788777600",contract={keyId,source:"col",datasets:[{dataset:"standup_weekly",metrics:allowed}]};for(const valid of payloads){if(valid.rows.some((row:{metric:string})=>!allowed.includes(row.metric)))throw Error("Haven projection exceeded actual Front Office allowlist");const parsed=model.parseStandUp(valid.rows,false);if(parsed.facilities.length!==5)throw Error("Actual consumer lost expected facility coverage");const raw=new TextEncoder().encode(JSON.stringify(valid));const signature=await protocol.sign(secret,keyId,sentAt,raw);await protocol.validateRequest({method:"POST",headers:new Headers({"content-type":"application/json","x-ingest-key-id":keyId,"x-ingest-sent-at":sentAt,"x-ingest-signature":signature}),raw,contract,secret,now:Number(sentAt)*1000});}
for(const mutate of [(x:Record<string,unknown>)=>({...x,packet_state:1}),(x:Record<string,unknown>)=>({...x,sequence:-1}),(x:Record<string,unknown>)=>({...x,complete:false}),(x:Record<string,unknown>)=>({...x,rows:[...(x.rows as unknown[]),{metric:"expected_facilities",value:5}]})]){
 const bad=new TextEncoder().encode(JSON.stringify(mutate(payload)));const sig=await protocol.sign(secret,keyId,sentAt,bad);let refused=false;try{await protocol.validateRequest({method:"POST",headers:new Headers({"content-type":"application/json","x-ingest-key-id":keyId,"x-ingest-sent-at":sentAt,"x-ingest-signature":sig}),raw:bad,contract,secret,now:Number(sentAt)*1000});}catch{refused=true;}if(!refused)throw Error("Actual Front Office protocol accepted invalid corporate/envelope/sequence/completeness data");
}
async function refused(body:Record<string,unknown>,sent=sentAt,now=Number(sentAt)*1000){const bytes=new TextEncoder().encode(JSON.stringify(body));const sig=await protocol.sign(secret,keyId,sent,bytes);try{await protocol.validateRequest({method:"POST",headers:new Headers({"content-type":"application/json","x-ingest-key-id":keyId,"x-ingest-sent-at":sent,"x-ingest-signature":sig}),raw:bytes,contract,secret,now});}catch{return;}throw Error("Actual Front Office protocol accepted a boundedness/freshness violation");}
await refused({...payload,sourceAsOf:"2026-09-07T00:10:00.000Z"},sentAt,Date.parse("2026-09-07T00:00:00.000Z"));
await refused(payload,String(Number(sentAt)-301),Number(sentAt)*1000);
await refused({...payload,rows:Array.from({length:1001},()=>({metric:"expected_facilities",value:5}))});
let oversized=false;try{await protocol.readBoundedBody(new Request("https://local.invalid",{method:"POST",body:"x".repeat(1_048_577)}));}catch(error){oversized=(error as {code?:string}).code==="invalid_size";}if(!oversized)throw Error("Actual Front Office stream reader accepted a body over one MiB");
console.log(JSON.stringify({status:"PASS",publisher:"Haven source_payload",consumer:"actual Front Office allowedStandUpMetrics/parseStandUp/validateRequest",network_requests:0,dataset:payload.dataset,rows:payload.rows.length}));
}
void main().catch(error=>{console.error(error);process.exitCode=1;});
